City.create(province_id: 2, name: 'ANJULI')
City.create(province_id: 2, name: 'ANQUINCILA')
City.create(province_id: 2, name: 'ANTAPOCA')
City.create(province_id: 2, name: 'ANTINACO')
City.create(province_id: 2, name: 'ANTOFAGASTA DE LA SIERRA')
City.create(province_id: 2, name: 'AZAMPAY')
City.create(province_id: 2, name: 'BALCOSNA')
City.create(province_id: 2, name: 'BAÑADO DE OVANTA')
City.create(province_id: 2, name: 'BANDA DE VARELA')
City.create(province_id: 2, name: 'BELEN')
City.create(province_id: 2, name: 'BELLA VISTA')
City.create(province_id: 2, name: 'BREA')
City.create(province_id: 2, name: 'CAPAYAN')
City.create(province_id: 2, name: 'CAPILLITAS')
City.create(province_id: 2, name: 'CARA CIENAGA')
City.create(province_id: 2, name: 'CARRANZA, ADOLFO E.')
City.create(province_id: 2, name: 'CASA ARMADA')
City.create(province_id: 2, name: 'CERRO NEGRO')
City.create(province_id: 2, name: 'CHAÑAR LAGUNA')
City.create(province_id: 2, name: 'CHAÑARITOS')
City.create(province_id: 2, name: 'CHAQUIAGO')
City.create(province_id: 2, name: 'CHUMBICHA')
City.create(province_id: 2, name: 'CIENAGUITA ,AP.')
City.create(province_id: 2, name: 'COLLAGASTA')
City.create(province_id: 2, name: 'COLPES')
City.create(province_id: 2, name: 'CONCEPCION')
City.create(province_id: 2, name: 'CONDOR HUASI')
City.create(province_id: 2, name: 'CONETA')
City.create(province_id: 2, name: 'COPACABANA')
City.create(province_id: 2, name: 'CORTADERAS')
City.create(province_id: 2, name: 'CULAMPAJA')
City.create(province_id: 2, name: 'EL ALTO')
City.create(province_id: 2, name: 'EL AYBAL')
City.create(province_id: 2, name: 'EL BAÑADO')
City.create(province_id: 2, name: 'EL BAVIANO')
City.create(province_id: 2, name: 'EL BOLSON')
City.create(province_id: 2, name: 'EL CAJON')
City.create(province_id: 2, name: 'EL DIVISADERO')
City.create(province_id: 2, name: 'EL JUMEAL')
City.create(province_id: 2, name: 'EL MEDANO ,AP.KILOMETRO 99')
City.create(province_id: 2, name: 'EL PAJONAL ,EST.POMAN')
City.create(province_id: 2, name: 'EL PORTEZUELO')
City.create(province_id: 2, name: 'EL PUESTO')
City.create(province_id: 2, name: 'EL RODEO')
City.create(province_id: 2, name: 'EL TACO')
City.create(province_id: 2, name: 'ESQUIU')
City.create(province_id: 2, name: 'FIAMBALA')
City.create(province_id: 2, name: 'FUERTE QUEMADO')
City.create(province_id: 2, name: 'GUAYAMBA')
City.create(province_id: 2, name: 'HUALFIN')
City.create(province_id: 2, name: 'HUAYCAMA')
City.create(province_id: 2, name: 'HUILLAPIMA')
City.create(province_id: 2, name: 'ICAÑO')
City.create(province_id: 2, name: 'ILOGA')
City.create(province_id: 2, name: 'INCAHUASI')
City.create(province_id: 2, name: 'INFANZON')
City.create(province_id: 2, name: 'IPIZCA')
City.create(province_id: 2, name: 'JOYANGO')
City.create(province_id: 2, name: 'KILOMETR0 62 ,EST.')
City.create(province_id: 2, name: 'KILOMETRO 1017')
City.create(province_id: 2, name: 'KILOMETRO 38 ,EMB.')
City.create(province_id: 2, name: 'KILOMETRO 969 ,EMB.')
City.create(province_id: 2, name: 'KILOMETRO 997')
City.create(province_id: 2, name: 'LA AGUADA')
City.create(province_id: 2, name: 'LA BAJADA')
City.create(province_id: 2, name: 'LA CIENAGA')
City.create(province_id: 2, name: 'LA CIENAGA')
City.create(province_id: 2, name: 'LA DORADA')
City.create(province_id: 2, name: 'LA GUARDIA')
City.create(province_id: 2, name: 'LA HOYADA')
City.create(province_id: 2, name: 'LA MAJADA')
City.create(province_id: 2, name: 'LA MERCED')
City.create(province_id: 2, name: 'LA PARADA')
City.create(province_id: 2, name: 'LA PUERTA')
City.create(province_id: 2, name: 'LA PUERTA DE SAN JOSE')
City.create(province_id: 2, name: 'LA PUNTILLA')
City.create(province_id: 2, name: 'LA RAMADITA')
City.create(province_id: 2, name: 'LA VIÑA')
City.create(province_id: 2, name: 'LAS CAÑAS')
City.create(province_id: 2, name: 'LAS CUEVAS')
City.create(province_id: 2, name: 'LAS JUNTAS')
City.create(province_id: 2, name: 'LAS JUNTAS')
City.create(province_id: 2, name: 'LAS MOJARRAS')
City.create(province_id: 2, name: 'LAS PIRQUITAS')
City.create(province_id: 2, name: 'LAS TEJAS')
City.create(province_id: 2, name: 'LONDRES')
City.create(province_id: 2, name: 'LORO HUASI')
City.create(province_id: 2, name: 'LOS MORTEROS')
City.create(province_id: 2, name: 'LOS SUNCHOS')
City.create(province_id: 2, name: 'LOS VARELA')
City.create(province_id: 2, name: 'MANANTIALES')
City.create(province_id: 2, name: 'MARENGO')
City.create(province_id: 2, name: 'MEDANITOS')
City.create(province_id: 2, name: 'MIRAFLORES')
City.create(province_id: 2, name: 'MONTE POTRERO')
City.create(province_id: 2, name: 'MUTQUIN')
City.create(province_id: 2, name: 'NACIMIENTO')
City.create(province_id: 2, name: 'NACIMIENTOS DE ABAJO')
City.create(province_id: 2, name: 'NACIMIENTOS DE ARRIBA')
City.create(province_id: 2, name: 'OJO DE AGUA')
City.create(province_id: 2, name: 'OVEJERIA')
City.create(province_id: 2, name: 'PALO BLANCO')
City.create(province_id: 2, name: 'PALO LABRADO')
City.create(province_id: 2, name: 'PIEDRA LARGA')
City.create(province_id: 2, name: 'POMAN')
City.create(province_id: 2, name: 'POMANCILLO')
City.create(province_id: 2, name: 'PUCARA')
City.create(province_id: 2, name: 'PUERTA DE CORRAL QUEMADO')
City.create(province_id: 2, name: 'PUNTA DE BALASTO')
City.create(province_id: 2, name: 'QUIROS')
City.create(province_id: 2, name: 'RAMBLONES')
City.create(province_id: 2, name: 'RECREO')
City.create(province_id: 2, name: 'RINCON')
City.create(province_id: 2, name: 'RIO CHICO')
City.create(province_id: 2, name: 'RIO COLORADO')
City.create(province_id: 2, name: 'RIO DE LA DORADA')
City.create(province_id: 2, name: 'RODEO GRANDE')
City.create(province_id: 2, name: 'ROSARIO DE COLANA')
City.create(province_id: 2, name: 'SALADO')
City.create(province_id: 2, name: 'SAN ANTONIO')
City.create(province_id: 2, name: 'SAN ANTONIO')
City.create(province_id: 2, name: 'SAN ANTONIO ,EST.SAN A.DE LA PAZ')
City.create(province_id: 2, name: 'SAN FDO.DEL VALLE DE CATAMARCA ,EST.')
City.create(province_id: 2, name: 'SAN FERNANDO')
City.create(province_id: 2, name: 'SAN ISIDRO')
City.create(province_id: 2, name: 'SAN JOSE')
City.create(province_id: 2, name: 'SAN JOSE')
City.create(province_id: 2, name: 'SAN JOSE')
City.create(province_id: 2, name: 'SAN JOSE')
City.create(province_id: 2, name: 'SAN MARTIN')
City.create(province_id: 2, name: 'SAN MIGUEL')
City.create(province_id: 2, name: 'SAN MIGUEL')
City.create(province_id: 2, name: 'SANTA CRUZ')
City.create(province_id: 2, name: 'SANTA LUCIA')
City.create(province_id: 2, name: 'SANTA MARIA')
City.create(province_id: 2, name: 'SANTA ROSA')
City.create(province_id: 2, name: 'SANTA ROSA')
City.create(province_id: 2, name: 'SAUJIL')
City.create(province_id: 2, name: 'SAUJIL')
City.create(province_id: 2, name: 'SIJAN')
City.create(province_id: 2, name: 'SISIHUASI')
City.create(province_id: 2, name: 'SUMALAO')
City.create(province_id: 2, name: 'SUMAMPA')
City.create(province_id: 2, name: 'TALAMAYO')
City.create(province_id: 2, name: 'TAPSO')
City.create(province_id: 2, name: 'TATON')
City.create(province_id: 2, name: 'TELARITOS')
City.create(province_id: 2, name: 'TINOGASTA')
City.create(province_id: 2, name: 'TIPAN')
City.create(province_id: 2, name: 'TORO YACO')
City.create(province_id: 2, name: 'TRES PUENTES')
City.create(province_id: 2, name: 'VILISMAN')
City.create(province_id: 2, name: 'VILLA CUBAS')
City.create(province_id: 2, name: 'VILLA DOLORES')
City.create(province_id: 2, name: 'VILLA GIL')
City.create(province_id: 2, name: 'YERBA BUENA')
City.create(province_id: 2, name: 'YOCAN')
City.create(province_id: 3, name: 'AVIA TERAI')
City.create(province_id: 3, name: 'BARRANQUERAS')
City.create(province_id: 3, name: 'BASAIL')
City.create(province_id: 3, name: 'BENITEZ')
City.create(province_id: 3, name: 'CABEZA DE TIGRE')
City.create(province_id: 3, name: 'CACUI ,EST')
City.create(province_id: 3, name: 'CAMPO LARGO')
City.create(province_id: 3, name: 'CAPITAN SOLARI')
City.create(province_id: 3, name: 'CASTELLI ,EST.COLONIA J.J.CASTELLI')
City.create(province_id: 3, name: 'CHARADAI')
City.create(province_id: 3, name: 'CHARATA')
City.create(province_id: 3, name: 'CHOROTIS')
City.create(province_id: 3, name: 'CIERVO PETISO')
City.create(province_id: 3, name: 'COLONIA AGRICOLA ABORIGEN CHACO')
City.create(province_id: 3, name: 'COLONIA BARANDA')
City.create(province_id: 3, name: 'COLONIA BRAVO')
City.create(province_id: 3, name: 'COLONIA CABEZA DE TIGRE')
City.create(province_id: 3, name: 'COLONIA CERVEZA HELADA')
City.create(province_id: 3, name: 'COLONIA EL PARAISAL')
City.create(province_id: 3, name: 'COLONIA ELISA')
City.create(province_id: 3, name: 'COLONIA ELISA')
City.create(province_id: 3, name: 'COLONIA JOSE MARMOL')
City.create(province_id: 3, name: 'COLONIA JUAN JOSE PASO')
City.create(province_id: 3, name: 'COLONIA LA FLORIDA GRANDE')
City.create(province_id: 3, name: 'COLONIA LA TAMBORA')
City.create(province_id: 3, name: 'COLONIA MARIANO SARRATEA')
City.create(province_id: 3, name: 'COLONIA POPULAR')
City.create(province_id: 3, name: 'COLONIA VELAZ')
City.create(province_id: 3, name: 'COLONIAS UNIDAS')
City.create(province_id: 3, name: 'CONCEPCION DEL BERMEJO')
City.create(province_id: 3, name: 'CORONEL DU GRATY')
City.create(province_id: 3, name: 'CORZUELA')
City.create(province_id: 3, name: 'COTE-LAI')
City.create(province_id: 3, name: 'EL ESPINILLO')
City.create(province_id: 3, name: 'EL PERDIDO')
City.create(province_id: 3, name: 'EL PINTADO')
City.create(province_id: 3, name: 'FONTANA')
City.create(province_id: 3, name: 'FORTIN CARDOSO')
City.create(province_id: 3, name: 'FUERTE ESPERANZA')
City.create(province_id: 3, name: 'GANCEDO')
City.create(province_id: 3, name: 'GENERAL CAPDEVILA')
City.create(province_id: 3, name: 'GENERAL DONOVAN')
City.create(province_id: 3, name: 'GENERAL JOSE DE SAN MARTIN ,EST.ZAPALLAR')
City.create(province_id: 3, name: 'GENERAL OBLIGADO')
City.create(province_id: 3, name: 'GENERAL PINEDO')
City.create(province_id: 3, name: 'GENERAL VEDIA')
City.create(province_id: 3, name: 'GIRASOL ,EMB.')
City.create(province_id: 3, name: 'HAUMONIA')
City.create(province_id: 3, name: 'HERMOSO CAMPO')
City.create(province_id: 3, name: 'HORQUILLA')
City.create(province_id: 3, name: 'INGENIERO BARBET')
City.create(province_id: 3, name: 'ITIN')
City.create(province_id: 3, name: 'KILOMETR0 501 ,AP.')
City.create(province_id: 3, name: 'KILOMETRO 22 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 29 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 34 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 39 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 42 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 443 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 474 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 48 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 518 ,DV.')
City.create(province_id: 3, name: 'KILOMETRO 520 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 522 ,DV.')
City.create(province_id: 3, name: 'KILOMETRO 53 ,AP.')
City.create(province_id: 3, name: 'KILOMETRO 59 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 596 ,DV.')
City.create(province_id: 3, name: 'KILOMETRO 602 ,AP.')
City.create(province_id: 3, name: 'KILOMETRO 75')
City.create(province_id: 3, name: 'KILOMETRO 841 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 855 ,EMB.')
City.create(province_id: 3, name: 'KILOMETRO 884 ,EMB.')
City.create(province_id: 3, name: 'LA CHIQUITA ,EMB.')
City.create(province_id: 3, name: 'LA CLOTILDE')
City.create(province_id: 3, name: 'LA EDUVIGIS')
City.create(province_id: 3, name: 'LA ESCONDIDA')
City.create(province_id: 3, name: 'LA ESCONDIDA ,EMB.')
City.create(province_id: 3, name: 'LA FIDELIDAD')
City.create(province_id: 3, name: 'LA LEONESA')
City.create(province_id: 3, name: 'LA PASTORIL ,DV.')
City.create(province_id: 3, name: 'LA SABANA')
City.create(province_id: 3, name: 'LA TIGRA')
City.create(province_id: 3, name: 'LA VERDE')
City.create(province_id: 3, name: 'LA VICUÑA')
City.create(province_id: 3, name: 'LAGUNA BLANCA')
City.create(province_id: 3, name: 'LAGUNA LIMPIA')
City.create(province_id: 3, name: 'LAPACHITO')
City.create(province_id: 3, name: 'LAS BREÑAS')
City.create(province_id: 3, name: 'LAS GARCITAS')
City.create(province_id: 3, name: 'LAS HACHERAS')
City.create(province_id: 3, name: 'LAS PALMAS')
City.create(province_id: 3, name: 'LAS VIBORAS')
City.create(province_id: 3, name: 'LOMA FLORIDA')
City.create(province_id: 3, name: 'LOS FRENTONES')
City.create(province_id: 3, name: 'LOS PALMARES')
City.create(province_id: 3, name: 'LOS QUEBRACHITOS')
City.create(province_id: 3, name: 'MACHAGAI')
City.create(province_id: 3, name: 'MAKALLE')
City.create(province_id: 3, name: 'MANANTIALES')
City.create(province_id: 3, name: 'MIRAFLORES')
City.create(province_id: 3, name: 'NAPALPI')
City.create(province_id: 3, name: 'NAPENAY')
City.create(province_id: 3, name: 'NUEVA POBLACION')
City.create(province_id: 3, name: 'NUEVA POMPEYA')
City.create(province_id: 3, name: 'PALO MARCADO')
City.create(province_id: 3, name: 'PAMPA ALMIRON')
City.create(province_id: 3, name: 'PAMPA CABA ÑARO')
City.create(province_id: 3, name: 'PAMPA DEL CIELO')
City.create(province_id: 3, name: 'PAMPA DEL INDIO')
City.create(province_id: 3, name: 'PAMPA DEL INFIERNO')
City.create(province_id: 3, name: 'PAMPA FLORIDA')
City.create(province_id: 3, name: 'PAMPA GUANACO')
City.create(province_id: 3, name: 'POZO DEL INDIO ,DV.')
City.create(province_id: 3, name: 'POZO HONDO')
City.create(province_id: 3, name: 'PRESIDENCIA ROCA')
City.create(province_id: 3, name: 'PRESIDENCIA ROQUE SAENZ PEÑA')
City.create(province_id: 3, name: 'PUERTO BERMEJO')
City.create(province_id: 3, name: 'PUERTO LAS PALMAS')
City.create(province_id: 3, name: 'PUERTO TIROL')
City.create(province_id: 3, name: 'PUERTO VILELAS')
City.create(province_id: 3, name: 'QUITILIPI')
City.create(province_id: 3, name: 'RESISTENCIA')
City.create(province_id: 3, name: 'RIO MUERTO')
City.create(province_id: 3, name: 'RIO TAPENAGA')
City.create(province_id: 3, name: 'SAMUHU')
City.create(province_id: 3, name: 'SAN BERNARDO')
City.create(province_id: 3, name: 'SAN JUANCITO')
City.create(province_id: 3, name: 'SANTA SYLVINA')
City.create(province_id: 3, name: 'SELVAS DEL RIO DE ORO')
City.create(province_id: 3, name: 'SIMBOLAR')
City.create(province_id: 3, name: 'TACO POZO')
City.create(province_id: 3, name: 'TRES ESTACAS')
City.create(province_id: 3, name: 'TRES ISLETAS')
City.create(province_id: 3, name: 'TRES MOJONES')
City.create(province_id: 3, name: 'TUNALES')
City.create(province_id: 3, name: 'URIEN, ENRIQUE')
City.create(province_id: 3, name: 'VENADOS GRANDES,EMB.')
City.create(province_id: 3, name: 'VILLA ANGELA')
City.create(province_id: 3, name: 'VILLA BERTHET')
City.create(province_id: 3, name: 'YATAY')
City.create(province_id: 3, name: 'ZAPARINQUI')
City.create(province_id: 3, name: 'ZUBERBUHLER')
City.create(province_id: 4, name: 'ALDEA')
City.create(province_id: 4, name: 'ALDEA APELEG')
City.create(province_id: 4, name: 'ALTO DE LAS PLUMAS')
City.create(province_id: 4, name: 'ALTO RIO MAYO')
City.create(province_id: 4, name: 'ALTO RIO SENGUERR')
City.create(province_id: 4, name: 'APELEG')
City.create(province_id: 4, name: 'ASTRA')
City.create(province_id: 4, name: 'BAHIA BUSTAMANTE')
City.create(province_id: 4, name: 'BOCA DE LA ZANJA')
City.create(province_id: 4, name: 'BUEN PASTO')
City.create(province_id: 4, name: 'BUENOS AIRES CHICO')
City.create(province_id: 4, name: 'CABO RASO')
City.create(province_id: 4, name: 'CALETA CORDOBA')
City.create(province_id: 4, name: 'CAMARONES')
City.create(province_id: 4, name: 'CAMPAMENTO I')
City.create(province_id: 4, name: 'CAMPAMENTO VILLEGAS ,EST.')
City.create(province_id: 4, name: 'CAMPO ESCALANTE ,AP.')
City.create(province_id: 4, name: 'CAÑADON IGLESIAS')
City.create(province_id: 4, name: 'CAÑADON LAGARTO ,EMB.')
City.create(province_id: 4, name: 'CANQUEL')
City.create(province_id: 4, name: 'CERRO DRAGON')
City.create(province_id: 4, name: 'CHASICO')
City.create(province_id: 4, name: 'CHOLILA')
City.create(province_id: 4, name: 'COLAN CONHUE')
City.create(province_id: 4, name: 'COLELACHE')
City.create(province_id: 4, name: 'COLHUE HUAPI')
City.create(province_id: 4, name: 'COMODORO RIVADAVIA')
City.create(province_id: 4, name: 'DIADEMA ARGENTINA')
City.create(province_id: 4, name: 'DIQUE FLORENTINO AMEGHINO')
City.create(province_id: 4, name: 'DOCTOR RICARDO ROJAS')
City.create(province_id: 4, name: 'DOLAVON')
City.create(province_id: 4, name: 'EL CORCOVADO')
City.create(province_id: 4, name: 'EL MAITEN')
City.create(province_id: 4, name: 'EL MAYOCO')
City.create(province_id: 4, name: 'EL MIRASOL')
City.create(province_id: 4, name: 'EL MOLLE')
City.create(province_id: 4, name: 'EL PAJARITO')
City.create(province_id: 4, name: 'EL SOMBRERO')
City.create(province_id: 4, name: 'EL TORDILLO')
City.create(province_id: 4, name: 'EPUYEN')
City.create(province_id: 4, name: 'ESCALANTE')
City.create(province_id: 4, name: 'ESQUEL')
City.create(province_id: 4, name: 'FACUNDO')
City.create(province_id: 4, name: 'GAIMAN')
City.create(province_id: 4, name: 'GAN GAN')
City.create(province_id: 4, name: 'GARAYALDE')
City.create(province_id: 4, name: 'GASTRE')
City.create(province_id: 4, name: 'GENERAL MOSCONI')
City.create(province_id: 4, name: 'GOBERNADOR COSTA')
City.create(province_id: 4, name: 'GUALJAINA')
City.create(province_id: 4, name: 'HERMITTE, ENRIQUE ,AP.')
City.create(province_id: 4, name: 'HOLDICH')
City.create(province_id: 4, name: 'HOYO DE EPUYEN')
City.create(province_id: 4, name: 'INGENIERO BRUNO J.THOMAE ,AP.')
City.create(province_id: 4, name: 'KILOMETR0 81 ,AP.')
City.create(province_id: 4, name: 'KILOMETRO 11')
City.create(province_id: 4, name: 'KILOMETRO 141')
City.create(province_id: 4, name: 'KILOMETRO 161')
City.create(province_id: 4, name: 'KILOMETRO 191 ,AP.')
City.create(province_id: 4, name: 'KILOMETRO 192')
City.create(province_id: 4, name: 'KILOMETRO 35')
City.create(province_id: 4, name: 'KILOMETRO 78 ,AP.')
City.create(province_id: 4, name: 'KILOMETRO 82 ,AP.')
City.create(province_id: 4, name: 'KILOMETRO 87 ,AP.')
City.create(province_id: 4, name: 'KILOMETRO 95 ,AP.')
City.create(province_id: 4, name: 'LAGO BLANCO')
City.create(province_id: 4, name: 'LAGO PUELO')
City.create(province_id: 4, name: 'LAGO VINTTER')
City.create(province_id: 4, name: 'LAGUNA GRANDE ,EMB.')
City.create(province_id: 4, name: 'LANGUIÑEO')
City.create(province_id: 4, name: 'LAS CHAPAS')
City.create(province_id: 4, name: 'LAS PLUMAS')
City.create(province_id: 4, name: 'LAS PULGAS')
City.create(province_id: 4, name: 'LELEQUE')
City.create(province_id: 4, name: 'LEPA')
City.create(province_id: 4, name: 'LOS CIPRESES')
City.create(province_id: 4, name: 'MALASPINA')
City.create(province_id: 4, name: 'MANANTIALES BERH')
City.create(province_id: 4, name: 'NUEVA LUBECKA')
City.create(province_id: 4, name: 'PAMPA DEL CASTILLO')
City.create(province_id: 4, name: 'PASO DE INDIOS')
City.create(province_id: 4, name: 'PASTOS BLANCOS')
City.create(province_id: 4, name: 'PETROQUIMICA ,EST.COMFERPET')
City.create(province_id: 4, name: 'PICO DE SALAMANCA')
City.create(province_id: 4, name: 'PLAYA UNION')
City.create(province_id: 4, name: 'PUERTO MADRYN')
City.create(province_id: 4, name: 'PUERTO PIRAMIDE')
City.create(province_id: 4, name: 'PUERTO RAWSON')
City.create(province_id: 4, name: 'PUERTO VISSER')
City.create(province_id: 4, name: 'PUNTA DELGADA')
City.create(province_id: 4, name: 'PUTRACHOIQUE')
City.create(province_id: 4, name: 'RADA TILLY')
City.create(province_id: 4, name: 'RAWSON')
City.create(province_id: 4, name: 'RIO MAYO')
City.create(province_id: 4, name: 'RIO PICO')
City.create(province_id: 4, name: 'SACANANA')
City.create(province_id: 4, name: 'SAN MARTIN, JOSE DE')
City.create(province_id: 4, name: 'SARMIENTO')
City.create(province_id: 4, name: 'SIERRA CHATA')
City.create(province_id: 4, name: 'SIERRA NEVADA')
City.create(province_id: 4, name: 'TALAGAPA')
City.create(province_id: 4, name: 'TECKA')
City.create(province_id: 4, name: 'TELSEN')
City.create(province_id: 4, name: 'TRELEW')
City.create(province_id: 4, name: 'TREVELIN')
City.create(province_id: 4, name: 'UZCUDUM')
City.create(province_id: 5, name: 'ACHIRAS')
City.create(province_id: 5, name: 'ADELIA MARIA')
City.create(province_id: 5, name: 'AGUA DE LAS PIEDRAS')
City.create(province_id: 5, name: 'AGUA DE ORO')
City.create(province_id: 5, name: 'AGUA DEL TALA')
City.create(province_id: 5, name: 'AGUAS DE RAMON')
City.create(province_id: 5, name: 'AGUILA BLANCA')
City.create(province_id: 5, name: 'ALCIRA ,EST.GIGENA')
City.create(province_id: 5, name: 'ALEJANDRO ROCA ,EST. ALEJANDRO.')
City.create(province_id: 5, name: 'ALEJO LEDESMA')
City.create(province_id: 5, name: 'ALICIA')
City.create(province_id: 5, name: 'ALMAFUERTE')
City.create(province_id: 5, name: 'ALPA CORRAL')
City.create(province_id: 5, name: 'ALTA CORDOBA')
City.create(province_id: 5, name: 'ALTA CORDOBA ,EST.')
City.create(province_id: 5, name: 'ALTA GRACIA')
City.create(province_id: 5, name: 'ALTAUTINA')
City.create(province_id: 5, name: 'ALTO ALEGRE')
City.create(province_id: 5, name: 'ALTO DEL TALA')
City.create(province_id: 5, name: 'ALTO FRESCO')
City.create(province_id: 5, name: 'ALTO SAN PEDRO')
City.create(province_id: 5, name: 'ALTOS DE CHIPION')
City.create(province_id: 5, name: 'AMBOY')
City.create(province_id: 5, name: 'AMBUL')
City.create(province_id: 5, name: 'ANA ZUMARAN')
City.create(province_id: 5, name: 'ARBOL BLANCO')
City.create(province_id: 5, name: 'ARGUELLO')
City.create(province_id: 5, name: 'ARIAS')
City.create(province_id: 5, name: 'ARROYITO')
City.create(province_id: 5, name: 'ARROYO ALGODON')
City.create(province_id: 5, name: 'ARROYO CABRAL')
City.create(province_id: 5, name: 'ASCOCHINGA')
City.create(province_id: 5, name: 'ASSUNTA')
City.create(province_id: 5, name: 'ATAHONA')
City.create(province_id: 5, name: 'ATOS PAMPA')
City.create(province_id: 5, name: 'AUSONIA')
City.create(province_id: 5, name: 'AVELLANEDA')
City.create(province_id: 5, name: 'BAJO CHICO')
City.create(province_id: 5, name: 'BALDE DE LA MORA')
City.create(province_id: 5, name: 'BALLESTEROS')
City.create(province_id: 5, name: 'BALLESTEROS SUR')
City.create(province_id: 5, name: 'BALNEARIA')
City.create(province_id: 5, name: 'BAÑADO DE SOTO')
City.create(province_id: 5, name: 'BARRANCA YACO')
City.create(province_id: 5, name: 'BARRETO')
City.create(province_id: 5, name: 'BARRIO FLORES ,EMB.')
City.create(province_id: 5, name: 'BELL VILLE')
City.create(province_id: 5, name: 'BENGOLEA')
City.create(province_id: 5, name: 'BENJAMIN GOULD')
City.create(province_id: 5, name: 'BERROTARAN')
City.create(province_id: 5, name: 'BIALET MASSE')
City.create(province_id: 5, name: 'BLAS DE ROSALES')
City.create(province_id: 5, name: 'BOCA DEL TIGRE')
City.create(province_id: 5, name: 'BOUWER')
City.create(province_id: 5, name: 'BRINKMANN')
City.create(province_id: 5, name: 'BUCHARDO ,EST.HIPOLITO BOUCHARD')
City.create(province_id: 5, name: 'BUEN RETIRO ,AP.EL VADO')
City.create(province_id: 5, name: 'BUENA VISTA')
City.create(province_id: 5, name: 'BUEY MUERTO')
City.create(province_id: 5, name: 'BULNES')
City.create(province_id: 5, name: 'BURMEISTER')
City.create(province_id: 5, name: 'CABANA')
City.create(province_id: 5, name: 'CACHI YACO')
City.create(province_id: 5, name: 'CACHIYUYO')
City.create(province_id: 5, name: 'CALCHIN')
City.create(province_id: 5, name: 'CALMAYO')
City.create(province_id: 5, name: 'CAMILO ALDAO')
City.create(province_id: 5, name: 'CAMINIAGA')
City.create(province_id: 5, name: 'CAMPO GRANDE')
City.create(province_id: 5, name: 'CAÑADA DE ALVAREZ')
City.create(province_id: 5, name: 'CAÑADA DE JUME')
City.create(province_id: 5, name: 'CAÑADA DE LUQUE')
City.create(province_id: 5, name: 'CAÑADA DE MACHADO')
City.create(province_id: 5, name: 'CAÑADA DE RIO PINTO')
City.create(province_id: 5, name: 'CAÑADA DE SALAS')
City.create(province_id: 5, name: 'CAÑADA DEL CORO')
City.create(province_id: 5, name: 'CAÑADA HONDA')
City.create(province_id: 5, name: 'CANALS')
City.create(province_id: 5, name: 'CANDELARIA')
City.create(province_id: 5, name: 'CANDELARIA NORTE')
City.create(province_id: 5, name: 'CANDELARIA SUD')
City.create(province_id: 5, name: 'CANDONGA')
City.create(province_id: 5, name: 'CANTERAS EL SAUCE ,EST.EMP.')
City.create(province_id: 5, name: 'CANTERAS QUILPO')
City.create(province_id: 5, name: 'CAPILLA DE LA SAGRADA FAMILIA')
City.create(province_id: 5, name: 'CAPILLA DE LOS REMEDIOS')
City.create(province_id: 5, name: 'CAPILLA DE SITON')
City.create(province_id: 5, name: 'CAPILLA DEL CARMEN')
City.create(province_id: 5, name: 'CAPILLA DEL MONTE')
City.create(province_id: 5, name: 'CAPITAN GENERAL BERNARDO O HIGGINS')
City.create(province_id: 5, name: 'CARCANO, RAMON J.')
City.create(province_id: 5, name: 'CARNERILLO')
City.create(province_id: 5, name: 'CAROLINA')
City.create(province_id: 5, name: 'CAROYA')
City.create(province_id: 5, name: 'CARRILOBO')
City.create(province_id: 5, name: 'CASA BAMBA')
City.create(province_id: 5, name: 'CASA GRANDE')
City.create(province_id: 5, name: 'CASERIO LA LONJA')
City.create(province_id: 5, name: 'CASSAFOUSTH')
City.create(province_id: 5, name: 'CASTRO URDIALES')
City.create(province_id: 5, name: 'CAVALANGO')
City.create(province_id: 5, name: 'CAVANAGH')
City.create(province_id: 5, name: 'CAYUQUEO')
City.create(province_id: 5, name: 'CERRO COLORADO')
City.create(province_id: 5, name: 'CHAJAN')
City.create(province_id: 5, name: 'CHALACEA')
City.create(province_id: 5, name: 'CHALACEA CENTRO')
City.create(province_id: 5, name: 'CHAMICO')
City.create(province_id: 5, name: 'CHAÑAR VIEJO')
City.create(province_id: 5, name: 'CHAÑARITOS')
City.create(province_id: 5, name: 'CHANCANI')
City.create(province_id: 5, name: 'CHARBONIER')
City.create(province_id: 5, name: 'CHARRAS')
City.create(province_id: 5, name: 'CHAZON')
City.create(province_id: 5, name: 'CHILIBROSTE')
City.create(province_id: 5, name: 'CHUCHIRAS')
City.create(province_id: 5, name: 'CHUCUL')
City.create(province_id: 5, name: 'CHUÑA')
City.create(province_id: 5, name: 'CHUÑA HUASI')
City.create(province_id: 5, name: 'CHURQUI CAÑADA')
City.create(province_id: 5, name: 'CIENAGA DE ALLENDE')
City.create(province_id: 5, name: 'CIENAGA DE BRITOS')
City.create(province_id: 5, name: 'CIENAGA DEL CORO')
City.create(province_id: 5, name: 'CINTRA')
City.create(province_id: 5, name: 'COLAZO')
City.create(province_id: 5, name: 'COLONIA 10 DE JULIO')
City.create(province_id: 5, name: 'COLONIA ALMADA')
City.create(province_id: 5, name: 'COLONIA ALMADA')
City.create(province_id: 5, name: 'COLONIA ANITA')
City.create(province_id: 5, name: 'COLONIA ANITA')
City.create(province_id: 5, name: 'COLONIA BISMARCK')
City.create(province_id: 5, name: 'COLONIA BREMEN')
City.create(province_id: 5, name: 'COLONIA CAROYA')
City.create(province_id: 5, name: 'COLONIA COYUNDA')
City.create(province_id: 5, name: 'COLONIA EL CARMEN')
City.create(province_id: 5, name: 'COLONIA LA TORDILLA')
City.create(province_id: 5, name: 'COLONIA LAS CUATRO ESQUINAS')
City.create(province_id: 5, name: 'COLONIA MACKINLAY')
City.create(province_id: 5, name: 'COLONIA MALBERTINA ,EMB.KILOMETRO 531')
City.create(province_id: 5, name: 'COLONIA MARINA')
City.create(province_id: 5, name: 'COLONIA PROSPERIDAD')
City.create(province_id: 5, name: 'COLONIA RIO CHICO')
City.create(province_id: 5, name: 'COLONIA SAN BARTOLOME')
City.create(province_id: 5, name: 'COLONIA SAN PEDRO')
City.create(province_id: 5, name: 'COLONIA SAN RAFAEL')
City.create(province_id: 5, name: 'COLONIA SANTA MARIA')
City.create(province_id: 5, name: 'COLONIA SANTA MARIA')
City.create(province_id: 5, name: 'COLONIA TIROLESA ,EST.')
City.create(province_id: 5, name: 'COLONIA VEINTICINCO')
City.create(province_id: 5, name: 'COLONIA VIDELA')
City.create(province_id: 5, name: 'COLONIA VIGNAUD')
City.create(province_id: 5, name: 'COLONIA WALTELINA')
City.create(province_id: 5, name: 'CONLARA')
City.create(province_id: 5, name: 'COPACABANA')
City.create(province_id: 5, name: 'CORDOBA')
City.create(province_id: 5, name: 'CORONEL BAIGORRIA')
City.create(province_id: 5, name: 'CORONEL MOLDES')
City.create(province_id: 5, name: 'CORONEL OLMEDO')
City.create(province_id: 5, name: 'CORRAL DE BARRANCA')
City.create(province_id: 5, name: 'CORRAL DE BUSTOS')
City.create(province_id: 5, name: 'CORRAL DEL BAJO')
City.create(province_id: 5, name: 'CORRALITO')
City.create(province_id: 5, name: 'CORTES, JERONIMO')
City.create(province_id: 5, name: 'COSME')
City.create(province_id: 5, name: 'COSQUIN')
City.create(province_id: 5, name: 'COSTA SACATE')
City.create(province_id: 5, name: 'COTAGAITA')
City.create(province_id: 5, name: 'CRAIK, JAMES')
City.create(province_id: 5, name: 'CRUZ ALTA')
City.create(province_id: 5, name: 'CRUZ CHICA')
City.create(province_id: 5, name: 'CRUZ DE CAÑA')
City.create(province_id: 5, name: 'CRUZ DEL EJE ,EST.NORTE')
City.create(province_id: 5, name: 'CRUZ DEL QUEMADO')
City.create(province_id: 5, name: 'CRUZ GRANDE')
City.create(province_id: 5, name: 'CRUZ MOJADA')
City.create(province_id: 5, name: 'CUATRO CAMINOS')
City.create(province_id: 5, name: 'CUATRO VIENTOS')
City.create(province_id: 5, name: 'CUCHI CORRAL')
City.create(province_id: 5, name: 'CUEVA DE INDIOS')
City.create(province_id: 5, name: 'CUEVA DE LOS PAJARITOS')
City.create(province_id: 5, name: 'CURAPALIGUE')
City.create(province_id: 5, name: 'DE LA QUINTANA, JOSE')
City.create(province_id: 5, name: 'DE LA SERNA')
City.create(province_id: 5, name: 'DEAN FUNES')
City.create(province_id: 5, name: 'DEL CAMPILLO')
City.create(province_id: 5, name: 'DESPEÑADEROS ,EST.DR.LUCAS A.DE OLMOS')
City.create(province_id: 5, name: 'DEVOTO')
City.create(province_id: 5, name: 'DIQUE SAN ROQUE')
City.create(province_id: 5, name: 'DOCTOR NICASIO SALAS OROÑO')
City.create(province_id: 5, name: 'DOLORES')
City.create(province_id: 5, name: 'DUMESNIL')
City.create(province_id: 5, name: 'EL ARAÑADO')
City.create(province_id: 5, name: 'EL BAÑADO')
City.create(province_id: 5, name: 'EL BAÑADO')
City.create(province_id: 5, name: 'EL BRETE')
City.create(province_id: 5, name: 'EL CADILLO')
City.create(province_id: 5, name: 'EL CANO')
City.create(province_id: 5, name: 'EL CHACHO')
City.create(province_id: 5, name: 'EL CRISPIN')
City.create(province_id: 5, name: 'EL DIQUECITO ,AP.')
City.create(province_id: 5, name: 'EL DURAZNO')
City.create(province_id: 5, name: 'EL DURAZNO')
City.create(province_id: 5, name: 'EL FARO')
City.create(province_id: 5, name: 'EL FLORENTINO')
City.create(province_id: 5, name: 'EL FORTIN')
City.create(province_id: 5, name: 'EL FUERTECITO')
City.create(province_id: 5, name: 'EL GATEADO')
City.create(province_id: 5, name: 'EL MANZANO')
City.create(province_id: 5, name: 'EL MIRADOR')
City.create(province_id: 5, name: 'EL PAMPERO')
City.create(province_id: 5, name: 'EL PAYADOR ,AP.')
City.create(province_id: 5, name: 'EL PERCHEL')
City.create(province_id: 5, name: 'EL PERCHEL')
City.create(province_id: 5, name: 'EL PONIENTE')
City.create(province_id: 5, name: 'EL PORTEZUELO')
City.create(province_id: 5, name: 'EL QUEBRACHO')
City.create(province_id: 5, name: 'EL QUEBRACHO')
City.create(province_id: 5, name: 'EL RASTREADOR')
City.create(province_id: 5, name: 'EL RETIRO')
City.create(province_id: 5, name: 'EL ROSARIO')
City.create(province_id: 5, name: 'EL SAUCE')
City.create(province_id: 5, name: 'EL SUNCHO')
City.create(province_id: 5, name: 'EL TAMBO')
City.create(province_id: 5, name: 'EL TIO')
City.create(province_id: 5, name: 'EL TOSTADO')
City.create(province_id: 5, name: 'EL TUSCAL')
City.create(province_id: 5, name: 'EL VENCE')
City.create(province_id: 5, name: 'EL ZAINO ,AP.')
City.create(province_id: 5, name: 'EL ZAPATO')
City.create(province_id: 5, name: 'ELCANO, SEBASTIAN')
City.create(province_id: 5, name: 'ELENA')
City.create(province_id: 5, name: 'EMBALSE MINISTRO JUAN PISTARINI')
City.create(province_id: 5, name: 'ENCRUCIJADAS')
City.create(province_id: 5, name: 'ESCALANTE, WENCESLAO')
City.create(province_id: 5, name: 'ESCUELA PARACAIDISTAS ,AP.')
City.create(province_id: 5, name: 'ESPINILLO')
City.create(province_id: 5, name: 'ESQUINA')
City.create(province_id: 5, name: 'ESTANCIA DE GUADALUPE')
City.create(province_id: 5, name: 'ETRURIA')
City.create(province_id: 5, name: 'FALDA DEL CARMEN')
City.create(province_id: 5, name: 'FERREYRA')
City.create(province_id: 5, name: 'FLORA')
City.create(province_id: 5, name: 'FRAGUEIRO')
City.create(province_id: 5, name: 'FRAY CAYETANO RODRIGUEZ')
City.create(province_id: 5, name: 'FREYRE')
City.create(province_id: 5, name: 'FUNES, DOMINGO ,AP.')
City.create(province_id: 5, name: 'FUNES, PEDRO E.')
City.create(province_id: 5, name: 'GARCIA, RAFAEL')
City.create(province_id: 5, name: 'GAVILAN ,EST.')
City.create(province_id: 5, name: 'GENERAL BALDISSERA')
City.create(province_id: 5, name: 'GENERAL CABRERA')
City.create(province_id: 5, name: 'GENERAL DEHEZA')
City.create(province_id: 5, name: 'GENERAL FOTHERINGHAM')
City.create(province_id: 5, name: 'GENERAL LEVALLE')
City.create(province_id: 5, name: 'GENERAL ORTIZ DE OCAMPO ,AP.')
City.create(province_id: 5, name: 'GENERAL PAZ')
City.create(province_id: 5, name: 'GENERAL ROCA')
City.create(province_id: 5, name: 'GENERAL SOLER')
City.create(province_id: 5, name: 'GIGENA ESTACION')
City.create(province_id: 5, name: 'GOULD, BENJAMIN')
City.create(province_id: 5, name: 'GUANACO MUERTO')
City.create(province_id: 5, name: 'GUARDIA VIEJA')
City.create(province_id: 5, name: 'GUASAPAMPA')
City.create(province_id: 5, name: 'GUATIMOZIN')
City.create(province_id: 5, name: 'GUIÑAZU')
City.create(province_id: 5, name: 'GUTEMBERG')
City.create(province_id: 5, name: 'HERNANDO')
City.create(province_id: 5, name: 'HUANCHILLA')
City.create(province_id: 5, name: 'HUASCHA')
City.create(province_id: 5, name: 'HUERTA GRANDE')
City.create(province_id: 5, name: 'HUINCA RENANCO')
City.create(province_id: 5, name: 'IDIAZABAL')
City.create(province_id: 5, name: 'IGLESIA VIEJA')
City.create(province_id: 5, name: 'IMPIRA')
City.create(province_id: 5, name: 'INGENIERO MALMEN')
City.create(province_id: 5, name: 'INRIVILLE')
City.create(province_id: 5, name: 'ISCHILIN')
City.create(province_id: 5, name: 'ISCHILIN VIEJO')
City.create(province_id: 5, name: 'ISLA DE SAN ANTONIO')
City.create(province_id: 5, name: 'ISLA VERDE')
City.create(province_id: 5, name: 'ITALO')
City.create(province_id: 5, name: 'JEANMAIRE')
City.create(province_id: 5, name: 'JESUS MARIA')
City.create(province_id: 5, name: 'JUAREZ CELMAN')
City.create(province_id: 5, name: 'JUAREZ, MARCOS')
City.create(province_id: 5, name: 'KILOMETRO 1,5 AP.')
City.create(province_id: 5, name: 'KILOMETRO 136 ,EMP.')
City.create(province_id: 5, name: 'KILOMETRO 16')
City.create(province_id: 5, name: 'KILOMETRO 16')
City.create(province_id: 5, name: 'KILOMETRO 182 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 23')
City.create(province_id: 5, name: 'KILOMETRO 23')
City.create(province_id: 5, name: 'KILOMETRO 25')
City.create(province_id: 5, name: 'KILOMETRO 271 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 316 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 394 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 466 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 480 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 541 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 563 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 57 ,EST.EMB.')
City.create(province_id: 5, name: 'KILOMETRO 579 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 581 ,EMB.')
City.create(province_id: 5, name: 'KILOMETRO 608 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 618 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 636 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 651 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 679')
City.create(province_id: 5, name: 'KILOMETRO 691 ,DV.')
City.create(province_id: 5, name: 'KILOMETRO 7')
City.create(province_id: 5, name: 'KILOMETRO 730 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 745')
City.create(province_id: 5, name: 'KILOMETRO 859 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 865 ,AP.')
City.create(province_id: 5, name: 'KILOMETRO 881 ,EMB.')
City.create(province_id: 5, name: 'KILOMETRO 9')
City.create(province_id: 5, name: 'KILOMETRO 907 ,EST.')
City.create(province_id: 5, name: 'KILOMETRO 931')
City.create(province_id: 5, name: 'LA AGUADA')
City.create(province_id: 5, name: 'LA ARGENTINA')
City.create(province_id: 5, name: 'LA BISMUTINA')
City.create(province_id: 5, name: 'LA BUENA PARADA ,EST.COMECHINGONES')
City.create(province_id: 5, name: 'LA CALERA')
City.create(province_id: 5, name: 'LA CAÑADA')
City.create(province_id: 5, name: 'LA CAÑADA')
City.create(province_id: 5, name: 'LA CARLOTA')
City.create(province_id: 5, name: 'LA CAUTIVA')
City.create(province_id: 5, name: 'LA CORTADERA')
City.create(province_id: 5, name: 'LA CRUZ')
City.create(province_id: 5, name: 'LA CUESTA')
City.create(province_id: 5, name: 'LA CUMBRE')
City.create(province_id: 5, name: 'LA ESPERANZA')
City.create(province_id: 5, name: 'LA ESQUINA')
City.create(province_id: 5, name: 'LA ESTANCIA')
City.create(province_id: 5, name: 'LA FALDA')
City.create(province_id: 5, name: 'LA FRANCIA')
City.create(province_id: 5, name: 'LA GILDA')
City.create(province_id: 5, name: 'LA GRANJA')
City.create(province_id: 5, name: 'LA HERRADURA')
City.create(province_id: 5, name: 'LA HIGUERA')
City.create(province_id: 5, name: 'LA JUANITA')
City.create(province_id: 5, name: 'LA LAGUNA')
City.create(province_id: 5, name: 'LA MAJADILLA')
City.create(province_id: 5, name: 'LA MUDANA')
City.create(province_id: 5, name: 'LA NACIONAL')
City.create(province_id: 5, name: 'LA PALESTINA')
City.create(province_id: 5, name: 'LA PAMPA')
City.create(province_id: 5, name: 'LA PAQUITA ,EST.PRESIDENTE F.ALCORTA')
City.create(province_id: 5, name: 'LA PARA')
City.create(province_id: 5, name: 'LA PATRIA')
City.create(province_id: 5, name: 'LA PAZ')
City.create(province_id: 5, name: 'LA PENCA')
City.create(province_id: 5, name: 'LA PLAYA')
City.create(province_id: 5, name: 'LA PLAYOSA')
City.create(province_id: 5, name: 'LA POBLACION')
City.create(province_id: 5, name: 'LA POSTA')
City.create(province_id: 5, name: 'LA PUERTA')
City.create(province_id: 5, name: 'LA PUERTA')
City.create(province_id: 5, name: 'LA RAMADA')
City.create(province_id: 5, name: 'LA REPRESA')
City.create(province_id: 5, name: 'LA RINCONADA')
City.create(province_id: 5, name: 'LA SERRANITA')
City.create(province_id: 5, name: 'LA TABLADA')
City.create(province_id: 5, name: 'LA TABLADA ,AP.')
City.create(province_id: 5, name: 'LA TIGRA')
City.create(province_id: 5, name: 'LA TOMA')
City.create(province_id: 5, name: 'LA TOMA')
City.create(province_id: 5, name: 'LABORDE')
City.create(province_id: 5, name: 'LABOULAYE')
City.create(province_id: 5, name: 'LAGUNA DEL MONTE')
City.create(province_id: 5, name: 'LAGUNA DEL SUNCHO')
City.create(province_id: 5, name: 'LAGUNA LARGA')
City.create(province_id: 5, name: 'LAGUNA OSCURA')
City.create(province_id: 5, name: 'LAGUNILLA')
City.create(province_id: 5, name: 'LARSEN')
City.create(province_id: 5, name: 'LAS ACEQUIAS')
City.create(province_id: 5, name: 'LAS ARRIAS')
City.create(province_id: 5, name: 'LAS AVERIAS')
City.create(province_id: 5, name: 'LAS BAJADAS')
City.create(province_id: 5, name: 'LAS CALLES')
City.create(province_id: 5, name: 'LAS CAÑITAS')
City.create(province_id: 5, name: 'LAS CHACRAS')
City.create(province_id: 5, name: 'LAS CHACRAS')
City.create(province_id: 5, name: 'LAS CHACRAS')
City.create(province_id: 5, name: 'LAS CHACRAS')
City.create(province_id: 5, name: 'LAS ENSENADAS')
City.create(province_id: 5, name: 'LAS GAMAS')
City.create(province_id: 5, name: 'LAS HIGUERAS')
City.create(province_id: 5, name: 'LAS ISLETILLAS')
City.create(province_id: 5, name: 'LAS JUNTURAS')
City.create(province_id: 5, name: 'LAS MOJARRAS')
City.create(province_id: 5, name: 'LAS MOSTAZAS')
City.create(province_id: 5, name: 'LAS MOSTAZAS')
City.create(province_id: 5, name: 'LAS PALMAS')
City.create(province_id: 5, name: 'LAS PEÑAS')
City.create(province_id: 5, name: 'LAS PEÑAS')
City.create(province_id: 5, name: 'LAS PERDICES')
City.create(province_id: 5, name: 'LAS RABONAS')
City.create(province_id: 5, name: 'LAS SALADAS')
City.create(province_id: 5, name: 'LAS TAPIAS')
City.create(province_id: 5, name: 'LAS TAPIAS')
City.create(province_id: 5, name: 'LAS TOSCAS')
City.create(province_id: 5, name: 'LAS TOSCAS')
City.create(province_id: 5, name: 'LAS VARAS')
City.create(province_id: 5, name: 'LAS VARILLAS')
City.create(province_id: 5, name: 'LAS VERTIENTES')
City.create(province_id: 5, name: 'LASPIUR, SATURNINO M.')
City.create(province_id: 5, name: 'LECUEDER')
City.create(province_id: 5, name: 'LEDESMA, ALEJO')
City.create(province_id: 5, name: 'LEGUIZAMON')
City.create(province_id: 5, name: 'LEONES')
City.create(province_id: 5, name: 'LOA ALAMOS')
City.create(province_id: 5, name: 'LOA ALGARROBOS')
City.create(province_id: 5, name: 'LOMAS DE SAN JOSE')
City.create(province_id: 5, name: 'LOS ALFALFARES')
City.create(province_id: 5, name: 'LOS ALTOS')
City.create(province_id: 5, name: 'LOS CADILLOS')
City.create(province_id: 5, name: 'LOS CALLEJONES')
City.create(province_id: 5, name: 'LOS CERRILLOS')
City.create(province_id: 5, name: 'LOS CERRILLOS')
City.create(province_id: 5, name: 'LOS CHAÑARES')
City.create(province_id: 5, name: 'LOS CHAÑARITOS')
City.create(province_id: 5, name: 'LOS CISNES')
City.create(province_id: 5, name: 'LOS COCOS')
City.create(province_id: 5, name: 'LOS COMETIERRA')
City.create(province_id: 5, name: 'LOS CONDORES')
City.create(province_id: 5, name: 'LOS GIGANTES')
City.create(province_id: 5, name: 'LOS HORNILLOS')
City.create(province_id: 5, name: 'LOS HOYOS')
City.create(province_id: 5, name: 'LOS JAGUELES')
City.create(province_id: 5, name: 'LOS MANANTIALES')
City.create(province_id: 5, name: 'LOS MEDANITOS')
City.create(province_id: 5, name: 'LOS MISTOLES')
City.create(province_id: 5, name: 'LOS MOLINOS')
City.create(province_id: 5, name: 'LOS MOLLES')
City.create(province_id: 5, name: 'LOS MOLLES')
City.create(province_id: 5, name: 'LOS MORTERITOS')
City.create(province_id: 5, name: 'LOS PORONGOS')
City.create(province_id: 5, name: 'LOS POZOS ,AP.KILOMETRO 827')
City.create(province_id: 5, name: 'LOS QUEBRACHITOS')
City.create(province_id: 5, name: 'LOS QUEBRACHITOS')
City.create(province_id: 5, name: 'LOS REARTES')
City.create(province_id: 5, name: 'LOS SAUCES')
City.create(province_id: 5, name: 'LOS SURGENTES')
City.create(province_id: 5, name: 'LOS TARTAROS')
City.create(province_id: 5, name: 'LOS ZORROS')
City.create(province_id: 5, name: 'LOZADA')
City.create(province_id: 5, name: 'LUCA')
City.create(province_id: 5, name: 'LUGONES, LEOPOLDO ,AP.')
City.create(province_id: 5, name: 'LUQUE')
City.create(province_id: 5, name: 'LUTTI')
City.create(province_id: 5, name: 'LUXARDO')
City.create(province_id: 5, name: 'LUYABA')
City.create(province_id: 5, name: 'MACHA')
City.create(province_id: 5, name: 'MAGIGASTA')
City.create(province_id: 5, name: 'MAJADA DE SANTIAGO')
City.create(province_id: 5, name: 'MALAGUENO')
City.create(province_id: 5, name: 'MALENA')
City.create(province_id: 5, name: 'MALLIN')
City.create(province_id: 5, name: 'MALVINAS ARGENTINAS ,EST.KILOMETRO 711')
City.create(province_id: 5, name: 'MANANTIALES')
City.create(province_id: 5, name: 'MANFREDI')
City.create(province_id: 5, name: 'MANSILLA, LUCIO V.')
City.create(province_id: 5, name: 'MAQUINISTA GALLINI')
City.create(province_id: 5, name: 'MARULL')
City.create(province_id: 5, name: 'MATORRALES')
City.create(province_id: 5, name: 'MATTALDI')
City.create(province_id: 5, name: 'MEDIA LUNA')
City.create(province_id: 5, name: 'MEDIA NARANJA')
City.create(province_id: 5, name: 'MELO')
City.create(province_id: 5, name: 'MENDIOLAZA')
City.create(province_id: 5, name: 'MINA CLAVERO')
City.create(province_id: 5, name: 'MIRAMAR')
City.create(province_id: 5, name: 'MOLINARI')
City.create(province_id: 5, name: 'MONTE BUEY')
City.create(province_id: 5, name: 'MONTE CRISTO')
City.create(province_id: 5, name: 'MONTE DE LOS GAUCHOS')
City.create(province_id: 5, name: 'MONTE DEL ROSARIO')
City.create(province_id: 5, name: 'MONTE LEÑA')
City.create(province_id: 5, name: 'MONTE MAIZ')
City.create(province_id: 5, name: 'MONTE RALO')
City.create(province_id: 5, name: 'MONTE REDONDO ,EST.')
City.create(province_id: 5, name: 'MORRISON')
City.create(province_id: 5, name: 'MORTEROS')
City.create(province_id: 5, name: 'MULA MUERTA')
City.create(province_id: 5, name: 'MUSSI')
City.create(province_id: 5, name: 'NARVAJA, TRISTAN ,AP.')
City.create(province_id: 5, name: 'NAZCA')
City.create(province_id: 5, name: 'NINALQUIN')
City.create(province_id: 5, name: 'NOETINGER')
City.create(province_id: 5, name: 'NONO')
City.create(province_id: 5, name: 'NUEVA ALDALUCIA')
City.create(province_id: 5, name: 'NUÑEZ DEL ORADO')
City.create(province_id: 5, name: 'OBISPO TREJO')
City.create(province_id: 5, name: 'OJO DE AGUA')
City.create(province_id: 5, name: 'OJO DE AGUA')
City.create(province_id: 5, name: 'OLAEN')
City.create(province_id: 5, name: 'OLAETA')
City.create(province_id: 5, name: 'OLIVA')
City.create(province_id: 5, name: 'OLMOS')
City.create(province_id: 5, name: 'ONAGOITY')
City.create(province_id: 5, name: 'ONCATIVO')
City.create(province_id: 5, name: 'ONGAMIRA')
City.create(province_id: 5, name: 'ORDOÑEZ')
City.create(province_id: 5, name: 'ORO GRUESO')
City.create(province_id: 5, name: 'PACHANGO')
City.create(province_id: 5, name: 'PACHECO DE MELO')
City.create(province_id: 5, name: 'PAJAS BLANCAS')
City.create(province_id: 5, name: 'PAMPAYASTA NORTE')
City.create(province_id: 5, name: 'PAMPAYASTA SUR')
City.create(province_id: 5, name: 'PAN DE AZUCAR ,AP.KILOMETRO 592')
City.create(province_id: 5, name: 'PANAHOLMA')
City.create(province_id: 5, name: 'PASCANAS')
City.create(province_id: 5, name: 'PASCO')
City.create(province_id: 5, name: 'PASO DEL RIO SECO')
City.create(province_id: 5, name: 'PASO VIEJO')
City.create(province_id: 5, name: 'PAUNERO')
City.create(province_id: 5, name: 'PAVIN')
City.create(province_id: 5, name: 'PEGASANO')
City.create(province_id: 5, name: 'PELLICO, SILVIO')
City.create(province_id: 5, name: 'PETER, JAIME')
City.create(province_id: 5, name: 'PICHANAS')
City.create(province_id: 5, name: 'PIEDRA BLANCA')
City.create(province_id: 5, name: 'PIEDRAS ANCHAS')
City.create(province_id: 5, name: 'PIEDRAS BLANCAS')
City.create(province_id: 5, name: 'PIEDRITA BLANCA')
City.create(province_id: 5, name: 'PIEDRITAS ROSADAS')
City.create(province_id: 5, name: 'PILAR')
City.create(province_id: 5, name: 'PINAS')
City.create(province_id: 5, name: 'PINCEN')
City.create(province_id: 5, name: 'PINTOS')
City.create(province_id: 5, name: 'PIQUILLIN')
City.create(province_id: 5, name: 'PIZARRO, MODESTINO')
City.create(province_id: 5, name: 'PLAYA GRANDE')
City.create(province_id: 5, name: 'PLAZA BRUNO')
City.create(province_id: 5, name: 'PLAZA COLAZO')
City.create(province_id: 5, name: 'PLAZA DE MERCEDES')
City.create(province_id: 5, name: 'PLAZA DEHEZA')
City.create(province_id: 5, name: 'PLAZA LUXARDO')
City.create(province_id: 5, name: 'PLAZA SAN FRANCISCO')
City.create(province_id: 5, name: 'PLAZA VIDELA')
City.create(province_id: 5, name: 'POCHO')
City.create(province_id: 5, name: 'PORTEÑA')
City.create(province_id: 5, name: 'POSSE, JUSTINIANO')
City.create(province_id: 5, name: 'POZO DE LA LOMA')
City.create(province_id: 5, name: 'POZO DE LA PAMPA')
City.create(province_id: 5, name: 'POZO DE LAS OLLAS')
City.create(province_id: 5, name: 'POZO DEL CHAÑAR')
City.create(province_id: 5, name: 'POZO DEL MOLLE')
City.create(province_id: 5, name: 'POZO DEL MORO')
City.create(province_id: 5, name: 'POZO DEL TIGRE')
City.create(province_id: 5, name: 'PRETOT FREYRE')
City.create(province_id: 5, name: 'PUEBLO ITALIANO')
City.create(province_id: 5, name: 'PUEBLO VIEJO')
City.create(province_id: 5, name: 'PUERTA COLORADA')
City.create(province_id: 5, name: 'PUESTO DE AFUERA ,AP.')
City.create(province_id: 5, name: 'PUESTO DE CASTRO')
City.create(province_id: 5, name: 'PUESTO DEL ROSARIO')
City.create(province_id: 5, name: 'PUESTO PUCHETA')
City.create(province_id: 5, name: 'PUESTO SAN JOSE')
City.create(province_id: 5, name: 'PUNILLA ,AP.')
City.create(province_id: 5, name: 'PUNTA DEL AGUA')
City.create(province_id: 5, name: 'PUNTA DEL AGUA')
City.create(province_id: 5, name: 'PUNTA DEL AGUA')
City.create(province_id: 5, name: 'QUEBRACHO HERRADO')
City.create(province_id: 5, name: 'QUEBRADA DE LOS POZOS')
City.create(province_id: 5, name: 'QUILINO')
City.create(province_id: 5, name: 'QUISQUIZACATE ,AP.')
City.create(province_id: 5, name: 'RANGEL')
City.create(province_id: 5, name: 'RANQUELES')
City.create(province_id: 5, name: 'RARA FORTUNA')
City.create(province_id: 5, name: 'RAYO CORTADO')
City.create(province_id: 5, name: 'RINCON')
City.create(province_id: 5, name: 'RINCON DE LUNA')
City.create(province_id: 5, name: 'RIO BAMBA')
City.create(province_id: 5, name: 'RIO CEBALLOS')
City.create(province_id: 5, name: 'RIO CUARTO')
City.create(province_id: 5, name: 'RIO CUARTO NORTE ,AP.')
City.create(province_id: 5, name: 'RIO DE LOS MOLINOS ,PDA.')
City.create(province_id: 5, name: 'RIO DE LOS SAUCES')
City.create(province_id: 5, name: 'RIO HONDO')
City.create(province_id: 5, name: 'RIO PRIMERO')
City.create(province_id: 5, name: 'RIO SEGUNDO')
City.create(province_id: 5, name: 'RIO TERCERO')
City.create(province_id: 5, name: 'RIVERA INDARTE')
City.create(province_id: 5, name: 'ROCA, ALEJANDRO ,EST.ALEJANDRO')
City.create(province_id: 5, name: 'RODEO GRANDE')
City.create(province_id: 5, name: 'RODEO VIEJO')
City.create(province_id: 5, name: 'RODRIGUEZ DEL BUSTO')
City.create(province_id: 5, name: 'ROJAS, DIEGO DE')
City.create(province_id: 5, name: 'ROSALES')
City.create(province_id: 5, name: 'ROSALES, BLAS DE')
City.create(province_id: 5, name: 'RUIZ DIAZ DE GUZMAN')
City.create(province_id: 5, name: 'RUMIYACO')
