City.create(province_id: 11, name: 'ANDALUCAS')
City.create(province_id: 11, name: 'ANGUINAN')
City.create(province_id: 11, name: 'ANGULOS')
City.create(province_id: 11, name: 'ANILLACO')
City.create(province_id: 11, name: 'ANIMAN')
City.create(province_id: 11, name: 'ANJULLON')
City.create(province_id: 11, name: 'ANTINACO')
City.create(province_id: 11, name: 'ARAUCO')
City.create(province_id: 11, name: 'ATILES')
City.create(province_id: 11, name: 'BAJO DEL GALLO')
City.create(province_id: 11, name: 'BAJO GRANDE')
City.create(province_id: 11, name: 'BAJO HONDO')
City.create(province_id: 11, name: 'BANDA FLORIDA')
City.create(province_id: 11, name: 'BAZAN')
City.create(province_id: 11, name: 'BELLA VISTA')
City.create(province_id: 11, name: 'CABOLLAR')
City.create(province_id: 11, name: 'CAMPANAS')
City.create(province_id: 11, name: 'CARRIZAL')
City.create(province_id: 11, name: 'CARRIZAL')
City.create(province_id: 11, name: 'CARRIZAL')
City.create(province_id: 11, name: 'CASTRO BARROS')
City.create(province_id: 11, name: 'CATINZACO')
City.create(province_id: 11, name: 'CHAMICAL ,EST.GOBERNADOR GORDILLO')
City.create(province_id: 11, name: 'CHAÑAR')
City.create(province_id: 11, name: 'CHAÑARMUYO')
City.create(province_id: 11, name: 'CHELCOS')
City.create(province_id: 11, name: 'CHEPES')
City.create(province_id: 11, name: 'CHEPES VIEJO')
City.create(province_id: 11, name: 'CHILECITO')
City.create(province_id: 11, name: 'CHUQUIS')
City.create(province_id: 11, name: 'COCHANGASTA')
City.create(province_id: 11, name: 'COMANDANTE LEAL')
City.create(province_id: 11, name: 'CORRAL DE ISAAC')
City.create(province_id: 11, name: 'CORTADERAS')
City.create(province_id: 11, name: 'CUATRO ESQUINAS')
City.create(province_id: 11, name: 'EL ALTO')
City.create(province_id: 11, name: 'EL BARREAL')
City.create(province_id: 11, name: 'EL CALDEN')
City.create(province_id: 11, name: 'EL CHIFLON')
City.create(province_id: 11, name: 'EL CONDADO')
City.create(province_id: 11, name: 'EL MOLLAR')
City.create(province_id: 11, name: 'EL PORTEZUELO')
City.create(province_id: 11, name: 'EL POTRERILLO')
City.create(province_id: 11, name: 'EL QUEBRACHO')
City.create(province_id: 11, name: 'EL RODEO')
City.create(province_id: 11, name: 'EL SUNCHAL')
City.create(province_id: 11, name: 'EL TALA')
City.create(province_id: 11, name: 'EL VILGO')
City.create(province_id: 11, name: 'FAMATINA')
City.create(province_id: 11, name: 'GUANDACOL')
City.create(province_id: 11, name: 'ILISCA')
City.create(province_id: 11, name: 'JAGUE')
City.create(province_id: 11, name: 'KILOMETRO 875 ,DV.')
City.create(province_id: 11, name: 'KILOMETRO 891 ,AP.')
City.create(province_id: 11, name: 'LA AGUADITA')
City.create(province_id: 11, name: 'LA AGUADITA DE LOS BRIZUELA')
City.create(province_id: 11, name: 'LA BANDA')
City.create(province_id: 11, name: 'LA CALERA')
City.create(province_id: 11, name: 'LA CIENAGA')
City.create(province_id: 11, name: 'LA CIENAGA')
City.create(province_id: 11, name: 'LA FALDA DE CITAN')
City.create(province_id: 11, name: 'LA ISLA ,EST.')
City.create(province_id: 11, name: 'LA JARILLA')
City.create(province_id: 11, name: 'LA MERCED')
City.create(province_id: 11, name: 'LA PERSEGUIDA')
City.create(province_id: 11, name: 'LA PUERTA')
City.create(province_id: 11, name: 'LA REPRESA')
City.create(province_id: 11, name: 'LA RIOJA')
City.create(province_id: 11, name: 'LAS CLOACAS')
City.create(province_id: 11, name: 'LAS COLORADAS')
City.create(province_id: 11, name: 'LAS PADERCITAS')
City.create(province_id: 11, name: 'LAS TOSCAS')
City.create(province_id: 11, name: 'LOMA BLANCA')
City.create(province_id: 11, name: 'LOMA LARGA')
City.create(province_id: 11, name: 'LOS AGUIRRES')
City.create(province_id: 11, name: 'LOS ALANICES')
City.create(province_id: 11, name: 'LOS BALDES')
City.create(province_id: 11, name: 'LOS MOGOTES')
City.create(province_id: 11, name: 'LOS MOLINOS')
City.create(province_id: 11, name: 'LOS PALACIOS')
City.create(province_id: 11, name: 'LOS SARMIENTOS')
City.create(province_id: 11, name: 'LOS TAMBILLOS')
City.create(province_id: 11, name: 'MACHIGASTA')
City.create(province_id: 11, name: 'MAJADITA')
City.create(province_id: 11, name: 'MALANZAN')
City.create(province_id: 11, name: 'MALLIGASTA')
City.create(province_id: 11, name: 'MASCASIN')
City.create(province_id: 11, name: 'MAZAN ,EST.')
City.create(province_id: 11, name: 'MILAGRO')
City.create(province_id: 11, name: 'MINA LA MEJICANA')
City.create(province_id: 11, name: 'MIRANDA')
City.create(province_id: 11, name: 'MOLLACO')
City.create(province_id: 11, name: 'NACATE')
City.create(province_id: 11, name: 'NONOGASTA')
City.create(province_id: 11, name: 'ÑOQUEBE')
City.create(province_id: 11, name: 'OBRAJE DE TOSCANO')
City.create(province_id: 11, name: 'OLPAS')
City.create(province_id: 11, name: 'OLTA')
City.create(province_id: 11, name: 'PAGANCILLO')
City.create(province_id: 11, name: 'PAGANZO')
City.create(province_id: 11, name: 'PATQUIA')
City.create(province_id: 11, name: 'PINCHAS')
City.create(province_id: 11, name: 'PITUIL')
City.create(province_id: 11, name: 'PORTEZUELO DE ARCE')
City.create(province_id: 11, name: 'POZO DE AVILA')
City.create(province_id: 11, name: 'POZO DE PIEDRA')
City.create(province_id: 11, name: 'PUERTO ALEGRE')
City.create(province_id: 11, name: 'PUERTO ALEGRE')
City.create(province_id: 11, name: 'PUNTA DE LOS LLANOS')
City.create(province_id: 11, name: 'REAL DEL CADILLO ,DV.')
City.create(province_id: 11, name: 'RETAMAL')
City.create(province_id: 11, name: 'RIVADAVIA')
City.create(province_id: 11, name: 'SALADILLO')
City.create(province_id: 11, name: 'SAN ANTONIO')
City.create(province_id: 11, name: 'SAN ANTONIO')
City.create(province_id: 11, name: 'SAN BLAS')
City.create(province_id: 11, name: 'SAN ISIDRO')
City.create(province_id: 11, name: 'SAN JUAN')
City.create(province_id: 11, name: 'SAN PEDRO')
City.create(province_id: 11, name: 'SAN RAMON')
City.create(province_id: 11, name: 'SAN ROQUE')
City.create(province_id: 11, name: 'SAN SOLANO')
City.create(province_id: 11, name: 'SANOGASTA')
City.create(province_id: 11, name: 'SANTA CLARA')
City.create(province_id: 11, name: 'SANTA CRUZ')
City.create(province_id: 11, name: 'SANTA CRUZ ,DV.')
City.create(province_id: 11, name: 'SANTO DOMINGO')
City.create(province_id: 11, name: 'SCHAQUI')
City.create(province_id: 11, name: 'SIERRA BRAVA')
City.create(province_id: 11, name: 'SOLCA')
City.create(province_id: 11, name: 'TALAMUYUNA')
City.create(province_id: 11, name: 'TALVA')
City.create(province_id: 11, name: 'TAMA')
City.create(province_id: 11, name: 'TASQUIN')
City.create(province_id: 11, name: 'TELLO, DESIDERIO')
City.create(province_id: 11, name: 'TERMAS SANTA TERESITA')
City.create(province_id: 11, name: 'TOTORAL')
City.create(province_id: 11, name: 'TUIZON')
City.create(province_id: 11, name: 'ULAPES')
City.create(province_id: 11, name: 'VICHIGASTA')
City.create(province_id: 11, name: 'VILLA CASANA')
City.create(province_id: 11, name: 'VILLA CASTELLI')
City.create(province_id: 11, name: 'VILLA MAZAN')
City.create(province_id: 11, name: 'VILLA SANAGASTA')
City.create(province_id: 11, name: 'VILLA SANTA RITA')
City.create(province_id: 11, name: 'VILLA UNION')
City.create(province_id: 11, name: 'VINCHINA')
City.create(province_id: 12, name: '25 DE MAYO')
City.create(province_id: 12, name: 'AGRELO')
City.create(province_id: 12, name: 'AGUA ESCONDIDA')
City.create(province_id: 12, name: 'AGUA NUEVA ,EMB.CAÑADA AMARILLA')
City.create(province_id: 12, name: 'ALDEA LA PRIMAVERA')
City.create(province_id: 12, name: 'ALGARROBITO')
City.create(province_id: 12, name: 'ALTO VERDE')
City.create(province_id: 12, name: 'ALTOS DEL OLVIDO')
City.create(province_id: 12, name: 'ANCHORIS')
City.create(province_id: 12, name: 'ANCON')
City.create(province_id: 12, name: 'ANDRADE')
City.create(province_id: 12, name: 'ARISTIDES VILLANUEVA')
City.create(province_id: 12, name: 'ARROYITO')
City.create(province_id: 12, name: 'BAJO LUNLUNTA')
City.create(province_id: 12, name: 'BAÑOS LUNLUNTA')
City.create(province_id: 12, name: 'BARCALA')
City.create(province_id: 12, name: 'BARDAS BLANCAS')
City.create(province_id: 12, name: 'BARRANCAS')
City.create(province_id: 12, name: 'BARRAQUERO')
City.create(province_id: 12, name: 'BERMEJO')
City.create(province_id: 12, name: 'BOWEN')
City.create(province_id: 12, name: 'BUENA NUEVA')
City.create(province_id: 12, name: 'CACHEUTA')
City.create(province_id: 12, name: 'CADETES DE CHILE')
City.create(province_id: 12, name: 'CALMUCO')
City.create(province_id: 12, name: 'CAMPO LOS ANDES')
City.create(province_id: 12, name: 'CAMPOS, GASPAR')
City.create(province_id: 12, name: 'CAÑADA SECA')
City.create(province_id: 12, name: 'CANALEJAS')
City.create(province_id: 12, name: 'CAPACHO')
City.create(province_id: 12, name: 'CAPDEVILLE')
City.create(province_id: 12, name: 'CAPILLA DEL ROSARIO')
City.create(province_id: 12, name: 'CAPILLA DEL ROSARIO')
City.create(province_id: 12, name: 'CARMENSA')
City.create(province_id: 12, name: 'CHACRAS DE CORIA ,EST.PASO DE LOS ANDES')
City.create(province_id: 12, name: 'CHAPANAY')
City.create(province_id: 12, name: 'CHILECITO')
City.create(province_id: 12, name: 'COEHUE-CO')
City.create(province_id: 12, name: 'COLONIA 3 DE MAYO')
City.create(province_id: 12, name: 'COLONIA ALVEAR')
City.create(province_id: 12, name: 'COLONIA LAS ROSAS')
City.create(province_id: 12, name: 'COLONIA SUR')
City.create(province_id: 12, name: 'COMANDANTE SALAS')
City.create(province_id: 12, name: 'COQUIMBITO')
City.create(province_id: 12, name: 'CORRAL DE LORCA')
City.create(province_id: 12, name: 'CORRALITOS')
City.create(province_id: 12, name: 'COSTA DE ARAUJO')
City.create(province_id: 12, name: 'CRUZ DE PIEDRA')
City.create(province_id: 12, name: 'CUADRO NACIONAL')
City.create(province_id: 12, name: 'DESAGUADERO')
City.create(province_id: 12, name: 'EL ALGARROBO')
City.create(province_id: 12, name: 'EL ALPERO ,EMB.')
City.create(province_id: 12, name: 'EL BORBOLLON')
City.create(province_id: 12, name: 'EL CARRIZAL ABAJO')
City.create(province_id: 12, name: 'EL CARRIZAL DE ARRIBA')
City.create(province_id: 12, name: 'EL CENTRAL')
City.create(province_id: 12, name: 'EL CHALLAO')
City.create(province_id: 12, name: 'EL FORZADO')
City.create(province_id: 12, name: 'EL MANZANO')
City.create(province_id: 12, name: 'EL MIRADOR')
City.create(province_id: 12, name: 'EL NIHUIL')
City.create(province_id: 12, name: 'EL NIHUIL ,EST.')
City.create(province_id: 12, name: 'EL PARAISO')
City.create(province_id: 12, name: 'EL PASTAL')
City.create(province_id: 12, name: 'EL PLUMERILLO')
City.create(province_id: 12, name: 'EL RESGUARDO')
City.create(province_id: 12, name: 'EL RETAMO')
City.create(province_id: 12, name: 'EL SAUCE')
City.create(province_id: 12, name: 'EL SOSNEADO')
City.create(province_id: 12, name: 'EL VERGEL')
City.create(province_id: 12, name: 'ESPEJO')
City.create(province_id: 12, name: 'ESQUINA PESCADERO')
City.create(province_id: 12, name: 'ESTANCIA LA PAMPA')
City.create(province_id: 12, name: 'FRAY LUIS BELTRAN')
City.create(province_id: 12, name: 'GENERAL ALVEAR ,EST.COLONIA ALVEAR NORTE')
City.create(province_id: 12, name: 'GENERAL AMIGORENA ,EMB.')
City.create(province_id: 12, name: 'GENERAL GUTIERREZ')
City.create(province_id: 12, name: 'GENERAL LAVALLE')
City.create(province_id: 12, name: 'GENERAL ORTEGA')
City.create(province_id: 12, name: 'GERMANIA')
City.create(province_id: 12, name: 'GOBERNADOR BENEGAS')
City.create(province_id: 12, name: 'GOBERNADOR CIVIT')
City.create(province_id: 12, name: 'GODOY CRUZ')
City.create(province_id: 12, name: 'GOICO')
City.create(province_id: 12, name: 'GOUDGE')
City.create(province_id: 12, name: 'GUADALES')
City.create(province_id: 12, name: 'GUIDO')
City.create(province_id: 12, name: 'HORNITO DEL GRINGO')
City.create(province_id: 12, name: 'INGENIERO GIAGNONI')
City.create(province_id: 12, name: 'INGENIERO GUSTAVO ANDRE')
City.create(province_id: 12, name: 'ISELIN, RODOLFO')
City.create(province_id: 12, name: 'JOCOLI')
City.create(province_id: 12, name: 'JOCOLI VIEJO')
City.create(province_id: 12, name: 'JUNIN')
City.create(province_id: 12, name: 'JUSUS NAZARENO')
City.create(province_id: 12, name: 'KILOMETRO 976 ,EST.')
City.create(province_id: 12, name: 'LA ARBOLEDA')
City.create(province_id: 12, name: 'LA CARRODILLA')
City.create(province_id: 12, name: 'LA CAUTIVA')
City.create(province_id: 12, name: 'LA CIENAGUITA')
City.create(province_id: 12, name: 'LA CONSULTA')
City.create(province_id: 12, name: 'LA COSTA')
City.create(province_id: 12, name: 'LA DORMIDA')
City.create(province_id: 12, name: 'LA ESCANDINAVA')
City.create(province_id: 12, name: 'LA HOLANDA')
City.create(province_id: 12, name: 'LA HULLERA')
City.create(province_id: 12, name: 'LA MARZOLINA')
City.create(province_id: 12, name: 'LA MORA')
City.create(province_id: 12, name: 'LA PAZ')
City.create(province_id: 12, name: 'LA PEGA')
City.create(province_id: 12, name: 'LA UNION')
City.create(province_id: 12, name: 'LA VALENCIANA')
City.create(province_id: 12, name: 'LAGUNITA')
City.create(province_id: 12, name: 'LAS CATITAS ,EST.JOSE NESTOR LENCINAS')
City.create(province_id: 12, name: 'LAS CHACRAS')
City.create(province_id: 12, name: 'LAS CUEVAS')
City.create(province_id: 12, name: 'LAS HERAS ,EST.CABINA TAMARINDOS')
City.create(province_id: 12, name: 'LAS MALVINAS')
City.create(province_id: 12, name: 'LAS PAREDES ,EST.CAPITAN MONTOYA')
City.create(province_id: 12, name: 'LOA ALAMITOS')
City.create(province_id: 12, name: 'LOMAS BLANCAS')
City.create(province_id: 12, name: 'LOS ARBOLES')
City.create(province_id: 12, name: 'LOS ARBOLES')
City.create(province_id: 12, name: 'LOS HUARPES ,AP.')
City.create(province_id: 12, name: 'LOS MOLLES')
City.create(province_id: 12, name: 'LOS SAUCES')
City.create(province_id: 12, name: 'LOS TERNEROS ,DV.')
City.create(province_id: 12, name: 'LUJAN DE CUYO')
City.create(province_id: 12, name: 'LUNLUNTA')
City.create(province_id: 12, name: 'LUZURIAGA')
City.create(province_id: 12, name: 'MAIPU')
City.create(province_id: 12, name: 'MALARGUE')
City.create(province_id: 12, name: 'MAQUINISTA LEVET')
City.create(province_id: 12, name: 'MAYOR DRUMMOND')
City.create(province_id: 12, name: 'MEDIA LUNA')
City.create(province_id: 12, name: 'MEDRANO')
City.create(province_id: 12, name: 'MENDOZA')
City.create(province_id: 12, name: 'MINACAR')
City.create(province_id: 12, name: 'MINAS SALAGASTA')
City.create(province_id: 12, name: 'MONTE COMAN')
City.create(province_id: 12, name: 'MOYANO, FEDERICO J.')
City.create(province_id: 12, name: 'ÑACUNAN')
City.create(province_id: 12, name: 'NEGRO QUEMADO')
City.create(province_id: 12, name: 'NEWBERY, JORGE')
City.create(province_id: 12, name: 'ÑIRE-CO')
City.create(province_id: 12, name: 'NUEVA CALIFORNIA ,EST.MOLUCHES')
City.create(province_id: 12, name: 'OVEJERIA')
City.create(province_id: 12, name: 'PALMIRA')
City.create(province_id: 12, name: 'PAMPA DEL TIGRE')
City.create(province_id: 12, name: 'PAMPITA')
City.create(province_id: 12, name: 'PANQUEUA')
City.create(province_id: 12, name: 'PARAMILLO ,AP.')
City.create(province_id: 12, name: 'PAREDITAS')
City.create(province_id: 12, name: 'PEDREGAL')
City.create(province_id: 12, name: 'PERDRIEL')
City.create(province_id: 12, name: 'PHILIPPS')
City.create(province_id: 12, name: 'PICHI CIEGO')
City.create(province_id: 12, name: 'PIRQUITA')
City.create(province_id: 12, name: 'POLVAREDAS')
City.create(province_id: 12, name: 'POTRERILLOS')
City.create(province_id: 12, name: 'PRATS, JAIME')
City.create(province_id: 12, name: 'PUEBLO NUEVO (KM.ONCE)')
City.create(province_id: 12, name: 'PUENTE DEL INCA')
City.create(province_id: 12, name: 'PUNTA DE VACA')
City.create(province_id: 12, name: 'PUNTA DEL AGUA')
City.create(province_id: 12, name: 'PUNTILLA')
City.create(province_id: 12, name: 'RAMA CAIDA')
City.create(province_id: 12, name: 'RANQUIL DEL NORTE')
City.create(province_id: 12, name: 'REAL DEL PADRE')
City.create(province_id: 12, name: 'RESOLANA')
City.create(province_id: 12, name: 'RINCON DEL ATUEL ,EST.ING.BALLOFFET')
City.create(province_id: 12, name: 'RIVADAVIA')
City.create(province_id: 12, name: 'RODEO DE LA CRUZ')
City.create(province_id: 12, name: 'RODEO DEL MEDIO')
City.create(province_id: 12, name: 'RODRIGUEZ PEÑA')
City.create(province_id: 12, name: 'RUSSELL')
City.create(province_id: 12, name: 'SALINAS DEL DIAMANTE ,EST.')
City.create(province_id: 12, name: 'SALTO DE LAS ROSAS')
City.create(province_id: 12, name: 'SAN CARLOS')
City.create(province_id: 12, name: 'SAN JOSE')
City.create(province_id: 12, name: 'SAN JOSE')
City.create(province_id: 12, name: 'SAN MARTIN ,EST.LIB.GRL.SAN MARTIN')
City.create(province_id: 12, name: 'SAN MIGUEL')
City.create(province_id: 12, name: 'SAN RAFAEL')
City.create(province_id: 12, name: 'SAN ROQUE')
City.create(province_id: 12, name: 'SANTA MARIA DE ORO')
City.create(province_id: 12, name: 'SANTA ROSA')
City.create(province_id: 12, name: 'SOITUE')
City.create(province_id: 12, name: 'TERMAS VILLAVICENCIO')
City.create(province_id: 12, name: 'TRES ESQUINAS')
City.create(province_id: 12, name: 'TRES PORTEÑAS')
City.create(province_id: 12, name: 'TROPERO SOSA ,EMP.')
City.create(province_id: 12, name: 'TUNUYAN')
City.create(province_id: 12, name: 'TUPUNGATO')
City.create(province_id: 12, name: 'UGARTECHE')
City.create(province_id: 12, name: 'USPALLATA')
City.create(province_id: 12, name: 'USPALLATA ,EST.')
City.create(province_id: 12, name: 'VARGAS, PEDRO')
City.create(province_id: 12, name: 'VILLA ATUEL')
City.create(province_id: 12, name: 'VILLA BASTIA')
City.create(province_id: 12, name: 'VILLA EDELMIRA')
City.create(province_id: 12, name: 'VILLA HIPODROMO')
City.create(province_id: 12, name: 'VILLA LA PAZ')
City.create(province_id: 12, name: 'VILLA NUEVA')
City.create(province_id: 12, name: 'VILLA SECA')
City.create(province_id: 12, name: 'VILLANUEVA, ARISTIDES')
City.create(province_id: 12, name: 'VISTA FLORES')
City.create(province_id: 12, name: 'VISTALBA')
City.create(province_id: 12, name: 'ZAPATA')
City.create(province_id: 13, name: '25 DE MAYO')
City.create(province_id: 13, name: '25 DE MAYO')
City.create(province_id: 13, name: '9 DE JULIO')
City.create(province_id: 13, name: 'ALBA POSE')
City.create(province_id: 13, name: 'ALMAFUERTE')
City.create(province_id: 13, name: 'APOSTOLES')
City.create(province_id: 13, name: 'ARISTOBULO DEL VALLE')
City.create(province_id: 13, name: 'ARROYO DEL MEDIO')
City.create(province_id: 13, name: 'AZARA')
City.create(province_id: 13, name: 'BARRA BONITA')
City.create(province_id: 13, name: 'BARRA CONCEPCION')
City.create(province_id: 13, name: 'BARRANCON SAN PEDRO')
City.create(province_id: 13, name: 'BELLA VISTA')
City.create(province_id: 13, name: 'BERNARDO DE IRIGOYEN')
City.create(province_id: 13, name: 'BONPLAND')
City.create(province_id: 13, name: 'CAA YARI')
City.create(province_id: 13, name: 'CAMPANA')
City.create(province_id: 13, name: 'CAMPIÑAS DE AMERICA')
City.create(province_id: 13, name: 'CAMPO GRANDE')
City.create(province_id: 13, name: 'CAMPO RAMON')
City.create(province_id: 13, name: 'CAMPO VIERA')
City.create(province_id: 13, name: 'CANDELARIA')
City.create(province_id: 13, name: 'CAPIOVI')
City.create(province_id: 13, name: 'CAPIOVICINO')
City.create(province_id: 13, name: 'CATARATAS DEL IGUAZU')
City.create(province_id: 13, name: 'CERRO AZUL')
City.create(province_id: 13, name: 'CERRO CORA')
City.create(province_id: 13, name: 'COLONIA APOSTOLES')
City.create(province_id: 13, name: 'COLONIA ARISTOBULO DEL VALLE')
City.create(province_id: 13, name: 'COLONIA AURORA')
City.create(province_id: 13, name: 'COLONIA MBOPICUA')
City.create(province_id: 13, name: 'COLONIA NARANJITO')
City.create(province_id: 13, name: 'COLONIA SANTA TERESA')
City.create(province_id: 13, name: 'COLONIA YABEBIRY')
City.create(province_id: 13, name: 'CONCEPCION DE LA SIERRA')
City.create(province_id: 13, name: 'CORPUS')
City.create(province_id: 13, name: 'CUÑAPIRU')
City.create(province_id: 13, name: 'DEL VALLE, ARISTOBULO')
City.create(province_id: 13, name: 'DESEADO')
City.create(province_id: 13, name: 'DOS ARROYOS')
City.create(province_id: 13, name: 'DOS DE MAYO')
City.create(province_id: 13, name: 'EL ALCAZAR')
City.create(province_id: 13, name: 'EL PARAISO')
City.create(province_id: 13, name: 'EL SOBERBIO')
City.create(province_id: 13, name: 'EL TIGRE')
City.create(province_id: 13, name: 'ELDORADO')
City.create(province_id: 13, name: 'FACHINAL')
City.create(province_id: 13, name: 'FRACRAN')
City.create(province_id: 13, name: 'GARUPA')
City.create(province_id: 13, name: 'GENERAL ALVEAR')
City.create(province_id: 13, name: 'GENERAL GUEMES')
City.create(province_id: 13, name: 'GOBERNADOR JUAN J.LANUSSE')
City.create(province_id: 13, name: 'GOBERNADOR LOPEZ')
City.create(province_id: 13, name: 'GOBERNADOR ROCA')
City.create(province_id: 13, name: 'GUARANI')
City.create(province_id: 13, name: 'INVERNADA DE ITACARUARE')
City.create(province_id: 13, name: 'IRIGOYEN, BERNARDO DE')
City.create(province_id: 13, name: 'ITACARUARE')
City.create(province_id: 13, name: 'JARDIN AMERICA')
City.create(province_id: 13, name: 'KILOMETRO 18')
City.create(province_id: 13, name: 'KILOMETRO 538 ,AP.')
City.create(province_id: 13, name: 'KILOMETRO 546 ,AP.')
City.create(province_id: 13, name: 'KILOMETRO 577')
City.create(province_id: 13, name: 'LA GRUTA')
City.create(province_id: 13, name: 'LAHARRAGE')
City.create(province_id: 13, name: 'LANUS, MIGUEL')
City.create(province_id: 13, name: 'LAS TUNAS')
City.create(province_id: 13, name: 'LEIS ,PDA.')
City.create(province_id: 13, name: 'LORETO')
City.create(province_id: 13, name: 'LOS HELECHOS')
City.create(province_id: 13, name: 'MACHADINO')
City.create(province_id: 13, name: 'MARTIRES')
City.create(province_id: 13, name: 'MOJON GRANDE')
City.create(province_id: 13, name: 'MONTEAGUDO')
City.create(province_id: 13, name: 'MONTECARLO')
City.create(province_id: 13, name: 'ÑACANGUAZU')
City.create(province_id: 13, name: 'OBERA')
City.create(province_id: 13, name: 'PANAMBI')
City.create(province_id: 13, name: 'PIÑALITO')
City.create(province_id: 13, name: 'PINDAPOY ,EST.')
City.create(province_id: 13, name: 'POSADAS')
City.create(province_id: 13, name: 'PROFUNDIDAD')
City.create(province_id: 13, name: 'PUEBLO TARUMA')
City.create(province_id: 13, name: 'PUERTO 3 DE MAYO')
City.create(province_id: 13, name: 'PUERTO AVELLANEDA')
City.create(province_id: 13, name: 'PUERTO BOSSETTI')
City.create(province_id: 13, name: 'PUERTO CARAGUATAY')
City.create(province_id: 13, name: 'PUERTO CONCEPCION')
City.create(province_id: 13, name: 'PUERTO DELICIA')
City.create(province_id: 13, name: 'PUERTO ELDORADO')
City.create(province_id: 13, name: 'PUERTO ELVECIA')
City.create(province_id: 13, name: 'PUERTO ERRECABORDE')
City.create(province_id: 13, name: 'PUERTO ESPAÑA')
City.create(province_id: 13, name: 'PUERTO ESPERANZA')
City.create(province_id: 13, name: 'PUERTO GARUHAPE')
City.create(province_id: 13, name: 'PUERTO GISELA')
City.create(province_id: 13, name: 'PUERTO IGUAZU')
City.create(province_id: 13, name: 'PUERTO INGENIERO MORANDI')
City.create(province_id: 13, name: 'PUERTO LEONI')
City.create(province_id: 13, name: 'PUERTO LIBERTAD')
City.create(province_id: 13, name: 'PUERTO LONDERO')
City.create(province_id: 13, name: 'PUERTO MADO')
City.create(province_id: 13, name: 'PUERTO MENOCCHIO')
City.create(province_id: 13, name: 'PUERTO NARANJITO')
City.create(province_id: 13, name: 'PUERTO OASIS')
City.create(province_id: 13, name: 'PUERTO ORO VERDE')
City.create(province_id: 13, name: 'PUERTO PARAISO')
City.create(province_id: 13, name: 'PUERTO PARANAY')
City.create(province_id: 13, name: 'PUERTO PAULITO')
City.create(province_id: 13, name: 'PUERTO PENINSULA')
City.create(province_id: 13, name: 'PUERTO PINARES')
City.create(province_id: 13, name: 'PUERTO PIRAY')
City.create(province_id: 13, name: 'PUERTO RICO')
City.create(province_id: 13, name: 'PUERTO ROSARIO')
City.create(province_id: 13, name: 'PUERTO SAN ANTONIO')
City.create(province_id: 13, name: 'PUERTO SAN ISIDRO')
City.create(province_id: 13, name: 'PUERTO SAN LUCAS')
City.create(province_id: 13, name: 'PUERTO SAN MARTIN')
City.create(province_id: 13, name: 'PUERTO SEGUNDO')
City.create(province_id: 13, name: 'PUERTO VICTORIA')
City.create(province_id: 13, name: 'PUERTO YRIGOYEN')
City.create(province_id: 13, name: 'PURTO MINERAL')
City.create(province_id: 13, name: 'RUIZ DE MONTOYA')
City.create(province_id: 13, name: 'SALTO')
City.create(province_id: 13, name: 'SAN ANTONIO')
City.create(province_id: 13, name: 'SAN FRANCISCO DE ASIS')
City.create(province_id: 13, name: 'SAN IGNACIO')
City.create(province_id: 13, name: 'SAN JAVIER')
City.create(province_id: 13, name: 'SAN JOSE')
City.create(province_id: 13, name: 'SAN PEDRO')
City.create(province_id: 13, name: 'SAN VICENTE')
City.create(province_id: 13, name: 'SANTA ANA')
City.create(province_id: 13, name: 'SANTA MARIA')
City.create(province_id: 13, name: 'SANTA RITA')
City.create(province_id: 13, name: 'SANTA RITA')
City.create(province_id: 13, name: 'SANTO PIPO')
City.create(province_id: 13, name: 'TACUARUZU')
City.create(province_id: 13, name: 'TOBUNA')
City.create(province_id: 13, name: 'TRES CAPONES')
City.create(province_id: 13, name: 'VILLA LONCA')
City.create(province_id: 13, name: 'WANDA')
City.create(province_id: 13, name: 'YRIGOYEN, HIPOLITO')
City.create(province_id: 14, name: 'ACHICO')
City.create(province_id: 14, name: 'ALUMINE')
City.create(province_id: 14, name: 'ANDACOLLO')
City.create(province_id: 14, name: 'AÑELO')
City.create(province_id: 14, name: 'ARROYITO CHALLACO')
City.create(province_id: 14, name: 'ARROYO BLANCO')
City.create(province_id: 14, name: 'ASTRA')
City.create(province_id: 14, name: 'AUCA MAHUIDA')
City.create(province_id: 14, name: 'BAJADA COLORADA')
City.create(province_id: 14, name: 'BAJADA DEL AGRIO')
City.create(province_id: 14, name: 'BAÑOS LAS MAQUINITAS')
City.create(province_id: 14, name: 'BARRANCAS')
City.create(province_id: 14, name: 'BELLA VISTA')
City.create(province_id: 14, name: 'BOTE')
City.create(province_id: 14, name: 'BUTA MALLIN')
City.create(province_id: 14, name: 'BUTA RANQUIL')
City.create(province_id: 14, name: 'BUTACO')
City.create(province_id: 14, name: 'CAJON DE ALMANZA')
City.create(province_id: 14, name: 'CAJON DEL MANZANO')
City.create(province_id: 14, name: 'CALIFORNIA')
City.create(province_id: 14, name: 'CAMPANA MAHUIDA')
City.create(province_id: 14, name: 'CAMPO GRANDE')
City.create(province_id: 14, name: 'CASTRO, RAMON M.')
City.create(province_id: 14, name: 'CATAN LIL')
City.create(province_id: 14, name: 'CENTENARIO')
City.create(province_id: 14, name: 'CHACAICO SUR')
City.create(province_id: 14, name: 'CHALLACO')
City.create(province_id: 14, name: 'CHOS MALAL')
City.create(province_id: 14, name: 'CODIHUE')
City.create(province_id: 14, name: 'COIHUECO')
City.create(province_id: 14, name: 'COLIPILLI')
City.create(province_id: 14, name: 'COLLON CURA')
City.create(province_id: 14, name: 'COLLON-CO')
City.create(province_id: 14, name: 'COPAHUE')
City.create(province_id: 14, name: 'CORRENTOSO')
City.create(province_id: 14, name: 'CORTADERA')
City.create(province_id: 14, name: 'COVUNCO')
City.create(province_id: 14, name: 'CUTRAL-CO')
City.create(province_id: 14, name: 'EL CHOLAR')
City.create(province_id: 14, name: 'EL HUECU')
City.create(province_id: 14, name: 'EL MARUCHO')
City.create(province_id: 14, name: 'ESPINAZO DEL ZORRO')
City.create(province_id: 14, name: 'FORTIN 1Âº DE MAYO')
City.create(province_id: 14, name: 'HUINGANCO')
City.create(province_id: 14, name: 'JUNIN DE LOS ANDES')
City.create(province_id: 14, name: 'LA BUITRERA')
City.create(province_id: 14, name: 'LA LIPELA')
City.create(province_id: 14, name: 'LA NEGRA')
City.create(province_id: 14, name: 'LA PICAZA')
City.create(province_id: 14, name: 'LAS COLORADAS')
City.create(province_id: 14, name: 'LAS LAJAS')
City.create(province_id: 14, name: 'LAS OVEJAS')
City.create(province_id: 14, name: 'LILEO')
City.create(province_id: 14, name: 'LONCOPUE')
City.create(province_id: 14, name: 'LOS HELECHOS')
City.create(province_id: 14, name: 'LOS MOLLES')
City.create(province_id: 14, name: 'MALLEO')
City.create(province_id: 14, name: 'MORENO, MARIANO')
City.create(province_id: 14, name: 'MULICHINCO')
City.create(province_id: 14, name: 'NAHUEL HUAPI')
City.create(province_id: 14, name: 'NAUNAUCO')
City.create(province_id: 14, name: 'NEUQUEN')
City.create(province_id: 14, name: 'ÑORQUIN')
City.create(province_id: 14, name: 'PASO DE LOS INDIOS')
City.create(province_id: 14, name: 'PICUN LEUFU')
City.create(province_id: 14, name: 'PIEDRA DEL AGUILA')
City.create(province_id: 14, name: 'PILOLIL')
City.create(province_id: 14, name: 'PINO HACHADO')
City.create(province_id: 14, name: 'PLAZA HUINCUL')
City.create(province_id: 14, name: 'PLOTTIER')
City.create(province_id: 14, name: 'PUERTO HUA-HUM')
City.create(province_id: 14, name: 'PUERTO HUEMUL')
City.create(province_id: 14, name: 'PUERTO MANZANO')
City.create(province_id: 14, name: 'QUILACHANQUIL')
City.create(province_id: 14, name: 'QUILI MALAL')
City.create(province_id: 14, name: 'RAHUE')
City.create(province_id: 14, name: 'RANQUILCO')
City.create(province_id: 14, name: 'SAN IGNACIO')
City.create(province_id: 14, name: 'SAN MARTIN DE LOS ANDES')
City.create(province_id: 14, name: 'SANICO')
City.create(province_id: 14, name: 'SENILLOSA')
City.create(province_id: 14, name: 'TRAFUL')
City.create(province_id: 14, name: 'TRES CHORROS')
City.create(province_id: 14, name: 'TRICAO MALAL')
City.create(province_id: 14, name: 'VARVARCI')
City.create(province_id: 14, name: 'VILLA EL CHOCON')
City.create(province_id: 14, name: 'VILLA LA ANGOSTURA')
City.create(province_id: 14, name: 'VILLA TRAFUL')
City.create(province_id: 14, name: 'VISTA ALEGRE')
City.create(province_id: 14, name: 'ZAPALA')
City.create(province_id: 15, name: 'AGUADA CECILIO')
City.create(province_id: 15, name: 'AGUADA DE GUERRA')
City.create(province_id: 15, name: 'AGUADA DE GUZMAN')
City.create(province_id: 15, name: 'AGUADA TRONCOSO')
City.create(province_id: 15, name: 'ALLEN')
City.create(province_id: 15, name: 'ARROYO DE LA VENTANA')
City.create(province_id: 15, name: 'ARROYO VERDE')
City.create(province_id: 15, name: 'BARDA DEL MEDIO ,EST.KM 1218')
City.create(province_id: 15, name: 'BENJAMIN ZORRILLA')
City.create(province_id: 15, name: 'BOCA DE LA TRAVESIA')
City.create(province_id: 15, name: 'BUENA PARADA')
City.create(province_id: 15, name: 'CATRIEL')
City.create(province_id: 15, name: 'CERRO ABANICO ,AP.')
City.create(province_id: 15, name: 'CERRO POLICIA')
City.create(province_id: 15, name: 'CERVANTES')
City.create(province_id: 15, name: 'CHACAY HUARRUCA')
City.create(province_id: 15, name: 'CHASICO')
City.create(province_id: 15, name: 'CHELFORO')
City.create(province_id: 15, name: 'CHICHINALES')
City.create(province_id: 15, name: 'CHIMPAY')
City.create(province_id: 15, name: 'CHOELE CHOEL')
City.create(province_id: 15, name: 'CINCO CHAÑARES')
City.create(province_id: 15, name: 'CINCO SALTOS')
City.create(province_id: 15, name: 'CIPOLLETTI')
City.create(province_id: 15, name: 'COLONIA JOSEFA')
City.create(province_id: 15, name: 'COLONIA JULIA Y ECHARREN')
City.create(province_id: 15, name: 'COMALLO')
City.create(province_id: 15, name: 'CONA NIYEU')
City.create(province_id: 15, name: 'CONTRALMIRANTE CORDERO')
City.create(province_id: 15, name: 'CONTRALMIRANTE MARTIN GUERRICO')
City.create(province_id: 15, name: 'CORONEL BELISLE')
City.create(province_id: 15, name: 'CORONEL EUGENIO DEL BUSTO')
City.create(province_id: 15, name: 'CORONEL FRANCISCO SOSA')
City.create(province_id: 15, name: 'CORONEL JUAN JOSE GOMEZ')
City.create(province_id: 15, name: 'CUBANEA')
City.create(province_id: 15, name: 'DARWIN')
City.create(province_id: 15, name: 'DOCTOR ROGELIO CORTIZO ,EMP.')
City.create(province_id: 15, name: 'EL BOLSON')
City.create(province_id: 15, name: 'EL CAIN')
City.create(province_id: 15, name: 'EL CUY')
City.create(province_id: 15, name: 'EL PORVENIR ,EMB.')
City.create(province_id: 15, name: 'FALKNER')
City.create(province_id: 15, name: 'FITALANCAO')
City.create(province_id: 15, name: 'FORTIN UNO')
City.create(province_id: 15, name: 'FRAY LUIS BELTRAN')
City.create(province_id: 15, name: 'FUTA RUIN')
City.create(province_id: 15, name: 'GANZU LAUQUEN ,AP.')
City.create(province_id: 15, name: 'GARAY, JUAN DE')
City.create(province_id: 15, name: 'GENERAL CONESA')
City.create(province_id: 15, name: 'GENERAL ENRIQUE GODOY')
City.create(province_id: 15, name: 'GENERAL FERNANDEZ ORO')
City.create(province_id: 15, name: 'GENERAL LIBORIO BERNAL')
City.create(province_id: 15, name: 'GENERAL LORENZO VINTTER')
City.create(province_id: 15, name: 'GENERAL NICOLAS H.PALACIOS')
City.create(province_id: 15, name: 'GENERAL ROCA')
City.create(province_id: 15, name: 'GUARDIA MITRE')
City.create(province_id: 15, name: 'INGENIERO JACOBACCI')
City.create(province_id: 15, name: 'INGENIERO JULIAN ROMERO ,EST')
City.create(province_id: 15, name: 'INGENIERO LUIS A.HUERGO')
City.create(province_id: 15, name: 'INGENIERO OTTO KRAUSE')
City.create(province_id: 15, name: 'INGENIERO ZIMMERMANN RESTA ,AP.')
City.create(province_id: 15, name: 'KILOMETRO 1013')
City.create(province_id: 15, name: 'KILOMETRO 1040')
City.create(province_id: 15, name: 'KILOMETRO 1071')
City.create(province_id: 15, name: 'KILOMETRO 21')
City.create(province_id: 15, name: 'KILOMETRO 38')
City.create(province_id: 15, name: 'KILOMETRO 39')
City.create(province_id: 15, name: 'KILOMETRO 57')
City.create(province_id: 15, name: 'KILOMETRO 648')
City.create(province_id: 15, name: 'KILOMETRO 829')
City.create(province_id: 15, name: 'KILOMETRO 839')
City.create(province_id: 15, name: 'KILOMETRO 867')
City.create(province_id: 15, name: 'KILOMETRO 875')
City.create(province_id: 15, name: 'KILOMETRO 899')
City.create(province_id: 15, name: 'KILOMETRO 966')
City.create(province_id: 15, name: 'KILOMETRO 995')
City.create(province_id: 15, name: 'LA ENSENADA')
City.create(province_id: 15, name: 'LA ESPERANZA')
City.create(province_id: 15, name: 'LA LOBERIA')
City.create(province_id: 15, name: 'LAGUNA BLANCA')
City.create(province_id: 15, name: 'LAMARQUE')
City.create(province_id: 15, name: 'LAS BAYAS')
City.create(province_id: 15, name: 'LLAO LLAO')
City.create(province_id: 15, name: 'LONCO VACA')
City.create(province_id: 15, name: 'LOS JUNCOS')
City.create(province_id: 15, name: 'LOS MENUCOS')
City.create(province_id: 15, name: 'LOS REPOLLOS')
City.create(province_id: 15, name: 'MAINQUE')
City.create(province_id: 15, name: 'MAMUEL CHOIQUE')
City.create(province_id: 15, name: 'MANCHA BLANCA ,EST.')
City.create(province_id: 15, name: 'MAQUINCHAO')
City.create(province_id: 15, name: 'MENCUE')
City.create(province_id: 15, name: 'MENUCOS')
City.create(province_id: 15, name: 'MINISTRO RAMOS MEXIA')
City.create(province_id: 15, name: 'MUSTERS ,EST.')
City.create(province_id: 15, name: 'NAHUEL NIYEU')
City.create(province_id: 15, name: 'NEGRO MUERTO')
City.create(province_id: 15, name: 'NENEO RUCA')
City.create(province_id: 15, name: 'ÑIRIHUAU')
City.create(province_id: 15, name: 'ÑORQUINCO')
City.create(province_id: 15, name: 'NUEVO LEON')
City.create(province_id: 15, name: 'OJOS DE AGUA')
City.create(province_id: 15, name: 'ONELLI, CLEMENTE')
City.create(province_id: 15, name: 'PADRE ALEJANDRO STEFENELLI')
City.create(province_id: 15, name: 'PAJALTA')
City.create(province_id: 15, name: 'PASO CHACABUCO')
City.create(province_id: 15, name: 'PASO FLORES')
City.create(province_id: 15, name: 'PASO LIMAY')
City.create(province_id: 15, name: 'PERITO MORENO')
City.create(province_id: 15, name: 'PERITO MORENO ,EST.')
City.create(province_id: 15, name: 'PICHI LEUFU')
City.create(province_id: 15, name: 'PICHI MAHUIDA')
City.create(province_id: 15, name: 'PILCANIYEU')
City.create(province_id: 15, name: 'POMONA')
City.create(province_id: 15, name: 'PUERTO BLEST')
City.create(province_id: 15, name: 'RIO CHICO ,EST.CERRO MESA')
City.create(province_id: 15, name: 'RIO COLORADO')
City.create(province_id: 15, name: 'RIO COLORADO')
City.create(province_id: 15, name: 'SAN ANTONIO OESTE')
City.create(province_id: 15, name: 'SAN CARLOS DE BARILOCHE')
City.create(province_id: 15, name: 'SAN LORENZO')
City.create(province_id: 15, name: 'SANTA ROSA')
City.create(province_id: 15, name: 'SCOTT, PERCY H. ,AP.')
City.create(province_id: 15, name: 'SIERRA COLORADA')
City.create(province_id: 15, name: 'SIERRA GRANDE')
City.create(province_id: 15, name: 'SIERRA PAILEMAN')
City.create(province_id: 15, name: 'TALCAHUALA ,AP.')
City.create(province_id: 15, name: 'TENIENTE MAZA ,EST.')
City.create(province_id: 15, name: 'TRAPALCO')
City.create(province_id: 15, name: 'TRICA CO')
City.create(province_id: 15, name: 'VALCHETA')
City.create(province_id: 15, name: 'VICEALMIRANTE EDUARDO O\'CONNOR')
City.create(province_id: 15, name: 'VIEDMA')
City.create(province_id: 15, name: 'VIEDMA ,EST.')
City.create(province_id: 15, name: 'VILLA MASCARDI')
City.create(province_id: 15, name: 'VILLA REGINA')
City.create(province_id: 15, name: 'ZANJON DE OYUELA')
City.create(province_id: 15, name: 'ZORRILLA, BENJAMIN')
City.create(province_id: 16, name: '20 DE FEBRERO')
City.create(province_id: 16, name: 'ACAMBUCO')
City.create(province_id: 16, name: 'AGUA BLANCA')
City.create(province_id: 16, name: 'AGUA SUCIA')
City.create(province_id: 16, name: 'AGUARAY ,EST.')
City.create(province_id: 16, name: 'ALEMANIA')
City.create(province_id: 16, name: 'ALGARROBAL')
City.create(province_id: 16, name: 'ALMIRANTE BROWN')
City.create(province_id: 16, name: 'ALTO DE FLORES')
City.create(province_id: 16, name: 'ALTO DEL MISTOL')
City.create(province_id: 16, name: 'AMBLAYO')
City.create(province_id: 16, name: 'AMPASCACHI')
City.create(province_id: 16, name: 'ANGASTACO')
City.create(province_id: 16, name: 'ANGOSTURA')
City.create(province_id: 16, name: 'ANIMANA')
City.create(province_id: 16, name: 'ANTA')
City.create(province_id: 16, name: 'ANTILLA')
City.create(province_id: 16, name: 'ANTONIO QUIJARRO')
City.create(province_id: 16, name: 'APOLINARIO SARAVIA')
City.create(province_id: 16, name: 'ARENAL')
City.create(province_id: 16, name: 'BAJO GRANDE')
City.create(province_id: 16, name: 'BALBOA')
City.create(province_id: 16, name: 'BELLA VISTA')
City.create(province_id: 16, name: 'BETANIA')
City.create(province_id: 16, name: 'CABEZA DE BUEY')
City.create(province_id: 16, name: 'CACHI')
City.create(province_id: 16, name: 'CACHIÑAL')
City.create(province_id: 16, name: 'CACHIPAMPA')
City.create(province_id: 16, name: 'CAFAYATE')
City.create(province_id: 16, name: 'CAIPE ,EST.')
City.create(province_id: 16, name: 'CAMPICHUELO')
City.create(province_id: 16, name: 'CAMPO ALEGRE')
City.create(province_id: 16, name: 'CAMPO CASEROS')
City.create(province_id: 16, name: 'CAMPO DURAN')
City.create(province_id: 16, name: 'CAMPO GRANDE')
City.create(province_id: 16, name: 'CAMPO QUIJANO')
City.create(province_id: 16, name: 'CAMPO SANTO')
City.create(province_id: 16, name: 'CAPITAN JUAN PAGE')
City.create(province_id: 16, name: 'CASTAÑARES ,EST.')
City.create(province_id: 16, name: 'CEIBALITO')
City.create(province_id: 16, name: 'CERRILLOS')
City.create(province_id: 16, name: 'CHAGUARAL')
City.create(province_id: 16, name: 'CHAÑAR MUYO ,EST.CNL.OLLEROS')
City.create(province_id: 16, name: 'CHICOANA')
City.create(province_id: 16, name: 'CHICOANA ,EST.')
City.create(province_id: 16, name: 'CHORRILLOS')
City.create(province_id: 16, name: 'CHORROARIN')
City.create(province_id: 16, name: 'CHUCULAQUI ,EST.')
City.create(province_id: 16, name: 'COBRES')
City.create(province_id: 16, name: 'COCHABAMBA ,AP.')
City.create(province_id: 16, name: 'COLONIA SANTA ROSA')
City.create(province_id: 16, name: 'COPO QUILE')
City.create(province_id: 16, name: 'CORONEL CORNEJO')
City.create(province_id: 16, name: 'CORONEL JUAN SOLA ,EST.MORILLO')
City.create(province_id: 16, name: 'CORONEL MOLDES')
City.create(province_id: 16, name: 'CORONEL MOLLINEDO')
City.create(province_id: 16, name: 'CORONEL VIDT')
City.create(province_id: 16, name: 'CORRALITO')
City.create(province_id: 16, name: 'CORRALITO')
City.create(province_id: 16, name: 'CRUZ QUEMADA')
City.create(province_id: 16, name: 'DE ALMAGRO, DIEGO')
City.create(province_id: 16, name: 'DOCTOR FACUNDO ZUVIRIA')
City.create(province_id: 16, name: 'DRAGONES')
City.create(province_id: 16, name: 'EL AIBAL')
City.create(province_id: 16, name: 'EL ALISAL')
City.create(province_id: 16, name: 'EL BORDO')
City.create(province_id: 16, name: 'EL BORDO')
City.create(province_id: 16, name: 'EL BOTIN')
City.create(province_id: 16, name: 'EL CARRIL')
City.create(province_id: 16, name: 'EL CEBILLAR')
City.create(province_id: 16, name: 'EL CEIBALITO')
City.create(province_id: 16, name: 'EL DURAZNO')
City.create(province_id: 16, name: 'EL ENCON')
City.create(province_id: 16, name: 'EL GALPON ,EST.FOGUISTA JORGE.F.SUAREZ')
City.create(province_id: 16, name: 'EL NARANJO')
City.create(province_id: 16, name: 'EL PAJEAL')
City.create(province_id: 16, name: 'EL PIQUETE')
City.create(province_id: 16, name: 'EL PUCARA')
City.create(province_id: 16, name: 'EL QUEBRACHAL')
City.create(province_id: 16, name: 'EL SALADILLO')
City.create(province_id: 16, name: 'EL TALA ,EST.RUIZ DE LOS LLANOS')
City.create(province_id: 16, name: 'EL TUNAL')
City.create(province_id: 16, name: 'EL TUNAL')
City.create(province_id: 16, name: 'EMBARCACION')
City.create(province_id: 16, name: 'ESCOIPE')
City.create(province_id: 16, name: 'ESQUINA DE QUISTO')
City.create(province_id: 16, name: 'ESTECO')
City.create(province_id: 16, name: 'GAONA')
City.create(province_id: 16, name: 'GENERAL ALVARADO')
City.create(province_id: 16, name: 'GENERAL BALLIVIAN')
City.create(province_id: 16, name: 'GENERAL GUEMES ,EST.GUEMES')
City.create(province_id: 16, name: 'GENERAL MOSCONI ,EST.VESPUCIO')
City.create(province_id: 16, name: 'GENERAL PIZARRO')
City.create(province_id: 16, name: 'GOBERNADOR MANUEL SOLA')
City.create(province_id: 16, name: 'GONZALEZ, Â°JOAQUIN V.')
City.create(province_id: 16, name: 'GUACHIPAS')
City.create(province_id: 16, name: 'GUAYACAN')
City.create(province_id: 16, name: 'HICKMANN')
City.create(province_id: 16, name: 'HORCONES')
City.create(province_id: 16, name: 'INCAHUASI')
City.create(province_id: 16, name: 'INGENIERO MAURY')
City.create(province_id: 16, name: 'IRUYA')
City.create(province_id: 16, name: 'JASIMANA')
City.create(province_id: 16, name: 'JURAMENTO')
City.create(province_id: 16, name: 'KILOMETRO 1088 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1104 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1125 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1129 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1152 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1156 ,AP.')
City.create(province_id: 16, name: 'KILOMETRO 1291')
City.create(province_id: 16, name: 'KILOMETRO 1291 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1299')
City.create(province_id: 16, name: 'KILOMETRO 1305 ,DV.')
City.create(province_id: 16, name: 'KILOMETRO 1357')
City.create(province_id: 16, name: 'KILOMETRO 1424')
City.create(province_id: 16, name: 'KILOMETRO 1448')
City.create(province_id: 16, name: 'KILOMETRO 1506')
City.create(province_id: 16, name: 'LA CALDERA')
City.create(province_id: 16, name: 'LA CANDELARIA')
City.create(province_id: 16, name: 'LA CANDELARIA')
City.create(province_id: 16, name: 'LA CORZUELA')
City.create(province_id: 16, name: 'LA ESTRELLA')
City.create(province_id: 16, name: 'LA FLORIDA')
City.create(province_id: 16, name: 'LA ISLA')
City.create(province_id: 16, name: 'LA MERCED')
City.create(province_id: 16, name: 'LA POMA')
City.create(province_id: 16, name: 'LA QUESERA')
City.create(province_id: 16, name: 'LA ROSITA')
City.create(province_id: 16, name: 'LA SILLETA')
City.create(province_id: 16, name: 'LA TRAMPA')
City.create(province_id: 16, name: 'LA UNION')
City.create(province_id: 16, name: 'LA VIÑA')
City.create(province_id: 16, name: 'LAS CAPILLAS')
City.create(province_id: 16, name: 'LAS LAJITAS')
City.create(province_id: 16, name: 'LAS LLAVES')
City.create(province_id: 16, name: 'LAS MERCEDES')
City.create(province_id: 16, name: 'LAS MESITAS ,DV.')
City.create(province_id: 16, name: 'LAS PALMAS')
City.create(province_id: 16, name: 'LAS SALADAS')
City.create(province_id: 16, name: 'LAS TORTUGAS')
City.create(province_id: 16, name: 'LAS TRES MARIAS')
City.create(province_id: 16, name: 'LAS VIBORAS')
City.create(province_id: 16, name: 'LORO HUASI')
City.create(province_id: 16, name: 'LOS BAÑOS')
City.create(province_id: 16, name: 'LOS BLANCOS')
City.create(province_id: 16, name: 'LOS MOGOTES')
City.create(province_id: 16, name: 'LOS NOGALES')
City.create(province_id: 16, name: 'LOS PATOS ,AP.')
City.create(province_id: 16, name: 'LOS SAUCES')
City.create(province_id: 16, name: 'LUMBRERA')
City.create(province_id: 16, name: 'LURACATAO')
City.create(province_id: 16, name: 'MACAPILLO')
City.create(province_id: 16, name: 'MARTINEZ DEL TINEO')
City.create(province_id: 16, name: 'MATORRAS, JERONIMO')
City.create(province_id: 16, name: 'MESETA')
City.create(province_id: 16, name: 'METAN')
City.create(province_id: 16, name: 'METAN VIEJO')
City.create(province_id: 16, name: 'MINA CONCORDIA ,EMB.')
City.create(province_id: 16, name: 'MINA LA CASUALIDAD')
City.create(province_id: 16, name: 'MOJOTORO')
City.create(province_id: 16, name: 'MOLINOS')
City.create(province_id: 16, name: 'MONTEVERDE')
City.create(province_id: 16, name: 'MORALES')
City.create(province_id: 16, name: 'MORENILLO')
City.create(province_id: 16, name: 'MUÑANO')
City.create(province_id: 16, name: 'NAZARENO')
City.create(province_id: 16, name: 'NUESTRA SEÑORA DE TALAVERA')
City.create(province_id: 16, name: 'OSMA')
City.create(province_id: 16, name: 'OSMA ,EST.')
City.create(province_id: 16, name: 'OVANDO')
City.create(province_id: 16, name: 'PADRE LOZANO')
City.create(province_id: 16, name: 'PALERMO')
City.create(province_id: 16, name: 'PALOMITAS')
City.create(province_id: 16, name: 'PAMPA GRANDE')
City.create(province_id: 16, name: 'PATRON COSTAS, LUIS')
City.create(province_id: 16, name: 'PAYOGASTA')
City.create(province_id: 16, name: 'PICHANAL')
City.create(province_id: 16, name: 'PIQUETE CABADO')
City.create(province_id: 16, name: 'PIQUIRENDA')
City.create(province_id: 16, name: 'PLUMA DEL PATO')
City.create(province_id: 16, name: 'POTRERILLOS')
City.create(province_id: 16, name: 'POTRERO')
City.create(province_id: 16, name: 'POTRERO DE URIBURU')
City.create(province_id: 16, name: 'POZO BRAVO')
City.create(province_id: 16, name: 'POZO CERRADO')
City.create(province_id: 16, name: 'POZO DE LA ESQUINA')
City.create(province_id: 16, name: 'PROFESOR SALVADOR MAZZA ,EST.POCITOS')
City.create(province_id: 16, name: 'PUCARA')
City.create(province_id: 16, name: 'PUEBLO VIEJO')
City.create(province_id: 16, name: 'PUENTE DE PLATA')
City.create(province_id: 16, name: 'PUERTA DE DIAZ')
City.create(province_id: 16, name: 'PUERTA TASTIL')
City.create(province_id: 16, name: 'PUERTO LA PAZ')
City.create(province_id: 16, name: 'PUNTA DEL AGUA')
City.create(province_id: 16, name: 'QUEBRADA DEL AGUA ,EST.')
City.create(province_id: 16, name: 'QUIJARRO, ANTONIO')
City.create(province_id: 16, name: 'RIO ANCHO ,AP.')
City.create(province_id: 16, name: 'RIO DEL VALLE')
City.create(province_id: 16, name: 'RIO PESCADO')
City.create(province_id: 16, name: 'RIO PIEDRAS')
City.create(province_id: 16, name: 'RIO SECO')
City.create(province_id: 16, name: 'RIO URUEÑA')
City.create(province_id: 16, name: 'RIVADAVIA')
City.create(province_id: 16, name: 'ROSARIO DE LA FRONTERA')
City.create(province_id: 16, name: 'ROSARIO DE LERMA')
City.create(province_id: 16, name: 'ROSARIO DEL DORADO')
City.create(province_id: 16, name: 'SALAR DE POCITOS ,EST.')
City.create(province_id: 16, name: 'SALTA')
City.create(province_id: 16, name: 'SAN AGUSTIN')
City.create(province_id: 16, name: 'SAN ANTONIO DE LOS COBRES')
City.create(province_id: 16, name: 'SAN CARLOS')
City.create(province_id: 16, name: 'SAN JOSE DE ESCALCHI')
City.create(province_id: 16, name: 'SAN LORENZO')
City.create(province_id: 16, name: 'SAN NICOLAS')
City.create(province_id: 16, name: 'SAN PEDRO')
City.create(province_id: 16, name: 'SAN RAMON DE LA NUEVA ORAN')
City.create(province_id: 16, name: 'SANTA MARIA')
City.create(province_id: 16, name: 'SANTA ROSA DE LOS PASTOS GRANDES')
City.create(province_id: 16, name: 'SANTA ROSA DE TASTIL')
City.create(province_id: 16, name: 'SANTA VICTORIA')
City.create(province_id: 16, name: 'SANTA VICTORIA')
City.create(province_id: 16, name: 'SANTO DOMINGO')
City.create(province_id: 16, name: 'SARAVIA, APOLINARIO')
City.create(province_id: 16, name: 'SAUCELITO')
City.create(province_id: 16, name: 'SCHNEIDEWIND')
City.create(province_id: 16, name: 'SECLANTAS')
City.create(province_id: 16, name: 'SENDA HACHADA')
City.create(province_id: 16, name: 'SENILLOSA')
City.create(province_id: 16, name: 'SOCOMPA ,EST.')
City.create(province_id: 16, name: 'SUNCHAL')
City.create(province_id: 16, name: 'TABACAL')
City.create(province_id: 16, name: 'TACA TACA ,EST.')
City.create(province_id: 16, name: 'TACUARA')
City.create(province_id: 16, name: 'TACUY')
City.create(province_id: 16, name: 'TALAPAMPA')
City.create(province_id: 16, name: 'TARTAGAL')
City.create(province_id: 16, name: 'TEDIN, VIRGILIO')
City.create(province_id: 16, name: 'TOBANTIRENDA')
City.create(province_id: 16, name: 'TOLAR GRANDE')
City.create(province_id: 16, name: 'TOLLOCHE')
City.create(province_id: 16, name: 'TOLOMBON')
City.create(province_id: 16, name: 'TONCO')
City.create(province_id: 16, name: 'TONONO')
City.create(province_id: 16, name: 'TRES YUCHANES')
City.create(province_id: 16, name: 'UNQUILLAL ,EMB.')
City.create(province_id: 16, name: 'URIZAR, ESTEBAN DE')
City.create(province_id: 16, name: 'URUNDEL')
City.create(province_id: 16, name: 'VAQUEROS')
City.create(province_id: 16, name: 'VEGA DE ARZARO ,EST.')
City.create(province_id: 16, name: 'VILLA SARMIENTO')
City.create(province_id: 16, name: 'VIRREY TOLEDO')
City.create(province_id: 16, name: 'VUELTA DE LOS TOBAS')
City.create(province_id: 16, name: 'YARIGUARENDA')
City.create(province_id: 16, name: 'YATASTO')
City.create(province_id: 16, name: 'YUCHAN')
City.create(province_id: 17, name: '9 DE JULIO')
City.create(province_id: 17, name: 'ADAN QUIROGA')
City.create(province_id: 17, name: 'ALBARDON')
City.create(province_id: 17, name: 'ALGARROBO VERDE')
City.create(province_id: 17, name: 'ALTO DE SIERRA')
City.create(province_id: 17, name: 'ANGACO NORTE ,EST')
City.create(province_id: 17, name: 'ANGUALASTO')
City.create(province_id: 17, name: 'BALDE DEL ROSARIO')
City.create(province_id: 17, name: 'BAÑO CENTENARIO')
City.create(province_id: 17, name: 'BARREAL')
City.create(province_id: 17, name: 'BARRIALITO')
City.create(province_id: 17, name: 'BARRIO RIVADAVIA')
City.create(province_id: 17, name: 'BELLA VISTA')
City.create(province_id: 17, name: 'BELLA VISTA')
City.create(province_id: 17, name: 'BERMEJO')
City.create(province_id: 17, name: 'BOCA DE LA QUEBRADA')
City.create(province_id: 17, name: 'BUENA ESPERANZA')
City.create(province_id: 17, name: 'CALINGASTA')
