City.create(province_id: 1, name: '16 DE JULIO')
City.create(province_id: 1, name: '17 DE AGOSTO')
City.create(province_id: 1, name: '20 DE JUNIO')
City.create(province_id: 1, name: '20 DE JUNIO ,AP.')
City.create(province_id: 1, name: '25 DE MAYO')
City.create(province_id: 1, name: '30 DE AGOSTO')
City.create(province_id: 1, name: '9 DE JULIO')
City.create(province_id: 1, name: 'A.A.FERNANDEZ ,AP.')
City.create(province_id: 1, name: 'A.F.ORMA ,PDA.')
City.create(province_id: 1, name: 'ABASTO')
City.create(province_id: 1, name: 'ABBOT')
City.create(province_id: 1, name: 'ABEL')
City.create(province_id: 1, name: 'ACASSUSO')
City.create(province_id: 1, name: 'ACEVEDO')
City.create(province_id: 1, name: 'ACHUPALLAS')
City.create(province_id: 1, name: 'ADELA')
City.create(province_id: 1, name: 'AEROPUERTO EZEIZA')
City.create(province_id: 1, name: 'AGOTE')
City.create(province_id: 1, name: 'AGUARA ,EST.')
City.create(province_id: 1, name: 'AGUSTIN FERRARI ,PDA.')
City.create(province_id: 1, name: 'AGUSTIN ROCA')
City.create(province_id: 1, name: 'AGUSTINA')
City.create(province_id: 1, name: 'ALAGON')
City.create(province_id: 1, name: 'ALAMOS')
City.create(province_id: 1, name: 'ALASTUEY')
City.create(province_id: 1, name: 'ALBARIÑO')
City.create(province_id: 1, name: 'ALBERDI VIEJO')
City.create(province_id: 1, name: 'ALBERTI ,EST. ANDRES VACCAREZZA')
City.create(province_id: 1, name: 'ALDEA ROMANA')
City.create(province_id: 1, name: 'ALDO BONZI')
City.create(province_id: 1, name: 'ALEGRE')
City.create(province_id: 1, name: 'ALEJANDRO KORN')
City.create(province_id: 1, name: 'ALEJANDRO PETION ,AP.')
City.create(province_id: 1, name: 'ALFEREZ SAN MARTIN')
City.create(province_id: 1, name: 'ALFREDO DEMARCHI ,EST. QUIROGA')
City.create(province_id: 1, name: 'ALMIRANTE BROWN ,EST. ADROGUE')
City.create(province_id: 1, name: 'ALMIRANTE SOLIER')
City.create(province_id: 1, name: 'ALSINA')
City.create(province_id: 1, name: 'ALTA VISTA')
City.create(province_id: 1, name: 'ALTAMIRA')
City.create(province_id: 1, name: 'ALTAMIRANO')
City.create(province_id: 1, name: 'ALTIMPERGHER ,AP.')
City.create(province_id: 1, name: 'ALTONA')
City.create(province_id: 1, name: 'ALVAREZ DE TOLEDO')
City.create(province_id: 1, name: 'ALVAREZ JONTE')
City.create(province_id: 1, name: 'ALZAGA')
City.create(province_id: 1, name: 'AMALIA')
City.create(province_id: 1, name: 'AMEGHINO')
City.create(province_id: 1, name: 'ANASAGASTI')
City.create(province_id: 1, name: 'ANCON ,EST.')
City.create(province_id: 1, name: 'ANDAT')
City.create(province_id: 1, name: 'ANDERSON')
City.create(province_id: 1, name: 'ANGEL ECHEVERRY')
City.create(province_id: 1, name: 'ANTONIO CARBONI')
City.create(province_id: 1, name: 'APARICIO')
City.create(province_id: 1, name: 'ARANA')
City.create(province_id: 1, name: 'ARANO')
City.create(province_id: 1, name: 'ARAUJO')
City.create(province_id: 1, name: 'ARBOLEDAS')
City.create(province_id: 1, name: 'ARBOLITO')
City.create(province_id: 1, name: 'ARENALES ,EST.')
City.create(province_id: 1, name: 'ARENAZA')
City.create(province_id: 1, name: 'ARGERICH')
City.create(province_id: 1, name: 'ARIEL')
City.create(province_id: 1, name: 'ARISTOBULO DEL VALLE ,EST.')
City.create(province_id: 1, name: 'ARRECIFES')
City.create(province_id: 1, name: 'ARRIBEÑOS')
City.create(province_id: 1, name: 'ARROYO CORTO')
City.create(province_id: 1, name: 'ARROYO DE LA CRUZ')
City.create(province_id: 1, name: 'ARROYO DE LOS HUESOS')
City.create(province_id: 1, name: 'ARROYO DEL MEDIO')
City.create(province_id: 1, name: 'ARROYO DULCE')
City.create(province_id: 1, name: 'ARROYO VENADO')
City.create(province_id: 1, name: 'ARTURO SEGUI')
City.create(province_id: 1, name: 'ARTURO VATTEONE ,EST')
City.create(province_id: 1, name: 'ASAMBLEA')
City.create(province_id: 1, name: 'ASCENSION')
City.create(province_id: 1, name: 'ASTURIAS')
City.create(province_id: 1, name: 'ATALAYA')
City.create(province_id: 1, name: 'ATILIO PESSAGNO')
City.create(province_id: 1, name: 'ATUCHA')
City.create(province_id: 1, name: 'AVELLANEDA')
City.create(province_id: 1, name: 'AVESTRUZ')
City.create(province_id: 1, name: 'AYACUCHO')
City.create(province_id: 1, name: 'AZCUENAGA')
City.create(province_id: 1, name: 'AZOPARDO')
City.create(province_id: 1, name: 'AZUCENA')
City.create(province_id: 1, name: 'AZUL')
City.create(province_id: 1, name: 'BACACAY')
City.create(province_id: 1, name: 'BACCAR')
City.create(province_id: 1, name: 'BADANO')
City.create(province_id: 1, name: 'BAHIA BLANCA')
City.create(province_id: 1, name: 'BAHIA SAN BLAS')
City.create(province_id: 1, name: 'BAIGORRITA')
City.create(province_id: 1, name: 'BAJO HONDO')
City.create(province_id: 1, name: 'BALCARCE')
City.create(province_id: 1, name: 'BALNEARIO ORENSE')
City.create(province_id: 1, name: 'BALNEARIO ORIENTE')
City.create(province_id: 1, name: 'BALNEARIO PEHUEN-CO')
City.create(province_id: 1, name: 'BALSA')
City.create(province_id: 1, name: 'BANCALARI ,AP.')
City.create(province_id: 1, name: 'BANDERALO')
City.create(province_id: 1, name: 'BANFIELD')
City.create(province_id: 1, name: 'BARADERO')
City.create(province_id: 1, name: 'BARISSO')
City.create(province_id: 1, name: 'BARKER')
City.create(province_id: 1, name: 'BARRIO COLONIA ALEGRE')
City.create(province_id: 1, name: 'BARRIO EL RETAZO')
City.create(province_id: 1, name: 'BARRIO SAN PATRICIO')
City.create(province_id: 1, name: 'BARROW')
City.create(province_id: 1, name: 'BARTOLOME BAVIO')
City.create(province_id: 1, name: 'BARTOLOME MITRE ,EST.')
City.create(province_id: 1, name: 'BATAN')
City.create(province_id: 1, name: 'BATHURST')
City.create(province_id: 1, name: 'BAUDRIX')
City.create(province_id: 1, name: 'BAYAUCA')
City.create(province_id: 1, name: 'BELEN DE ESCOBAR')
City.create(province_id: 1, name: 'BELLA VISTA ,EST.TTE.GRL.RICCHIERI')
City.create(province_id: 1, name: 'BELLOCO')
City.create(province_id: 1, name: 'BENAVIDEZ')
City.create(province_id: 1, name: 'BENITEZ')
City.create(province_id: 1, name: 'BERAZATEGUI')
City.create(province_id: 1, name: 'BERDIER')
City.create(province_id: 1, name: 'BERMUDEZ')
City.create(province_id: 1, name: 'BERNAL')
City.create(province_id: 1, name: 'BERRAONDO')
City.create(province_id: 1, name: 'BERUTTI')
City.create(province_id: 1, name: 'BILLINGHURST')
City.create(province_id: 1, name: 'BLANCA GRANDE')
City.create(province_id: 1, name: 'BLANDENGUES')
City.create(province_id: 1, name: 'BLAQUIER')
City.create(province_id: 1, name: 'BLAS DURAÑONA')
City.create(province_id: 1, name: 'BOCA DEL TORO')
City.create(province_id: 1, name: 'BOCAYUVA')
City.create(province_id: 1, name: 'BONNEMENT ,AP.')
City.create(province_id: 1, name: 'BORDENAVE')
City.create(province_id: 1, name: 'BORDEU')
City.create(province_id: 1, name: 'BORGES ,EST.')
City.create(province_id: 1, name: 'BOSCH')
City.create(province_id: 1, name: 'BOSQUES')
City.create(province_id: 1, name: 'BOULOGNE')
City.create(province_id: 1, name: 'BRAGADO')
City.create(province_id: 1, name: 'BRANDSEN ,EST.CNL.BRANDSEN')
City.create(province_id: 1, name: 'BUCHANAN')
City.create(province_id: 1, name: 'BURZACO')
City.create(province_id: 1, name: 'CABILDO')
City.create(province_id: 1, name: 'CACHARI')
City.create(province_id: 1, name: 'CADRET')
City.create(province_id: 1, name: 'CAIOMUTA')
City.create(province_id: 1, name: 'CALDERON')
City.create(province_id: 1, name: 'CALFUCURA')
City.create(province_id: 1, name: 'CALVO')
City.create(province_id: 1, name: 'CAMBACERES')
City.create(province_id: 1, name: 'CAMET')
City.create(province_id: 1, name: 'CAMPANA')
City.create(province_id: 1, name: 'CAMPO DE MAYO')
City.create(province_id: 1, name: 'CAMPODONICO')
City.create(province_id: 1, name: 'CAN, ROBERTO')
City.create(province_id: 1, name: 'CAÑADA MARIANO ,AP.')
City.create(province_id: 1, name: 'CAÑADA SECA')
City.create(province_id: 1, name: 'CANAL SAN FERNANDO ,EST.')
City.create(province_id: 1, name: 'CANGALLO')
City.create(province_id: 1, name: 'CANNING')
City.create(province_id: 1, name: 'CANONIGO GORRITI')
City.create(province_id: 1, name: 'CAÑUELAS')
City.create(province_id: 1, name: 'CAPILLA DEL SEÑOR ,EST.CAPILLA')
City.create(province_id: 1, name: 'CAPITAN CASTRO')
City.create(province_id: 1, name: 'CAPITAN SARMIENTO')
City.create(province_id: 1, name: 'CARABELAS')
City.create(province_id: 1, name: 'CARAPACHAY')
City.create(province_id: 1, name: 'CARBONI, ANTONIO')
City.create(province_id: 1, name: 'CARDENAL CAGLIERO')
City.create(province_id: 1, name: 'CARHUE')
City.create(province_id: 1, name: 'CARMEN DE ARECO')
City.create(province_id: 1, name: 'CASALINS')
City.create(province_id: 1, name: 'CASANOVA, ISIDRO')
City.create(province_id: 1, name: 'CASARES, CARLOS')
City.create(province_id: 1, name: 'CASARES, VICENTE')
City.create(province_id: 1, name: 'CASAS, JOSE B.')
City.create(province_id: 1, name: 'CASBAS')
City.create(province_id: 1, name: 'CASCADA')
City.create(province_id: 1, name: 'CASCALLARES, MICAELA')
City.create(province_id: 1, name: 'CASEROS')
City.create(province_id: 1, name: 'CASEY')
City.create(province_id: 1, name: 'CASTELAR')
City.create(province_id: 1, name: 'CASTELLI')
City.create(province_id: 1, name: 'CASTILLA')
City.create(province_id: 1, name: 'CASTILLO, RAFAEL')
City.create(province_id: 1, name: 'CAZON')
City.create(province_id: 1, name: 'CENTRO AGRICOLA EL PATO ,AP.')
City.create(province_id: 1, name: 'CERRITO')
City.create(province_id: 1, name: 'CHACABUCO')
City.create(province_id: 1, name: 'CHANCAY')
City.create(province_id: 1, name: 'CHAPADMALAL')
City.create(province_id: 1, name: 'CHAPALEUFU')
City.create(province_id: 1, name: 'CHAS')
City.create(province_id: 1, name: 'CHASCOMUS')
City.create(province_id: 1, name: 'CHASICO')
City.create(province_id: 1, name: 'CHENAUT')
City.create(province_id: 1, name: 'CHICLANA')
City.create(province_id: 1, name: 'CHILLAR')
City.create(province_id: 1, name: 'CHIVILCOY')
City.create(province_id: 1, name: 'CHOIQUE')
City.create(province_id: 1, name: 'CIRCUNVALACION ,EST.')
City.create(province_id: 1, name: 'CITY BELL')
City.create(province_id: 1, name: 'CIUDAD GRL.MARTIN MIGUEL DE GUEMES')
City.create(province_id: 1, name: 'CIUDADELA')
City.create(province_id: 1, name: 'CLARAZ')
City.create(province_id: 1, name: 'CLAROMECO')
City.create(province_id: 1, name: 'CLAYPOLE')
City.create(province_id: 1, name: 'COBO')
City.create(province_id: 1, name: 'COBO, MANUEL J.,EST.LEZAMA')
City.create(province_id: 1, name: 'COCHRANE')
City.create(province_id: 1, name: 'COLIQUEO')
City.create(province_id: 1, name: 'COLMAN, MARTIN')
City.create(province_id: 1, name: 'COLON')
City.create(province_id: 1, name: 'COLONIA HOGAR RICARDO GUTIERREZ')
City.create(province_id: 1, name: 'COLONIA SAN MIGUEL ARCANGEL')
City.create(province_id: 1, name: 'COLONIA SERE')
City.create(province_id: 1, name: 'COLONIA VELAZ')
City.create(province_id: 1, name: 'COMANDANTE GIRIBONE')
City.create(province_id: 1, name: 'COMANDANTE NICANOR OTAMENDI')
City.create(province_id: 1, name: 'COMODORO PY')
City.create(province_id: 1, name: 'CONESA')
City.create(province_id: 1, name: 'COPETONAS')
City.create(province_id: 1, name: 'CORACEROS ,EST.')
City.create(province_id: 1, name: 'CORAZZI')
City.create(province_id: 1, name: 'CORBETT')
City.create(province_id: 1, name: 'CORONADO, MARTIN')
City.create(province_id: 1, name: 'CORONEL BOERR')
City.create(province_id: 1, name: 'CORONEL BRANDSEN')
City.create(province_id: 1, name: 'CORONEL CHARLONE')
City.create(province_id: 1, name: 'CORONEL DORREGO')
City.create(province_id: 1, name: 'CORONEL FALCON')
City.create(province_id: 1, name: 'CORONEL GRANADA')
City.create(province_id: 1, name: 'CORONEL MARCELINO FRYRE')
City.create(province_id: 1, name: 'CORONEL MARTINEZ DE HOZ')
City.create(province_id: 1, name: 'CORONEL MARTINIANO CHILAVERT ,PDA.')
City.create(province_id: 1, name: 'CORONEL MOM')
City.create(province_id: 1, name: 'CORONEL PRINGLES ,EST.PRINGLES')
City.create(province_id: 1, name: 'CORONEL RODOLFO BUNGE')
City.create(province_id: 1, name: 'CORONEL SUAREZ')
City.create(province_id: 1, name: 'CORONEL VIDAL')
City.create(province_id: 1, name: 'CORREAS, IGNACIO')
City.create(province_id: 1, name: 'CORTI')
City.create(province_id: 1, name: 'COSTA, EDUARDO')
City.create(province_id: 1, name: 'COVELLO')
City.create(province_id: 1, name: 'CRISTIANO MUERTO')
City.create(province_id: 1, name: 'CROTO')
City.create(province_id: 1, name: 'CURA MALAL')
City.create(province_id: 1, name: 'CURARU')
City.create(province_id: 1, name: 'D ORBIGNY')
City.create(province_id: 1, name: 'DAIREAUX')
City.create(province_id: 1, name: 'DARREGUEIRA')
City.create(province_id: 1, name: 'DE BARY')
City.create(province_id: 1, name: 'DE ELIA, AGUSTIN ,AP.')
City.create(province_id: 1, name: 'DE LA CANAL')
City.create(province_id: 1, name: 'DE LA GARMA')
City.create(province_id: 1, name: 'DE LA PLAZA, VICTORINO')
City.create(province_id: 1, name: 'DE LA RIESTRA, NORBERTO')
City.create(province_id: 1, name: 'DE LUCA, ESTEBAN')
City.create(province_id: 1, name: 'DE VICTORIA, FRANCISCO')
City.create(province_id: 1, name: 'DEFFERRARI')
City.create(province_id: 1, name: 'DEL CARRIL')
City.create(province_id: 1, name: 'DEL VALLE')
City.create(province_id: 1, name: 'DEL VALLE,ARISTOBULO ,EST.')
City.create(province_id: 1, name: 'DEL VISO')
City.create(province_id: 1, name: 'DELTA ,EST.')
City.create(province_id: 1, name: 'DENNEHY')
City.create(province_id: 1, name: 'DESCALZI, NICOLAS')
City.create(province_id: 1, name: 'DIQUE LUJAN')
City.create(province_id: 1, name: 'DOCTOR DOMINGO HAROSTEGUY')
City.create(province_id: 1, name: 'DOCTOR RICARDO LEVENE ,EST.')
City.create(province_id: 1, name: 'DOLORES')
City.create(province_id: 1, name: 'DOMSELAAR')
City.create(province_id: 1, name: 'DON BOSCO')
City.create(province_id: 1, name: 'DON CIPRIANO')
City.create(province_id: 1, name: 'DON TORCUATO')
City.create(province_id: 1, name: 'DOS HERMANOS')
City.create(province_id: 1, name: 'DOYLE')
City.create(province_id: 1, name: 'DRABBLE')
City.create(province_id: 1, name: 'DRYSDALE')
City.create(province_id: 1, name: 'DUCOS')
City.create(province_id: 1, name: 'DUDIGNAC')
City.create(province_id: 1, name: 'DUFAUR')
City.create(province_id: 1, name: 'DUGGAN')
City.create(province_id: 1, name: 'DUHAU')
City.create(province_id: 1, name: 'DURAÑONA')
City.create(province_id: 1, name: 'DUSSAUD ,EST.')
City.create(province_id: 1, name: 'EGAÑA')
City.create(province_id: 1, name: 'EL ARBOLITO')
City.create(province_id: 1, name: 'EL DIA')
City.create(province_id: 1, name: 'EL DIVISORIO')
City.create(province_id: 1, name: 'EL DORADO')
City.create(province_id: 1, name: 'EL LENGUARAZ')
City.create(province_id: 1, name: 'EL MORO')
City.create(province_id: 1, name: 'EL PALOMAR')
City.create(province_id: 1, name: 'EL PARAISO')
City.create(province_id: 1, name: 'EL PENSAMIENTO')
City.create(province_id: 1, name: 'EL PEREGRINO')
City.create(province_id: 1, name: 'EL TALAR')
City.create(province_id: 1, name: 'EL TEJAR')
City.create(province_id: 1, name: 'EL TRIGO')
City.create(province_id: 1, name: 'EL TRIUNFO')
City.create(province_id: 1, name: 'EL ZORRO')
City.create(province_id: 1, name: 'ELIZALDE, RUFINO DE')
City.create(province_id: 1, name: 'ELORDI')
City.create(province_id: 1, name: 'ELVIRA')
City.create(province_id: 1, name: 'EMMA')
City.create(province_id: 1, name: 'ENCINA')
City.create(province_id: 1, name: 'ENERGIA')
City.create(province_id: 1, name: 'ENSENADA')
City.create(province_id: 1, name: 'EPUMER ,EST.YUTUYACO')
City.create(province_id: 1, name: 'ESCALADA')
City.create(province_id: 1, name: 'ESCALADA, REMEDIOS DE')
City.create(province_id: 1, name: 'ESCOBAR, BELEN DE ,EST.ESCOBAR')
City.create(province_id: 1, name: 'ESCRIBANO, PEDRO N.')
City.create(province_id: 1, name: 'ESPARTILLAR')
City.create(province_id: 1, name: 'ESPIGAS')
City.create(province_id: 1, name: 'ESPORA')
City.create(province_id: 1, name: 'ESQUINA NEGRA')
City.create(province_id: 1, name: 'ESTELA')
City.create(province_id: 1, name: 'ESTHER')
City.create(province_id: 1, name: 'ESTOMBA')
City.create(province_id: 1, name: 'ESTRUGAMOU')
City.create(province_id: 1, name: 'ETCHEVERRY, ANGEL')
City.create(province_id: 1, name: 'EZEIZA, JOSE MARIA')
City.create(province_id: 1, name: 'EZPELETA')
City.create(province_id: 1, name: 'FAIR')
City.create(province_id: 1, name: 'FARO')
City.create(province_id: 1, name: 'FAUZON')
City.create(province_id: 1, name: 'FERNANDEZ, A.A.,PDA.')
City.create(province_id: 1, name: 'FERNANDEZ, JUAN N.')
City.create(province_id: 1, name: 'FERRARI, AGUSTIN ,PDA.')
City.create(province_id: 1, name: 'FERRARI, JOSE')
City.create(province_id: 1, name: 'FERRE')
City.create(province_id: 1, name: 'FIORITO')
City.create(province_id: 1, name: 'FLORENCIO VARELA')
City.create(province_id: 1, name: 'FLORIDA')
City.create(province_id: 1, name: 'FLORIDA')
City.create(province_id: 1, name: 'FORTABAT, ALFREDO ,EST.')
City.create(province_id: 1, name: 'FORTIN ACHA')
City.create(province_id: 1, name: 'FORTIN OLAVARRIA')
City.create(province_id: 1, name: 'FORTIN TIBURCIO')
City.create(province_id: 1, name: 'FORTIN VIGILANCIA')
City.create(province_id: 1, name: 'FRENCH')
City.create(province_id: 1, name: 'FULTON')
City.create(province_id: 1, name: 'GAHAN')
City.create(province_id: 1, name: 'GAMBIER ,EST.')
City.create(province_id: 1, name: 'GAMEN, PEDRO')
City.create(province_id: 1, name: 'GANDARA')
City.create(province_id: 1, name: 'GARCIA DEL RIO')
City.create(province_id: 1, name: 'GARCIA, MANUEL J.')
City.create(province_id: 1, name: 'GARDEY')
City.create(province_id: 1, name: 'GARIN')
City.create(province_id: 1, name: 'GARRE')
City.create(province_id: 1, name: 'GASCON, ESTEBAN AGUSTIN')
City.create(province_id: 1, name: 'GENERAL ALVEAR')
City.create(province_id: 1, name: 'GENERAL ARENALES ,EST.ARENALES')
City.create(province_id: 1, name: 'GENERAL BELGRANO')
City.create(province_id: 1, name: 'GENERAL CONESA')
City.create(province_id: 1, name: 'GENERAL DANIEL CERRI ,EST.GRL.CERRI')
City.create(province_id: 1, name: 'GENERAL GUIDO')
City.create(province_id: 1, name: 'GENERAL HORNOS')
City.create(province_id: 1, name: 'GENERAL JUAN MADARIAGA ,EST.G.MADARIAGA')
City.create(province_id: 1, name: 'GENERAL LA MADRID')
City.create(province_id: 1, name: 'GENERAL LAS HERAS ,EST.LAS HERAS')
City.create(province_id: 1, name: 'GENERAL LAVALLE')
City.create(province_id: 1, name: 'GENERAL MANSILLA ,EST.BARTOLOME BAVIO')
City.create(province_id: 1, name: 'GENERAL O\'BRIEN')
City.create(province_id: 1, name: 'GENERAL PACHECO')
City.create(province_id: 1, name: 'GENERAL PINTO')
City.create(province_id: 1, name: 'GENERAL PIRAN')
City.create(province_id: 1, name: 'GENERAL RODRIGUEZ')
City.create(province_id: 1, name: 'GENERAL ROJO')
City.create(province_id: 1, name: 'GENERAL RONDEAU')
City.create(province_id: 1, name: 'GENERAL SAN MARTIN ,EST.SAN MARTIN')
City.create(province_id: 1, name: 'GENERAL VIAMONTE ,EST.LOS TOLDOS')
City.create(province_id: 1, name: 'GENERAL VILLEGAS')
City.create(province_id: 1, name: 'GERLI')
City.create(province_id: 1, name: 'GERMANIA ,EST.MAYOR ORELLANO')
City.create(province_id: 1, name: 'GIL')
City.create(province_id: 1, name: 'GIRODIAS')
City.create(province_id: 1, name: 'GIRONDO')
City.create(province_id: 1, name: 'GLEW')
City.create(province_id: 1, name: 'GNECCO')
City.create(province_id: 1, name: 'GOBERNADOR ARIAS')
City.create(province_id: 1, name: 'GOBERNADOR CASTRO')
City.create(province_id: 1, name: 'GOBERNADOR EDUARDO ARANA ,AP.')
City.create(province_id: 1, name: 'GOBERNADOR LUIS GARCIA ,AP.')
City.create(province_id: 1, name: 'GOBERNADOR MONTEVERDE')
City.create(province_id: 1, name: 'GOBERNADOR UDAONDO')
City.create(province_id: 1, name: 'GOBERNADOR UGARTE')
City.create(province_id: 1, name: 'GOMEZ, VALENTIN')
City.create(province_id: 1, name: 'GONDRA')
City.create(province_id: 1, name: 'GONNET, MANUEL B.')
City.create(province_id: 1, name: 'GONZALEZ CATAN')
City.create(province_id: 1, name: 'GONZALEZ CHAVES, ADOLFO ,EST.G.CHAVES')
City.create(province_id: 1, name: 'GONZALEZ MORENO')
City.create(province_id: 1, name: 'GORCHS')
City.create(province_id: 1, name: 'GORINA, JOAQUIN')
City.create(province_id: 1, name: 'GOROSTIAGA')
City.create(province_id: 1, name: 'GOUIN')
City.create(province_id: 1, name: 'GOYENA')
City.create(province_id: 1, name: 'GOYENECHE')
City.create(province_id: 1, name: 'GRACIARENA')
City.create(province_id: 1, name: 'GRAND BOURG')
City.create(province_id: 1, name: 'GRAVIÑA, RICARDO')
City.create(province_id: 1, name: 'GRUNBEIN')
City.create(province_id: 1, name: 'GRUNBEIN ,EST.EMP.')
City.create(province_id: 1, name: 'GUAMINI')
City.create(province_id: 1, name: 'GUANACO')
City.create(province_id: 1, name: 'GUERNICA')
City.create(province_id: 1, name: 'GUERRERO')
City.create(province_id: 1, name: 'GUERRICO')
City.create(province_id: 1, name: 'GUILLON, LUIS')
City.create(province_id: 1, name: 'GUISASOLA,JOSE A.')
City.create(province_id: 1, name: 'GUNTHER')
City.create(province_id: 1, name: 'GUTIERREZ, JUAN M.')
City.create(province_id: 1, name: 'HAEDO')
City.create(province_id: 1, name: 'HALE')
City.create(province_id: 1, name: 'HEAVY')
City.create(province_id: 1, name: 'HENDERSON')
City.create(province_id: 1, name: 'HEREFORD')
City.create(province_id: 1, name: 'HERNANDEZ, JOSE')
City.create(province_id: 1, name: 'HERRERA VEGAS')
City.create(province_id: 1, name: 'HINOJO')
City.create(province_id: 1, name: 'HIRSCH, MAURICIO')
City.create(province_id: 1, name: 'HORTENSIA')
City.create(province_id: 1, name: 'HUANGUELEN')
City.create(province_id: 1, name: 'HUDSON, GUILLERMO E.')
City.create(province_id: 1, name: 'HUERGO,DELFIN')
City.create(province_id: 1, name: 'HUETEL')
City.create(province_id: 1, name: 'HUNTER')
City.create(province_id: 1, name: 'HURLINGHAM')
City.create(province_id: 1, name: 'HUSARES')
City.create(province_id: 1, name: 'IBAÑEZ')
City.create(province_id: 1, name: 'IBARRA,JUAN F.')
City.create(province_id: 1, name: 'IGARZABAL')
City.create(province_id: 1, name: 'INDART, INES')
City.create(province_id: 1, name: 'INDIO RICO')
City.create(province_id: 1, name: 'INGENIERO ANDRES VILLANUEVA ,AP.')
City.create(province_id: 1, name: 'INGENIERO BALBIN')
City.create(province_id: 1, name: 'INGENIERO BEAUGEY')
City.create(province_id: 1, name: 'INGENIERO BUNGE')
City.create(province_id: 1, name: 'INGENIERO JUAN ALLAN')
City.create(province_id: 1, name: 'INGENIERO MASCHWITZ')
City.create(province_id: 1, name: 'INGENIERO MONETA')
City.create(province_id: 1, name: 'INGENIERO PABLO NOGUES')
City.create(province_id: 1, name: 'INGENIERO SANTIAGO BRIAN ,AP.')
City.create(province_id: 1, name: 'INGENIERO THOMPSON')
City.create(province_id: 1, name: 'INGENIERO WIHTE')
City.create(province_id: 1, name: 'INGENIERO WILLIAMS')
City.create(province_id: 1, name: 'INVERNADAS')
City.create(province_id: 1, name: 'IRALA')
City.create(province_id: 1, name: 'IRAOLA')
City.create(province_id: 1, name: 'IRENE')
City.create(province_id: 1, name: 'IRIARTE')
City.create(province_id: 1, name: 'ISLAS')
City.create(province_id: 1, name: 'ITURREGUI')
City.create(province_id: 1, name: 'ITUZAINGO')
City.create(province_id: 1, name: 'JEPPENER')
City.create(province_id: 1, name: 'JOFRE, TOMAS')
City.create(province_id: 1, name: 'JUANCHO')
City.create(province_id: 1, name: 'JUAREZ, BENITO ,EST.JUAREZ')
City.create(province_id: 1, name: 'JUNIN')
City.create(province_id: 1, name: 'JUSTO VILLEGAS ,PDA.')
City.create(province_id: 1, name: 'JUSTO, JUAN B. ,PDA.')
City.create(province_id: 1, name: 'KILOMERO 8 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 12 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 17 ,PDA.')
City.create(province_id: 1, name: 'KILOMETRO 19 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 27 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 34 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 36 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 40 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 40 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 45 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 48 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 53 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 54 ,PDA.')
City.create(province_id: 1, name: 'KILOMETRO 55 ,AP.')
City.create(province_id: 1, name: 'KILOMETRO 641 ,PDA.')
City.create(province_id: 1, name: 'KILOMETRO 9 ,AP.')
City.create(province_id: 1, name: 'KORN, ALEJANDRO')
City.create(province_id: 1, name: 'KRABBE')
City.create(province_id: 1, name: 'LA ANGELITA')
City.create(province_id: 1, name: 'LA BARRANCOSA')
City.create(province_id: 1, name: 'LA BEBA')
City.create(province_id: 1, name: 'LA CARRETA')
City.create(province_id: 1, name: 'LA COLINA')
City.create(province_id: 1, name: 'LA CONSTANCIA ,AP.KILOMETRO 360')
City.create(province_id: 1, name: 'LA COPETA ,EST.')
City.create(province_id: 1, name: 'LA CUMBRE ,PDA.')
City.create(province_id: 1, name: 'LA DELFINA')
City.create(province_id: 1, name: 'LA DORITA')
City.create(province_id: 1, name: 'LA EMILIA')
City.create(province_id: 1, name: 'LA INVENCIBLE')
City.create(province_id: 1, name: 'LA LARGA')
City.create(province_id: 1, name: 'LA LIMPIA')
City.create(province_id: 1, name: 'LA LUCILA')
City.create(province_id: 1, name: 'LA LUCILA DEL MAR')
City.create(province_id: 1, name: 'LA LUISA')
City.create(province_id: 1, name: 'LA MANUELA')
City.create(province_id: 1, name: 'LA MASCOTA ,EST.MASCOTA')
City.create(province_id: 1, name: 'LA NEGRA')
City.create(province_id: 1, name: 'LA NEVADA')
City.create(province_id: 1, name: 'LA NIÑA')
City.create(province_id: 1, name: 'LA NORIA')
City.create(province_id: 1, name: 'LA ORIENTAL')
City.create(province_id: 1, name: 'LA PALA')
City.create(province_id: 1, name: 'LA PASTORA')
City.create(province_id: 1, name: 'LA PLATA')
City.create(province_id: 1, name: 'LA PORTEÑA')
City.create(province_id: 1, name: 'LA PRIMAVERA')
City.create(province_id: 1, name: 'LA PROVIDENCIA')
City.create(province_id: 1, name: 'LA REFORMA')
City.create(province_id: 1, name: 'LA REJA')
City.create(province_id: 1, name: 'LA RICA')
City.create(province_id: 1, name: 'LA SALADA')
City.create(province_id: 1, name: 'LA SOFIA')
City.create(province_id: 1, name: 'LA SORTIJA')
City.create(province_id: 1, name: 'LA VIOLETA')
City.create(province_id: 1, name: 'LA VITICOLA')
City.create(province_id: 1, name: 'LA ZANJA')
City.create(province_id: 1, name: 'LABARDEN')
City.create(province_id: 1, name: 'LAFERRERE')
City.create(province_id: 1, name: 'LAGO EPECUEN')
City.create(province_id: 1, name: 'LAGUNA ALSINA ,EST.BONIFACIO')
City.create(province_id: 1, name: 'LAMARCA, EMILIO')
City.create(province_id: 1, name: 'LANGUEYU')
City.create(province_id: 1, name: 'LANUS')
City.create(province_id: 1, name: 'LAPLACETE')
City.create(province_id: 1, name: 'LAPRIDA')
City.create(province_id: 1, name: 'LARRE, SANTIAGO')
City.create(province_id: 1, name: 'LARTIGAU')
City.create(province_id: 1, name: 'LAS ARMAS')
City.create(province_id: 1, name: 'LAS BARRANCAS')
City.create(province_id: 1, name: 'LAS CHACRAS')
City.create(province_id: 1, name: 'LAS FLORES')
City.create(province_id: 1, name: 'LAS HERMANAS')
City.create(province_id: 1, name: 'LAS MALVINAS')
City.create(province_id: 1, name: 'LAS MARIANAS')
City.create(province_id: 1, name: 'LAS NUTRIAS')
City.create(province_id: 1, name: 'LAS PALMAS')
City.create(province_id: 1, name: 'LAS PARVAS')
City.create(province_id: 1, name: 'LAS TOSCAS')
City.create(province_id: 1, name: 'LAS VAQUERIAS')
City.create(province_id: 1, name: 'LASALLE, PEDRO P.')
City.create(province_id: 1, name: 'LASTRA')
City.create(province_id: 1, name: 'LAVALLE, ENRIQUE')
City.create(province_id: 1, name: 'LAVALLOL')
City.create(province_id: 1, name: 'LAZZARINO')
City.create(province_id: 1, name: 'LERTORA')
City.create(province_id: 1, name: 'LEUBUCO')
City.create(province_id: 1, name: 'LEVALLE, NICOLAS')
City.create(province_id: 1, name: 'LIBANO')
City.create(province_id: 1, name: 'LIBERTAD')
City.create(province_id: 1, name: 'LIBRES DEL SUD')
City.create(province_id: 1, name: 'LICENCIADO MATIENZO')
City.create(province_id: 1, name: 'LIMA')
City.create(province_id: 1, name: 'LIN CALEL')
City.create(province_id: 1, name: 'LINCOLN')
City.create(province_id: 1, name: 'LLORENTE, GALO')
City.create(province_id: 1, name: 'LOBERIA')
City.create(province_id: 1, name: 'LOBOS')
City.create(province_id: 1, name: 'LOMA NEGRA')
City.create(province_id: 1, name: 'LOMA PARAGUAYA ,EST.')
City.create(province_id: 1, name: 'LOMA VERDE')
City.create(province_id: 1, name: 'LOMAS DE ZAMORA')
City.create(province_id: 1, name: 'LONGCHAMPS')
City.create(province_id: 1, name: 'LOPEZ')
City.create(province_id: 1, name: 'LOPEZ CAMELO ,PDA.')
City.create(province_id: 1, name: 'LOPEZ LECUBE')
City.create(province_id: 1, name: 'LOPEZ, VICENTE')
City.create(province_id: 1, name: 'LOS ANGELES')
City.create(province_id: 1, name: 'LOS GAUCHOS ,PDA.')
City.create(province_id: 1, name: 'LOS INDIOS')
City.create(province_id: 1, name: 'LOS PINOS')
City.create(province_id: 1, name: 'LOS POLVORINES')
City.create(province_id: 1, name: 'LOUGE')
City.create(province_id: 1, name: 'LOURDES')
City.create(province_id: 1, name: 'LUJAN')
City.create(province_id: 1, name: 'LUMB')
City.create(province_id: 1, name: 'LURO')
City.create(province_id: 1, name: 'LURO, PEDRO')
City.create(province_id: 1, name: 'MACEDO')
City.create(province_id: 1, name: 'MACHITA')
City.create(province_id: 1, name: 'MADERO, FRANCISCO')
City.create(province_id: 1, name: 'MAGDALA')
City.create(province_id: 1, name: 'MAGDALENA')
City.create(province_id: 1, name: 'MAGNANO, FRANCISCO')
City.create(province_id: 1, name: 'MAGUIRRE')
City.create(province_id: 1, name: 'MAIPU')
City.create(province_id: 1, name: 'MALAVER ,PDA.')
City.create(province_id: 1, name: 'MAMAGUITA')
City.create(province_id: 1, name: 'MAPIS')
City.create(province_id: 1, name: 'MAQUINISTA SAVIO')
City.create(province_id: 1, name: 'MAR DE AJO')
City.create(province_id: 1, name: 'MAR DEL PLATA')
City.create(province_id: 1, name: 'MAR DEL TUYU')
City.create(province_id: 1, name: 'MARI LAUQUEN')
City.create(province_id: 1, name: 'MARIA IGNACIA ,EST.VEIA')
City.create(province_id: 1, name: 'MARIA LUCILA')
City.create(province_id: 1, name: 'MARMOL, JOSE')
City.create(province_id: 1, name: 'MARTIN FIERRO')
City.create(province_id: 1, name: 'MARTINEZ')
City.create(province_id: 1, name: 'MARUCHA')
City.create(province_id: 1, name: 'MASUREL ,EST.')
City.create(province_id: 1, name: 'MATHEU')
City.create(province_id: 1, name: 'MAYOR BURATOVICH')
City.create(province_id: 1, name: 'MAZA')
City.create(province_id: 1, name: 'MECHONGUE')
City.create(province_id: 1, name: 'MEDANOS')
City.create(province_id: 1, name: 'MEMBRILLAR')
City.create(province_id: 1, name: 'MERCEDES')
City.create(province_id: 1, name: 'MERLO')
City.create(province_id: 1, name: 'MERLO GOMEZ ,AP.')
City.create(province_id: 1, name: 'MICHEO, JOSE M.')
City.create(province_id: 1, name: 'MIGUELETE ,PDA.')
City.create(province_id: 1, name: 'MINISTRO RIVADAVIA')
City.create(province_id: 1, name: 'MIRA PAMPA')
City.create(province_id: 1, name: 'MIRAMAR')
City.create(province_id: 1, name: 'MIRAMONTE')
City.create(province_id: 1, name: 'MIRANDA')
City.create(province_id: 1, name: 'MITRE, BARTOLOME ,EST.')
City.create(province_id: 1, name: 'MOCTEZUMA')
City.create(province_id: 1, name: 'MOLINA, CLAUDIO')
City.create(province_id: 1, name: 'MONASTERIO')
City.create(province_id: 1, name: 'MONES CAZON')
City.create(province_id: 1, name: 'MONROE')
City.create(province_id: 1, name: 'MONSALVO')
City.create(province_id: 1, name: 'MONTE CHINGOLO')
City.create(province_id: 1, name: 'MONTE GRANDE')
City.create(province_id: 1, name: 'MONTE HERMOSO')
City.create(province_id: 1, name: 'MONTE VELOZ')
City.create(province_id: 1, name: 'MONTES DE OCA')
City.create(province_id: 1, name: 'MOORES')
City.create(province_id: 1, name: 'MOQUEHUA')
City.create(province_id: 1, name: 'MORENO, MARIANO ,EST.MORENO')
City.create(province_id: 1, name: 'MORON')
City.create(province_id: 1, name: 'MORRIS, WILIAM C.,PDA.')
City.create(province_id: 1, name: 'MORSE')
City.create(province_id: 1, name: 'MOSCONI')
City.create(province_id: 1, name: 'MOURAS ,EST.')
City.create(province_id: 1, name: 'MUÑIZ')
City.create(province_id: 1, name: 'MUÑOZ')
City.create(province_id: 1, name: 'MUNRO')
City.create(province_id: 1, name: 'MURATURE, FRANCISCO')
City.create(province_id: 1, name: 'NAHUEL RUCA')
City.create(province_id: 1, name: 'NAON, CARLOS M.')
City.create(province_id: 1, name: 'NAPALEOFU')
City.create(province_id: 1, name: 'NAPOSTA')
City.create(province_id: 1, name: 'NAVARRO')
City.create(province_id: 1, name: 'NECOCHEA')
City.create(province_id: 1, name: 'NECOL')
City.create(province_id: 1, name: 'NEILD, RAMON J.')
City.create(province_id: 1, name: 'NEWTON')
City.create(province_id: 1, name: 'NIEVES')
City.create(province_id: 1, name: 'NORUMBEGA')
City.create(province_id: 1, name: 'NUEVA PLATA')
City.create(province_id: 1, name: 'NUEVA ROMA')
City.create(province_id: 1, name: 'NUEVA SUIZA ,EST.')
City.create(province_id: 1, name: 'OBLIGADO')
City.create(province_id: 1, name: 'OBLIGADO, RAFAEL')
City.create(province_id: 1, name: 'OCAMPO, MANUEL')
City.create(province_id: 1, name: 'OCHANDIO')
City.create(province_id: 1, name: 'O\'HIGGINS')
City.create(province_id: 1, name: 'OLASCOAGA')
City.create(province_id: 1, name: 'OLAVARRIA')
City.create(province_id: 1, name: 'OLIDEN')
City.create(province_id: 1, name: 'OLIVERA, NICANOR ,EST.LA DULCE')
City.create(province_id: 1, name: 'OLIVOS')
City.create(province_id: 1, name: 'OLMOS, LISANDRO ,AP.')
City.create(province_id: 1, name: 'OMBU')
City.create(province_id: 1, name: 'OMBUCTA')
City.create(province_id: 1, name: 'ORDOQUI')
City.create(province_id: 1, name: 'ORENSE')
City.create(province_id: 1, name: 'ORIENTE')
City.create(province_id: 1, name: 'ORMA, ADOLFO F. ,AP.')
City.create(province_id: 1, name: 'ORTIZ BASUALDO')
City.create(province_id: 1, name: 'ORTIZ DE ROSAS')
City.create(province_id: 1, name: 'OSTENDE')
City.create(province_id: 1, name: 'OTOÑO ,EST.')
City.create(province_id: 1, name: 'PADILLA, MIGUEL MANUEL ,EST.')
City.create(province_id: 1, name: 'PARAGUIL')
City.create(province_id: 1, name: 'PARDO')
City.create(province_id: 1, name: 'PARISH')
City.create(province_id: 1, name: 'PARRAVICINI')
City.create(province_id: 1, name: 'PASCO ,AP.')
City.create(province_id: 1, name: 'PASMAN')
City.create(province_id: 1, name: 'PASO DEL REY')
City.create(province_id: 1, name: 'PASO MAYOR')
City.create(province_id: 1, name: 'PASO, JUAN JOSE')
City.create(province_id: 1, name: 'PASTEUR')
City.create(province_id: 1, name: 'PATAGONES, CARMEN DE')
City.create(province_id: 1, name: 'PATRICIOS')
City.create(province_id: 1, name: 'PAYRO, ROBERTO')
City.create(province_id: 1, name: 'PAZ, JOSE C.')
City.create(province_id: 1, name: 'PAZ, MARCOS')
City.create(province_id: 1, name: 'PAZ, MAXIMO')
City.create(province_id: 1, name: 'PAZOS KANKI')
City.create(province_id: 1, name: 'PEARSON')
City.create(province_id: 1, name: 'PEDERNALES')
City.create(province_id: 1, name: 'PEHUAJO')
City.create(province_id: 1, name: 'PEHUELCHES')
City.create(province_id: 1, name: 'PEHUEN-CO')
City.create(province_id: 1, name: 'PELICURA')
City.create(province_id: 1, name: 'PELLEGRINI')
City.create(province_id: 1, name: 'PERALTA')
City.create(province_id: 1, name: 'PEREDA, VICENTE')
City.create(province_id: 1, name: 'PEREZ MILLAN')
City.create(province_id: 1, name: 'PEREZ, ROQUE')
City.create(province_id: 1, name: 'PERGAMINO')
City.create(province_id: 1, name: 'PESSAGNO, ATILIO')
City.create(province_id: 1, name: 'PETION, ALEJANDRO ,PDA.')
City.create(province_id: 1, name: 'PICHINCHA')
City.create(province_id: 1, name: 'PIEDRA ECHADA')
City.create(province_id: 1, name: 'PIEDRITAS')
City.create(province_id: 1, name: 'PIERES')
City.create(province_id: 1, name: 'PIGUE')
City.create(province_id: 1, name: 'PILA')
City.create(province_id: 1, name: 'PILAR')
City.create(province_id: 1, name: 'PILLAHUINCO')
City.create(province_id: 1, name: 'PINAMAR')
City.create(province_id: 1, name: 'PIÑERO')
City.create(province_id: 1, name: 'PIÑEYRO')
City.create(province_id: 1, name: 'PIPINAS')
City.create(province_id: 1, name: 'PIROVANO')
City.create(province_id: 1, name: 'PLA')
City.create(province_id: 1, name: 'PLATANOS')
City.create(province_id: 1, name: 'PLAZA MONTERO')
City.create(province_id: 1, name: 'POBLET')
City.create(province_id: 1, name: 'POLVAREDAS')
City.create(province_id: 1, name: 'PONTAUT')
City.create(province_id: 1, name: 'PONTEVEDRA')
City.create(province_id: 1, name: 'PORTELA, IRINEO')
City.create(province_id: 1, name: 'PORVENIR')
City.create(province_id: 1, name: 'POURTALE')
City.create(province_id: 1, name: 'PRADERE, JUAN A.')
City.create(province_id: 1, name: 'PRESIDENTE QUINTANA')
City.create(province_id: 1, name: 'PRIMERA JUNTA')
City.create(province_id: 1, name: 'PUAN')
City.create(province_id: 1, name: 'PUEBLITOS')
City.create(province_id: 1, name: 'PUENTE CASCALLARES')
City.create(province_id: 1, name: 'PUERTO BELGRANO')
City.create(province_id: 1, name: 'PUERTO CUATREROS')
City.create(province_id: 1, name: 'PUERTO GALVAN')
City.create(province_id: 1, name: 'PUERTO ROSALES')
City.create(province_id: 1, name: 'PUNTA ALTA ,EST.ALMIRANTE SOLIER')
City.create(province_id: 1, name: 'PUNTA CHICA')
City.create(province_id: 1, name: 'PUNTA INDIO')
City.create(province_id: 1, name: 'PUNTA LARA')
City.create(province_id: 1, name: 'QUENUMA')
City.create(province_id: 1, name: 'QUEQUEN')
City.create(province_id: 1, name: 'QUERANDI ,EST.')
City.create(province_id: 1, name: 'QUERANDIES ,EMP.')
City.create(province_id: 1, name: 'QUILCO')
City.create(province_id: 1, name: 'QUILMES')
City.create(province_id: 1, name: 'QUIÑIHUAL')
City.create(province_id: 1, name: 'QUIRNO COSTA')
City.create(province_id: 1, name: 'QUIROGA')
City.create(province_id: 1, name: 'RAMALLO')
City.create(province_id: 1, name: 'RAMOS MEJIA')
City.create(province_id: 1, name: 'RAMOS OTERO')
City.create(province_id: 1, name: 'RANCAGUA')
City.create(province_id: 1, name: 'RANCHOS')
City.create(province_id: 1, name: 'RANELAGH')
City.create(province_id: 1, name: 'RAUCH')
City.create(province_id: 1, name: 'RAULET')
City.create(province_id: 1, name: 'RAWSON')
City.create(province_id: 1, name: 'REAL AUDIENCIA')
City.create(province_id: 1, name: 'RECALDE')
City.create(province_id: 1, name: 'RESERVA')
City.create(province_id: 1, name: 'RETA')
City.create(province_id: 1, name: 'RINGUELET')
City.create(province_id: 1, name: 'RIO LUJAN ,EST.')
City.create(province_id: 1, name: 'RIO SALADO ,AP.')
City.create(province_id: 1, name: 'RIO TALA')
City.create(province_id: 1, name: 'RIVADAVIA ,EST.AMERICA')
City.create(province_id: 1, name: 'RIVADEO')
City.create(province_id: 1, name: 'RIVAS')
City.create(province_id: 1, name: 'RIVERA')
City.create(province_id: 1, name: 'ROBERTS')
City.create(province_id: 1, name: 'ROCA, AGUSTIN')
City.create(province_id: 1, name: 'ROCHA')
City.create(province_id: 1, name: 'ROJAS')
City.create(province_id: 1, name: 'ROLDAN, MARIANO')
City.create(province_id: 1, name: 'ROLITO')
City.create(province_id: 1, name: 'ROMERO, ELIAS ,EST.')
City.create(province_id: 1, name: 'ROMERO, MELCHOR')
City.create(province_id: 1, name: 'ROOSEVELT')
City.create(province_id: 1, name: 'ROSAS')
City.create(province_id: 1, name: 'RUBEN DARIO ,EST.')
City.create(province_id: 1, name: 'RUIZ')
City.create(province_id: 1, name: 'SAAVEDRA')
City.create(province_id: 1, name: 'SAENZ PEÑA')
City.create(province_id: 1, name: 'SALADILLO')
City.create(province_id: 1, name: 'SALAS, CARLOS')
City.create(province_id: 1, name: 'SALAZAR')
City.create(province_id: 1, name: 'SALDUNGARAY')
City.create(province_id: 1, name: 'SALINERA ,DV.')
City.create(province_id: 1, name: 'SALLIQUELO')
City.create(province_id: 1, name: 'SALTO')
City.create(province_id: 1, name: 'SALVADOR MARIA')
City.create(province_id: 1, name: 'SAN AGUSTIN')
City.create(province_id: 1, name: 'SAN ANDRES')
City.create(province_id: 1, name: 'SAN ANDRES DE GILES ,EST.GILES')
City.create(province_id: 1, name: 'SAN ANTONIO DE ARECO')
City.create(province_id: 1, name: 'SAN ANTONIO DE PADUA')
City.create(province_id: 1, name: 'SAN BERNARDO')
City.create(province_id: 1, name: 'SAN BERNARDO')
City.create(province_id: 1, name: 'SAN CARLOS DE BOLIVAR ,EST.BOLIVAR')
City.create(province_id: 1, name: 'SAN CAYETANO')
City.create(province_id: 1, name: 'SAN CLEMENTE DEL TUYU')
City.create(province_id: 1, name: 'SAN ELADIO')
City.create(province_id: 1, name: 'SAN EMILIO')
City.create(province_id: 1, name: 'SAN ENRIQUE')
City.create(province_id: 1, name: 'SAN FERMIN')
City.create(province_id: 1, name: 'SAN FERNANDO')
City.create(province_id: 1, name: 'SAN FRANCISCO DE BELLOCQ')
City.create(province_id: 1, name: 'SAN FRANCISCO SOLANO ,PDA.KILOMETRO 26')
City.create(province_id: 1, name: 'SAN GERMAN')
City.create(province_id: 1, name: 'SAN IGNACIO')
City.create(province_id: 1, name: 'SAN ISIDRO')
City.create(province_id: 1, name: 'SAN JORGE')
City.create(province_id: 1, name: 'SAN JOSE')
City.create(province_id: 1, name: 'SAN JOSE')
City.create(province_id: 1, name: 'SAN JUSTO')
City.create(province_id: 1, name: 'SAN MANUEL')
City.create(province_id: 1, name: 'SAN MAURICIO')
City.create(province_id: 1, name: 'SAN MAYOL')
City.create(province_id: 1, name: 'SAN MIGUEL')
City.create(province_id: 1, name: 'SAN MIGUEL ,EST.GENERAL SARMIENTO')
City.create(province_id: 1, name: 'SAN MIGUEL DEL MONTE ,EST.MONTE')
City.create(province_id: 1, name: 'SAN NICOLAS DE LOS ARROYOS,EST.S.NICOLAS')
City.create(province_id: 1, name: 'SAN PATRICIO')
City.create(province_id: 1, name: 'SAN PEDRO')
City.create(province_id: 1, name: 'SAN ROMAN')
City.create(province_id: 1, name: 'SAN VICENTE')
City.create(province_id: 1, name: 'SANDRINI ,DV.')
City.create(province_id: 1, name: 'SANSINENA')
City.create(province_id: 1, name: 'SANTA CATALINA')
City.create(province_id: 1, name: 'SANTA COLOMA')
City.create(province_id: 1, name: 'SANTA ELENA')
City.create(province_id: 1, name: 'SANTA ELEODORA')
City.create(province_id: 1, name: 'SANTA INES')
City.create(province_id: 1, name: 'SANTA LUCIA')
City.create(province_id: 1, name: 'SANTA LUCIA')
City.create(province_id: 1, name: 'SANTA MARIA')
City.create(province_id: 1, name: 'SANTA REGINA')
City.create(province_id: 1, name: 'SANTA REGINA')
City.create(province_id: 1, name: 'SANTA TERESITA')
City.create(province_id: 1, name: 'SANTAMARINA, RAMON')
City.create(province_id: 1, name: 'SANTO DOMINGO')
City.create(province_id: 1, name: 'SANTOS AREVALO, JOSE')
City.create(province_id: 1, name: 'SANTOS LUGARES')
City.create(province_id: 1, name: 'SANTOS UNZUE')
City.create(province_id: 1, name: 'SARANDI')
City.create(province_id: 1, name: 'SARASA')
City.create(province_id: 1, name: 'SATURNO')
City.create(province_id: 1, name: 'SEGUI, ARTURO')
City.create(province_id: 1, name: 'SEGUROLA')
City.create(province_id: 1, name: 'SEVIGNE')
City.create(province_id: 1, name: 'SHAW')
City.create(province_id: 1, name: 'SIERRA CHICA')
City.create(province_id: 1, name: 'SIERRA DE LA VENTANA')
City.create(province_id: 1, name: 'SIERRAS BAYAS')
City.create(province_id: 1, name: 'SMITH')
City.create(province_id: 1, name: 'SOLA, FELIPE')
City.create(province_id: 1, name: 'SOLANET')
City.create(province_id: 1, name: 'SOSA, INOCENCIO')
City.create(province_id: 1, name: 'SOURDEAUX, ADOLFO ,PDA.')
City.create(province_id: 1, name: 'SOURIGUES, CARLOS ,AP.')
City.create(province_id: 1, name: 'SPANO, GUIDO')
City.create(province_id: 1, name: 'SPEGAZZINI, CARLOS')
City.create(province_id: 1, name: 'SPURR ,EST.')
City.create(province_id: 1, name: 'STEGMANN')
City.create(province_id: 1, name: 'STROEDER')
City.create(province_id: 1, name: 'SUAREZ, JOSE LEON')
City.create(province_id: 1, name: 'SUAREZ, TRISTAN')
City.create(province_id: 1, name: 'SUIPACHA')
City.create(province_id: 1, name: 'SUNDBLAD')
City.create(province_id: 1, name: 'TABLADA')
City.create(province_id: 1, name: 'TACUARI')
City.create(province_id: 1, name: 'TAMANGUEYU')
City.create(province_id: 1, name: 'TANDIL')
City.create(province_id: 1, name: 'TAPALQUE')
City.create(province_id: 1, name: 'TAPIALES')
City.create(province_id: 1, name: 'TATAY')
City.create(province_id: 1, name: 'TEJEDOR, CARLOS ,EST.TEJEDOR')
City.create(province_id: 1, name: 'TEMPERLEY')
City.create(province_id: 1, name: 'TENIENTE CORONEL MIÑANA')
City.create(province_id: 1, name: 'TENIENTE ORIGONE')
City.create(province_id: 1, name: 'THAMES')
City.create(province_id: 1, name: 'TIGRE')
City.create(province_id: 1, name: 'TIMOTE')
City.create(province_id: 1, name: 'TIMOTE ,EST.')
City.create(province_id: 1, name: 'TODD')
City.create(province_id: 1, name: 'TOLOSA')
City.create(province_id: 1, name: 'TORNQUIST')
City.create(province_id: 1, name: 'TORTUGUITAS')
City.create(province_id: 1, name: 'TRENQUE LAUQUEN')
City.create(province_id: 1, name: 'TRES ALGARROBOS ,EST.CUENCA')
City.create(province_id: 1, name: 'TRES ARROYOS')
City.create(province_id: 1, name: 'TRES LAGUNAS')
City.create(province_id: 1, name: 'TRES LOMAS')
City.create(province_id: 1, name: 'TRES PICOS')
City.create(province_id: 1, name: 'TRIUNVIRATO')
City.create(province_id: 1, name: 'TRONCONI, JUAN')
City.create(province_id: 1, name: 'TRONGE')
City.create(province_id: 1, name: 'TURDERA')
City.create(province_id: 1, name: 'TUYUTI')
City.create(province_id: 1, name: 'UBALLES, EUFEMIO')
City.create(province_id: 1, name: 'UDAQUIOLA')
City.create(province_id: 1, name: 'UNION FERROVIARIA ,PDA.')
City.create(province_id: 1, name: 'UNZUE, MARIANO')
City.create(province_id: 1, name: 'URDAMPILLETA')
City.create(province_id: 1, name: 'URIBURU, TEDIN')
City.create(province_id: 1, name: 'VALDES')
City.create(province_id: 1, name: 'VALLIMANCA')
City.create(province_id: 1, name: 'VARELA, FLORENCIO')
City.create(province_id: 1, name: 'VASQUEZ')
City.create(province_id: 1, name: 'VATTEONE, ARTURO ,EST.')
City.create(province_id: 1, name: 'VEDIA')
City.create(province_id: 1, name: 'VELLOSO')
City.create(province_id: 1, name: 'VERGARA')
City.create(province_id: 1, name: 'VERONICA')
City.create(province_id: 1, name: 'VICEALMIRANTE E.MONTES')
City.create(province_id: 1, name: 'VICTORIA')
City.create(province_id: 1, name: 'VIDELA DORNA, ZENON')
City.create(province_id: 1, name: 'VIEYTES')
City.create(province_id: 1, name: 'VILELA')
City.create(province_id: 1, name: 'VILLA ADELINA')
City.create(province_id: 1, name: 'VILLA ANGELICA ,EST,EL SOCORRO')
City.create(province_id: 1, name: 'VILLA BALLESTER')
City.create(province_id: 1, name: 'VILLA BARILARI')
City.create(province_id: 1, name: 'VILLA BOSCH ,PDA.JUAN MARIA BOSCH')
City.create(province_id: 1, name: 'VILLA CARAZA')
City.create(province_id: 1, name: 'VILLA CASTELAR ,EST.ERIZE')
City.create(province_id: 1, name: 'VILLA CRISTOBAL COLON')
City.create(province_id: 1, name: 'VILLA DE MAYO')
City.create(province_id: 1, name: 'VILLA DIAMANTE')
City.create(province_id: 1, name: 'VILLA DOMINICO')
City.create(province_id: 1, name: 'VILLA EL CACIQUE')
City.create(province_id: 1, name: 'VILLA ELISA')
City.create(province_id: 1, name: 'VILLA ESPAÑA')
City.create(province_id: 1, name: 'VILLA GARIBALDI')
City.create(province_id: 1, name: 'VILLA GENERAL ARIAS ,EST.KILOMETRO 638')
City.create(province_id: 1, name: 'VILLA GENERAL SAVIO EST.SANCHEZ')
City.create(province_id: 1, name: 'VILLA GESEL')
City.create(province_id: 1, name: 'VILLA GIAMBRUNO')
City.create(province_id: 1, name: 'VILLA HARDING GREEN')
City.create(province_id: 1, name: 'VILLA IRIS')
City.create(province_id: 1, name: 'VILLA LUZURIAGA')
City.create(province_id: 1, name: 'VILLA LYCH PUEYRREDON')
City.create(province_id: 1, name: 'VILLA LYNCH ,EST.CNL.FRANCISCO LYNCH')
City.create(province_id: 1, name: 'VILLA MADERO')
City.create(province_id: 1, name: 'VILLA MOLL')
City.create(province_id: 1, name: 'VILLA NUMANCIA')
City.create(province_id: 1, name: 'VILLA OLGA')
City.create(province_id: 1, name: 'VILLA PRONSATO ,EST.CORONEL MALDONADO')
City.create(province_id: 1, name: 'VILLA SABOYA')
City.create(province_id: 1, name: 'VILLA SAUZE')
City.create(province_id: 1, name: 'VILLA SENA')
City.create(province_id: 1, name: 'VILLA SERRA')
City.create(province_id: 1, name: 'VILLALONGA')
City.create(province_id: 1, name: 'VILLANUEVA')
City.create(province_id: 1, name: 'VILLARS')
City.create(province_id: 1, name: 'VIÑA')
City.create(province_id: 1, name: 'VIRREYES ,EST.FACUNDO QUIROGA')
City.create(province_id: 1, name: 'VIVORATA')
City.create(province_id: 1, name: 'VIVORATA')
City.create(province_id: 1, name: 'VOLUNTAD')
City.create(province_id: 1, name: 'VUCETICH, JUAN ,AP.')
City.create(province_id: 1, name: 'WARNES')
City.create(province_id: 1, name: 'WILDE')
City.create(province_id: 1, name: 'YERBAS')
City.create(province_id: 1, name: 'YRAIZOZ')
City.create(province_id: 1, name: 'ZAMUDIO ,AP.')
City.create(province_id: 1, name: 'ZARATE')
City.create(province_id: 1, name: 'ZAVALIA')
City.create(province_id: 1, name: 'ZEBALLOS, ESTANISLAO SEVERO ,EST.')
City.create(province_id: 1, name: 'ZENTENA ,EST.')
City.create(province_id: 1, name: 'ZUBIAURRE')
City.create(province_id: 2, name: 'ADOLFO E. CARRANZA')
City.create(province_id: 2, name: 'AGUA DE LAS PALOMAS')
City.create(province_id: 2, name: 'ALBIGASTA')
City.create(province_id: 2, name: 'ALIJILAN')
City.create(province_id: 2, name: 'ALTA GRACIA')
City.create(province_id: 2, name: 'ALTO DE LA ESQUINA')
City.create(province_id: 2, name: 'ALUMBRERA')
City.create(province_id: 2, name: 'AMADORES')
City.create(province_id: 2, name: 'AMANA')
City.create(province_id: 2, name: 'AMANAO')
City.create(province_id: 2, name: 'AMPOLLA')
City.create(province_id: 2, name: 'ANCASTI')
City.create(province_id: 2, name: 'ANDALGALA')
City.create(province_id: 2, name: 'ANDALHUALA')
City.create(province_id: 2, name: 'ANDALUCA')
