City.create(province_id: 17, name: 'CAÑADA HONDA')
City.create(province_id: 17, name: 'CARPINTERIA')
City.create(province_id: 17, name: 'CASTAÑO NUEVO')
City.create(province_id: 17, name: 'CASTAÑO VIEJO')
City.create(province_id: 17, name: 'CAUCETE')
City.create(province_id: 17, name: 'CHIGUA')
City.create(province_id: 17, name: 'CHUCUMA')
City.create(province_id: 17, name: 'CIENAGUITA')
City.create(province_id: 17, name: 'COCHAGUAL')
City.create(province_id: 17, name: 'COLANGUIL')
City.create(province_id: 17, name: 'COLL')
City.create(province_id: 17, name: 'COLOLA')
City.create(province_id: 17, name: 'CUYO ,EST.')
City.create(province_id: 17, name: 'DIVISORIA')
City.create(province_id: 17, name: 'ECHAGUE, PEDRO ,EST.')
City.create(province_id: 17, name: 'EL BOSQUE')
City.create(province_id: 17, name: 'EL FICAL')
City.create(province_id: 17, name: 'EL SALADO')
City.create(province_id: 17, name: 'ENCON')
City.create(province_id: 17, name: 'GUANACACHE')
City.create(province_id: 17, name: 'HUACO')
City.create(province_id: 17, name: 'HUERTA DE HUACHI')
City.create(province_id: 17, name: 'ICHIGUALASTO')
City.create(province_id: 17, name: 'IGLESIA')
City.create(province_id: 17, name: 'INGENIERO MATIAS G.SANCHEZ ,EST.')
City.create(province_id: 17, name: 'KILOMETRO 810')
City.create(province_id: 17, name: 'KILOMETRO 936 ,EMB.')
City.create(province_id: 17, name: 'LA BEBIDA')
City.create(province_id: 17, name: 'LA CAÑADA')
City.create(province_id: 17, name: 'LA CIENAGA DE CUMILLANGO')
City.create(province_id: 17, name: 'LA HUERTA')
City.create(province_id: 17, name: 'LA ISLA')
City.create(province_id: 17, name: 'LA LAJA')
City.create(province_id: 17, name: 'LA RINCONADA')
City.create(province_id: 17, name: 'LAS CASUARINAS')
City.create(province_id: 17, name: 'LAS CHIMBAS ,AP.')
City.create(province_id: 17, name: 'LAS DELICIAS')
City.create(province_id: 17, name: 'LAS FLORES')
City.create(province_id: 17, name: 'LAS JUNTAS')
City.create(province_id: 17, name: 'LAS LOMITAS ,EST.ALBARDON')
City.create(province_id: 17, name: 'LAS SALINAS ,DV.')
City.create(province_id: 17, name: 'LAS TAPIAS')
City.create(province_id: 17, name: 'LOS BERROS')
City.create(province_id: 17, name: 'LOS PAPAGAYOS')
City.create(province_id: 17, name: 'LOS RINCONES')
City.create(province_id: 17, name: 'LOS VIÑEDOS ,AP.')
City.create(province_id: 17, name: 'MACATACLASTO')
City.create(province_id: 17, name: 'MALIMAN DE ABAJO')
City.create(province_id: 17, name: 'MARAYES')
City.create(province_id: 17, name: 'MARQUESADO')
City.create(province_id: 17, name: 'MATAGUSANOS')
City.create(province_id: 17, name: 'MEDANO DE ORO')
City.create(province_id: 17, name: 'MOGNA')
City.create(province_id: 17, name: 'NIQUIVIL')
City.create(province_id: 17, name: 'NIQUIVIL NUEVO')
City.create(province_id: 17, name: 'NIQUIVIL VIEJO')
City.create(province_id: 17, name: 'NUEVA CASTILLA ,DV.')
City.create(province_id: 17, name: 'ORO, DOMINGO DE ,EST.')
City.create(province_id: 17, name: 'PACHIMOCO')
City.create(province_id: 17, name: 'PAMPA DEL CHAÑAR')
City.create(province_id: 17, name: 'PAMPA VIEJA')
City.create(province_id: 17, name: 'PAMPITA')
City.create(province_id: 17, name: 'PANACAN')
City.create(province_id: 17, name: 'PASLEAM')
City.create(province_id: 17, name: 'PEDERNAL')
City.create(province_id: 17, name: 'PIE DE PALO')
City.create(province_id: 17, name: 'PISMANTA')
City.create(province_id: 17, name: 'POCITO')
City.create(province_id: 17, name: 'PUCHUZUN')
City.create(province_id: 17, name: 'PUENTE NACIONAL ,AP.')
City.create(province_id: 17, name: 'PUNTA DEL AGUA')
City.create(province_id: 17, name: 'PUNTILLA BLANCA')
City.create(province_id: 17, name: 'QUILINQUIL')
City.create(province_id: 17, name: 'QUIROGA, ADAN')
City.create(province_id: 17, name: 'RAMBLON')
City.create(province_id: 17, name: 'RETAMITO')
City.create(province_id: 17, name: 'RIVADAVIA')
City.create(province_id: 17, name: 'RODEO')
City.create(province_id: 17, name: 'SAN AGUSTIN DEL VALLE FERTIL')
City.create(province_id: 17, name: 'SAN JOSE DE JACHAL')
City.create(province_id: 17, name: 'SAN JUAN')
City.create(province_id: 17, name: 'SAN MARTIN ,EST.ANGACO SUD')
City.create(province_id: 17, name: 'SAN ROQUE ,EST.LOS DIAGUITAS')
City.create(province_id: 17, name: 'SANCHEZ DE LORIA')
City.create(province_id: 17, name: 'SANTA LUCIA')
City.create(province_id: 17, name: 'SANTO DOMINGO')
City.create(province_id: 17, name: 'SLA CIENAGA')
City.create(province_id: 17, name: 'SOROCAYENSE')
City.create(province_id: 17, name: 'TALACASTO')
City.create(province_id: 17, name: 'TAMBERIAS')
City.create(province_id: 17, name: 'TOCOTA')
City.create(province_id: 17, name: 'TRINIDAD')
City.create(province_id: 17, name: 'TUCUNUCO')
City.create(province_id: 17, name: 'TUCUNUCO ,EMB.')
City.create(province_id: 17, name: 'TUDCUM')
City.create(province_id: 17, name: 'ULLUN')
City.create(province_id: 17, name: 'USNO')
City.create(province_id: 17, name: 'VALLECITO')
City.create(province_id: 17, name: 'VILLA ABERASTAIN')
City.create(province_id: 17, name: 'VILLA CORRAL')
City.create(province_id: 17, name: 'VILLA DEL SALVADOR')
City.create(province_id: 17, name: 'VILLA INDEPENDENCIA')
City.create(province_id: 17, name: 'VILLA KRAUSE')
City.create(province_id: 17, name: 'VILLA MEDIA AGUA')
City.create(province_id: 17, name: 'VILLA MERCEDES')
City.create(province_id: 17, name: 'VILLA NUEVA')
City.create(province_id: 17, name: 'VILLA PAULA ALBARRACIN DE SARMIENTO')
City.create(province_id: 17, name: 'VILLA PITUIL')
City.create(province_id: 17, name: 'VILLA SAN ISIDRO')
City.create(province_id: 17, name: 'VILLA SANTA ROSA')
City.create(province_id: 17, name: 'YOCA')
City.create(province_id: 17, name: 'ZONDA')
City.create(province_id: 18, name: 'ALGARROBOS GRANDES')
City.create(province_id: 18, name: 'ALTO LINDO')
City.create(province_id: 18, name: 'ALTO PELADO')
City.create(province_id: 18, name: 'ALTO PENCOSO')
City.create(province_id: 18, name: 'ANCHORENA')
City.create(province_id: 18, name: 'ARBOL SOLO')
City.create(province_id: 18, name: 'ARIZONA')
City.create(province_id: 18, name: 'AVANZADA ,EST.')
City.create(province_id: 18, name: 'BAGUAL')
City.create(province_id: 18, name: 'BAJADA NUEVA')
City.create(province_id: 18, name: 'BAJOS HONDOS')
City.create(province_id: 18, name: 'BALCARCE')
City.create(province_id: 18, name: 'BALDE')
City.create(province_id: 18, name: 'BALDE DE AZCURRA')
City.create(province_id: 18, name: 'BALDE DE ESCUDERO')
City.create(province_id: 18, name: 'BALDE DE LOS TORRES')
City.create(province_id: 18, name: 'BALDE DE PUERTAS')
City.create(province_id: 18, name: 'BALDE DE QUINES')
City.create(province_id: 18, name: 'BALDE VIEJO')
City.create(province_id: 18, name: 'BARRANCA COLORADA')
City.create(province_id: 18, name: 'BATAVIA')
City.create(province_id: 18, name: 'BEAZLEY')
City.create(province_id: 18, name: 'BELLA ESTANCIA')
City.create(province_id: 18, name: 'BELLA VISTA')
City.create(province_id: 18, name: 'BUENA ESPERANZA')
City.create(province_id: 18, name: 'CALDENADAS')
City.create(province_id: 18, name: 'CAÑADA ANGOSTA')
City.create(province_id: 18, name: 'CAÑADA HONDA')
City.create(province_id: 18, name: 'CANDELARIA ,EST.LA CANDELARIA')
City.create(province_id: 18, name: 'CANTERAS')
City.create(province_id: 18, name: 'CAROLINA')
City.create(province_id: 18, name: 'CARPINTERIA')
City.create(province_id: 18, name: 'CARPINTERIA')
City.create(province_id: 18, name: 'CAZADOR')
City.create(province_id: 18, name: 'CHALANTA')
City.create(province_id: 18, name: 'CHIMBORAZO')
City.create(province_id: 18, name: 'CHIPISCU')
City.create(province_id: 18, name: 'CHISCHACA ,DV.')
City.create(province_id: 18, name: 'CHISCHAQUITA')
City.create(province_id: 18, name: 'CHOSMES')
City.create(province_id: 18, name: 'COCHEQUINGAN')
City.create(province_id: 18, name: 'COLONIA CALZADA')
City.create(province_id: 18, name: 'COLONIA SANTA VIRGINIA')
City.create(province_id: 18, name: 'COLONIA URDANIZ')
City.create(province_id: 18, name: 'COMANDANTE GRANVILLE')
City.create(province_id: 18, name: 'CONCARAN')
City.create(province_id: 18, name: 'CORONEL ALZOGARAY')
City.create(province_id: 18, name: 'CORONEL SEGOVIA')
City.create(province_id: 18, name: 'CORTADERAS')
City.create(province_id: 18, name: 'CRAMER')
City.create(province_id: 18, name: 'CRUZ DE CAÑA')
City.create(province_id: 18, name: 'CUATRO ESQUINAS')
City.create(province_id: 18, name: 'DARACT, JUSTO')
City.create(province_id: 18, name: 'DIXONVILLE ,EST.FORTIN EL PATRIA')
City.create(province_id: 18, name: 'DONADO')
City.create(province_id: 18, name: 'DONOVAN, DANIEL')
City.create(province_id: 18, name: 'EL AGUILA')
City.create(province_id: 18, name: 'EL AMPARO')
City.create(province_id: 18, name: 'EL CARMEN')
City.create(province_id: 18, name: 'EL CHORRILLO')
City.create(province_id: 18, name: 'EL DURAZNO')
City.create(province_id: 18, name: 'EL HORMIGUERO')
City.create(province_id: 18, name: 'EL MARTILLO')
City.create(province_id: 18, name: 'EL MILAGRO')
City.create(province_id: 18, name: 'EL MOLLE')
City.create(province_id: 18, name: 'EL PORTEZUELO')
City.create(province_id: 18, name: 'EL PORTEZUELO')
City.create(province_id: 18, name: 'EL PORVENIR')
City.create(province_id: 18, name: 'EL RECUERDO')
City.create(province_id: 18, name: 'EL RETAMO')
City.create(province_id: 18, name: 'EL RODEO')
City.create(province_id: 18, name: 'EL SAUCE')
City.create(province_id: 18, name: 'EL VOLCAN')
City.create(province_id: 18, name: 'FORTUNA')
City.create(province_id: 18, name: 'FRAGA')
City.create(province_id: 18, name: 'FRISIA')
City.create(province_id: 18, name: 'GEZ,JUAN W.')
City.create(province_id: 18, name: 'GOMEZ, CASIMIRO')
City.create(province_id: 18, name: 'GORGONTA')
City.create(province_id: 18, name: 'GUANIZUL')
City.create(province_id: 18, name: 'HUEJEDA')
City.create(province_id: 18, name: 'JARILLA')
City.create(province_id: 18, name: 'JORBA, JUAN')
City.create(province_id: 18, name: 'KILOMETRO 14 ,DIV.')
City.create(province_id: 18, name: 'KILOMETRO 731')
City.create(province_id: 18, name: 'KILOMETRO 757')
City.create(province_id: 18, name: 'LA ANGELINA')
City.create(province_id: 18, name: 'LA BAJADA')
City.create(province_id: 18, name: 'LA COCHA')
City.create(province_id: 18, name: 'LA COSTA')
City.create(province_id: 18, name: 'LA ESQUINA')
City.create(province_id: 18, name: 'LA ESTRELLA')
City.create(province_id: 18, name: 'LA FLORIDA')
City.create(province_id: 18, name: 'LA HUERTA')
City.create(province_id: 18, name: 'LA IRENE')
City.create(province_id: 18, name: 'LA MAROMA')
City.create(province_id: 18, name: 'LA MELINA')
City.create(province_id: 18, name: 'LA NELIDA')
City.create(province_id: 18, name: 'LA PAMPA GRANDE')
City.create(province_id: 18, name: 'LA PUNILLA')
City.create(province_id: 18, name: 'LA SEÑA')
City.create(province_id: 18, name: 'LA TOMA')
City.create(province_id: 18, name: 'LA TRANCA')
City.create(province_id: 18, name: 'LA VERDE')
City.create(province_id: 18, name: 'LAFINUR')
City.create(province_id: 18, name: 'LAGUNAS LARGAS')
City.create(province_id: 18, name: 'LAS AGUADAS')
City.create(province_id: 18, name: 'LAS BARRANCAS')
City.create(province_id: 18, name: 'LAS BARRANQUITAS')
City.create(province_id: 18, name: 'LAS CHACRAS')
City.create(province_id: 18, name: 'LAS CHACRAS')
City.create(province_id: 18, name: 'LAS CHIMBAS')
City.create(province_id: 18, name: 'LAS GAMAS')
City.create(province_id: 18, name: 'LAS ISLETAS')
City.create(province_id: 18, name: 'LAS LOMITAS')
City.create(province_id: 18, name: 'LAS PALOMAS')
City.create(province_id: 18, name: 'LAS VERTIENTES')
City.create(province_id: 18, name: 'LAVAISSE')
City.create(province_id: 18, name: 'LIBERTADOR GENERAL SAN MARTIN')
City.create(province_id: 18, name: 'LLERENA, JUAN')
City.create(province_id: 18, name: 'LOBOS, ELEODORO')
City.create(province_id: 18, name: 'LOMAS BLANCAS')
City.create(province_id: 18, name: 'LOMAS BLANCAS')
City.create(province_id: 18, name: 'LOS ARGUELLOS')
City.create(province_id: 18, name: 'LOS CERRILLOS')
City.create(province_id: 18, name: 'LOS CERRILLOS')
City.create(province_id: 18, name: 'LOS COROS')
City.create(province_id: 18, name: 'LOS MOLLES')
City.create(province_id: 18, name: 'LOS PUQUIOS')
City.create(province_id: 18, name: 'LOYOLA, MARTIN DE')
City.create(province_id: 18, name: 'LUJAN')
City.create(province_id: 18, name: 'LUNA, LIBORIO')
City.create(province_id: 18, name: 'MANANTIALES')
City.create(province_id: 18, name: 'MERCEDES ,EST.VILLA MERCEDES')
City.create(province_id: 18, name: 'MERLO')
City.create(province_id: 18, name: 'MOSMOTA')
City.create(province_id: 18, name: 'NAHUEL MAPA')
City.create(province_id: 18, name: 'NASCHEL')
City.create(province_id: 18, name: 'NAVIA')
City.create(province_id: 18, name: 'NIKIZANGA ,DV.')
City.create(province_id: 18, name: 'NUEVA CONSTITUCION')
City.create(province_id: 18, name: 'NUEVA ESCOCIA')
City.create(province_id: 18, name: 'NUEVA GALIA')
City.create(province_id: 18, name: 'OJO DEL RIO')
City.create(province_id: 18, name: 'PAPAGAYO')
City.create(province_id: 18, name: 'PASO DEL REY')
City.create(province_id: 18, name: 'PASO GRANDE')
City.create(province_id: 18, name: 'PEDERNERA')
City.create(province_id: 18, name: 'PESCADORES')
City.create(province_id: 18, name: 'POLLEDO')
City.create(province_id: 18, name: 'POTRERO DE LOS FUNES')
City.create(province_id: 18, name: 'POZO DEL CARRIL')
City.create(province_id: 18, name: 'POZO DEL TALA')
City.create(province_id: 18, name: 'QUEBRADA DE LOS CONDORES')
City.create(province_id: 18, name: 'QUINES')
City.create(province_id: 18, name: 'RANQUELCO')
City.create(province_id: 18, name: 'RIO QUINTO')
City.create(province_id: 18, name: 'ROSARIO')
City.create(province_id: 18, name: 'SALADILLO')
City.create(province_id: 18, name: 'SALINAS DEL BEBEDERO')
City.create(province_id: 18, name: 'SAN AMBROSIO')
City.create(province_id: 18, name: 'SAN ANTONIO')
City.create(province_id: 18, name: 'SAN EDUARDO')
City.create(province_id: 18, name: 'SAN FELIPE')
City.create(province_id: 18, name: 'SAN FRANCISCO DEL MONTE DE ORO')
City.create(province_id: 18, name: 'SAN GERONIMO')
City.create(province_id: 18, name: 'SAN ISIDRO')
City.create(province_id: 18, name: 'SAN ISIDRO')
City.create(province_id: 18, name: 'SAN JOSE DEL MORRO')
City.create(province_id: 18, name: 'SAN LUIS')
City.create(province_id: 18, name: 'SAN MARTIN DEL ALTO NEGRO')
City.create(province_id: 18, name: 'SAN MIGUEL')
City.create(province_id: 18, name: 'SAN PABLO')
City.create(province_id: 18, name: 'SAN PEDRO')
City.create(province_id: 18, name: 'SAN ROQUE')
City.create(province_id: 18, name: 'SANTA ROSA')
City.create(province_id: 18, name: 'SANTA ROSA ,EST.ADOLFO RODRIGUEZ ZAA')
City.create(province_id: 18, name: 'SANTA TERESA')
City.create(province_id: 18, name: 'SOCOSCORA')
City.create(province_id: 18, name: 'SOVEN')
City.create(province_id: 18, name: 'SUYUQUE')
City.create(province_id: 18, name: 'SUYUQUE NUEVO')
City.create(province_id: 18, name: 'TALITA')
City.create(province_id: 18, name: 'TALITA')
City.create(province_id: 18, name: 'TILISARAO')
City.create(province_id: 18, name: 'TORO NEGRO')
City.create(province_id: 18, name: 'TOSCAL')
City.create(province_id: 18, name: 'TRAPICHE')
City.create(province_id: 18, name: 'TRAVESIA')
City.create(province_id: 18, name: 'TRES AMIGOS')
City.create(province_id: 18, name: 'UNION')
City.create(province_id: 18, name: 'USIYAL')
City.create(province_id: 18, name: 'VARELA')
City.create(province_id: 18, name: 'VILLA DE PRAGA')
City.create(province_id: 18, name: 'VILLA DEL CARMEN')
City.create(province_id: 18, name: 'VILLA GENERAL ROCA')
City.create(province_id: 18, name: 'VILLA LA QUEBRADA')
City.create(province_id: 18, name: 'VILLA LARCA')
City.create(province_id: 18, name: 'VILLA REYNOLDS')
City.create(province_id: 18, name: 'YRIGOYEN, HIPOLITO')
City.create(province_id: 18, name: 'ZANJITAS')
City.create(province_id: 19, name: '28 DE NOVIEMBRE')
City.create(province_id: 19, name: 'AGUADA ALEGRE')
City.create(province_id: 19, name: 'AGUADA ESCONDIDA')
City.create(province_id: 19, name: 'AGUADA GRANDE')
City.create(province_id: 19, name: 'ALMA GAUCHA')
City.create(province_id: 19, name: 'ALQUINTA')
City.create(province_id: 19, name: 'ANTONIO DE BIEDMA')
City.create(province_id: 19, name: 'ARISTIZABAL')
City.create(province_id: 19, name: 'BAHIA LAURA')
City.create(province_id: 19, name: 'BAHIA OSO MARINO')
City.create(province_id: 19, name: 'BAJO DE LOS CARACOLES')
City.create(province_id: 19, name: 'BAJO FUEGO')
City.create(province_id: 19, name: 'BAJO PIEDRA')
City.create(province_id: 19, name: 'BELLA VISTA')
City.create(province_id: 19, name: 'BELLA VISTA')
City.create(province_id: 19, name: 'BELLA VISTA ,EST.')
City.create(province_id: 19, name: 'CABO BLANCO')
City.create(province_id: 19, name: 'CABO BUEN TIEMPO')
City.create(province_id: 19, name: 'CABO VIRGENES')
City.create(province_id: 19, name: 'CALAFATE')
City.create(province_id: 19, name: 'CALETA OLIVIA')
City.create(province_id: 19, name: 'CAÑADON 11 DE SEPTIEMBRE')
City.create(province_id: 19, name: 'CAÑADON SECO')
City.create(province_id: 19, name: 'CANCHA CARRERAS')
City.create(province_id: 19, name: 'CAPITAN EYROA ,EST.')
City.create(province_id: 19, name: 'CERRO BLANCO ,EMB.')
City.create(province_id: 19, name: 'COLONIA PERITO MORENO')
City.create(province_id: 19, name: 'COMANDANTE LUIS PIEDRA BUENA')
City.create(province_id: 19, name: 'COMANDANTE LUIS PIEDRA BUENA')
City.create(province_id: 19, name: 'COY AIKE')
City.create(province_id: 19, name: 'DE BIEDMA, ANTONIO')
City.create(province_id: 19, name: 'DUFOUR, JULIA ,EST.')
City.create(province_id: 19, name: 'EL CALAFATE')
City.create(province_id: 19, name: 'EL CERRITO')
City.create(province_id: 19, name: 'EL CONDOR')
City.create(province_id: 19, name: 'EL PLUMA')
City.create(province_id: 19, name: 'EL PORTEZUELO')
City.create(province_id: 19, name: 'EL SALADO')
City.create(province_id: 19, name: 'EL TURBIO ,EST.GOBERNADOR MEYER')
City.create(province_id: 19, name: 'EL VOLCAN')
City.create(province_id: 19, name: 'EL ZURDO ,EST.')
City.create(province_id: 19, name: 'ESPERANZA')
City.create(province_id: 19, name: 'FITZ ROY')
City.create(province_id: 19, name: 'FLECHA NEGRA')
City.create(province_id: 19, name: 'FLORIDA NEGRA')
City.create(province_id: 19, name: 'FUENTES DEL COYLE')
City.create(province_id: 19, name: 'FUHR, CHARLES')
City.create(province_id: 19, name: 'GENDARME BARRETO')
City.create(province_id: 19, name: 'GOBERNADOR GREGORES')
City.create(province_id: 19, name: 'GOBERNADOR LISTA ,EST.')
City.create(province_id: 19, name: 'GOBERNADOR MAYER')
City.create(province_id: 19, name: 'GOBERNADOR MOYANO')
City.create(province_id: 19, name: 'GOBERNADOR MOYANO ,EST.')
City.create(province_id: 19, name: 'GUER AIKE')
City.create(province_id: 19, name: 'HILL STATION')
City.create(province_id: 19, name: 'JARAMILLO')
City.create(province_id: 19, name: 'KILOMETRO 199 ,DV.')
City.create(province_id: 19, name: 'KOLUEL KAYKE')
City.create(province_id: 19, name: 'LA ARAGONESA')
City.create(province_id: 19, name: 'LA MARIA')
City.create(province_id: 19, name: 'LAGO CARDIEL')
City.create(province_id: 19, name: 'LAGO POSADAS')
City.create(province_id: 19, name: 'LAGO SAN MARTIN')
City.create(province_id: 19, name: 'LAGO VIEDMA')
City.create(province_id: 19, name: 'LAGUNA GRANDE')
City.create(province_id: 19, name: 'LAI AIKE')
City.create(province_id: 19, name: 'LAS HERAS ,EST.COLONIA LAS HERAS')
City.create(province_id: 19, name: 'LAS TRES HERMANAS')
City.create(province_id: 19, name: 'LISTA, RAMON ,EST.')
City.create(province_id: 19, name: 'LOS ANTIGUOS')
City.create(province_id: 19, name: 'LOS MONOS')
City.create(province_id: 19, name: 'MATA AMARILLA')
City.create(province_id: 19, name: 'MATA GRANDE')
City.create(province_id: 19, name: 'MAZARREDO')
City.create(province_id: 19, name: 'MINERALES ,EST.')
City.create(province_id: 19, name: 'MONTE AYMOND')
City.create(province_id: 19, name: 'MONTE DINERO')
City.create(province_id: 19, name: 'MONTE LEON')
City.create(province_id: 19, name: 'PAMPA ALTA ,EMB.')
City.create(province_id: 19, name: 'PASO GREGORES')
City.create(province_id: 19, name: 'PASO RODOLFO ROBALLOS')
City.create(province_id: 19, name: 'PERITO MORENO')
City.create(province_id: 19, name: 'PICO TRUNCADO')
City.create(province_id: 19, name: 'PIEDRA CLAVADA ,EST.')
City.create(province_id: 19, name: 'PUERTO BANDERA')
City.create(province_id: 19, name: 'PUERTO COIG')
City.create(province_id: 19, name: 'PUERTO DESEADO')
City.create(province_id: 19, name: 'PUERTO SAN JULIAN')
City.create(province_id: 19, name: 'PUERTO SANTA CRUZ')
City.create(province_id: 19, name: 'RINCON')
City.create(province_id: 19, name: 'RIO CHICO')
City.create(province_id: 19, name: 'RIO GALLEGOS')
City.create(province_id: 19, name: 'RIO TURBIO')
City.create(province_id: 19, name: 'TAMEL AIKE')
City.create(province_id: 19, name: 'TAPI AIKE')
City.create(province_id: 19, name: 'TEHUELCHES ,AP.')
City.create(province_id: 19, name: 'TELLIER')
City.create(province_id: 19, name: 'TRES CERROS')
City.create(province_id: 19, name: 'TRES LAGOS')
City.create(province_id: 19, name: 'TUCU TUCU')
City.create(province_id: 20, name: 'AARON CASTELLANOS')
City.create(province_id: 20, name: 'ACEBAL')
City.create(province_id: 20, name: 'ADELA')
City.create(province_id: 20, name: 'AERO CLUB ARGENTINO')
City.create(province_id: 20, name: 'ALBARELLOS')
City.create(province_id: 20, name: 'ALCORTA')
City.create(province_id: 20, name: 'ALDAO')
City.create(province_id: 20, name: 'ALEJANDRA')
City.create(province_id: 20, name: 'ALTO VERDE')
City.create(province_id: 20, name: 'ALVAREZ')
City.create(province_id: 20, name: 'ALVEAR')
City.create(province_id: 20, name: 'AMBROSETTI')
City.create(province_id: 20, name: 'AMENABAR')
City.create(province_id: 20, name: 'ANDINO')
City.create(province_id: 20, name: 'ANGEL GALLARDO')
City.create(province_id: 20, name: 'ANGELICA')
City.create(province_id: 20, name: 'ANTARTIDA ARGENTINA ,EST.')
City.create(province_id: 20, name: 'ANTONIO PINI')
City.create(province_id: 20, name: 'AREQUITO')
City.create(province_id: 20, name: 'ARIJON ,DV.')
City.create(province_id: 20, name: 'ARMINDA')
City.create(province_id: 20, name: 'ARMSTRONG')
City.create(province_id: 20, name: 'AROCENA')
City.create(province_id: 20, name: 'AROMOS ,EST.')
City.create(province_id: 20, name: 'ARRASCAETA ,AP.')
City.create(province_id: 20, name: 'ARROYO AGUIAR ,EST.')
City.create(province_id: 20, name: 'ARROYO CEIBAL')
City.create(province_id: 20, name: 'ARROYO DEL REY')
City.create(province_id: 20, name: 'ARROYO LEYES')
City.create(province_id: 20, name: 'ARRUFO')
City.create(province_id: 20, name: 'ARTEAGA')
City.create(province_id: 20, name: 'ASCOCHINGAS ,DV.')
City.create(province_id: 20, name: 'ATALIVA')
City.create(province_id: 20, name: 'AURELIA')
City.create(province_id: 20, name: 'AURELIA NORTE')
City.create(province_id: 20, name: 'AURELIA SUR')
City.create(province_id: 20, name: 'AVELLANEDA ,EST.EWALD')
City.create(province_id: 20, name: 'BARRANCAS')
City.create(province_id: 20, name: 'BAUER Y SIGEL')
City.create(province_id: 20, name: 'BERABEVU')
City.create(province_id: 20, name: 'BERNA')
City.create(province_id: 20, name: 'BERNARDO DE IRIGOYEN')
City.create(province_id: 20, name: 'BIGAND')
City.create(province_id: 20, name: 'BOMBAL')
City.create(province_id: 20, name: 'BOUQUET')
City.create(province_id: 20, name: 'BUSTINZA')
City.create(province_id: 20, name: 'CABAL')
City.create(province_id: 20, name: 'CACIQUE ARIACAIQUIN')
City.create(province_id: 20, name: 'CAFFERATA')
City.create(province_id: 20, name: 'CALCHAQUI')
City.create(province_id: 20, name: 'CAMPO GARAY')
City.create(province_id: 20, name: 'CAMPO REDONDO')
City.create(province_id: 20, name: 'CAÑADA DE GOMEZ')
City.create(province_id: 20, name: 'CAÑADA DEL UCLE')
City.create(province_id: 20, name: 'CAÑADA OMBU')
City.create(province_id: 20, name: 'CAÑADA RICA ,EST.')
City.create(province_id: 20, name: 'CAÑADA ROSQUIN')
City.create(province_id: 20, name: 'CAPITAN BERMUDEZ')
City.create(province_id: 20, name: 'CAPIVARA')
City.create(province_id: 20, name: 'CARAGUATAY')
City.create(province_id: 20, name: 'CARCARAÑA')
City.create(province_id: 20, name: 'CARMEN')
City.create(province_id: 20, name: 'CARRERAS')
City.create(province_id: 20, name: 'CARRIZALES ,EST.CLARKE')
City.create(province_id: 20, name: 'CASABLANCA ,EST.')
City.create(province_id: 20, name: 'CASALEGNO')
City.create(province_id: 20, name: 'CASAS')
City.create(province_id: 20, name: 'CASILDA')
City.create(province_id: 20, name: 'CASTELAR')
City.create(province_id: 20, name: 'CASTELLANOS')
City.create(province_id: 20, name: 'CASTELLANOS, AARON ,EST.CASTELLANOS')
City.create(province_id: 20, name: 'CAVOUR')
City.create(province_id: 20, name: 'CAYASTA')
City.create(province_id: 20, name: 'CAYASTACITO')
City.create(province_id: 20, name: 'CENTENO')
City.create(province_id: 20, name: 'CERES')
City.create(province_id: 20, name: 'CERRITOS')
City.create(province_id: 20, name: 'CHABAS')
City.create(province_id: 20, name: 'CHAÑAR LADEADO')
City.create(province_id: 20, name: 'CHAPUY')
City.create(province_id: 20, name: 'CHATEAUBRIAND ,EST.MURPHY')
City.create(province_id: 20, name: 'CHOVET')
City.create(province_id: 20, name: 'CHRISTOPHERSEN')
City.create(province_id: 20, name: 'CLASON')
City.create(province_id: 20, name: 'CLUCELLAS')
City.create(province_id: 20, name: 'CLUCELLAS ,EST.')
City.create(province_id: 20, name: 'COLASTINE')
City.create(province_id: 20, name: 'COLMENA')
City.create(province_id: 20, name: 'COLONIA ALDAO')
City.create(province_id: 20, name: 'COLONIA ANA')
City.create(province_id: 20, name: 'COLONIA ANGELONI')
City.create(province_id: 20, name: 'COLONIA BELGRANO')
City.create(province_id: 20, name: 'COLONIA BOSSI')
City.create(province_id: 20, name: 'COLONIA CELLO')
City.create(province_id: 20, name: 'COLONIA DOLORES')
City.create(province_id: 20, name: 'COLONIA DOLORES')
City.create(province_id: 20, name: 'COLONIA EL TOBA')
City.create(province_id: 20, name: 'COLONIA ELLA')
City.create(province_id: 20, name: 'COLONIA LA CAMILA')
City.create(province_id: 20, name: 'COLONIA MASCIAS')
City.create(province_id: 20, name: 'COLONIA MEDICI')
City.create(province_id: 20, name: 'COLONIA RAQUEL')
City.create(province_id: 20, name: 'COLONIA ROSA')
City.create(province_id: 20, name: 'COLONIA SILVA ,EST.ABIPONES')
City.create(province_id: 20, name: 'COLONIA TACURALES')
City.create(province_id: 20, name: 'CONSTANZA')
City.create(province_id: 20, name: 'CONSTITUYENTES')
City.create(province_id: 20, name: 'CORONDA')
City.create(province_id: 20, name: 'CORONEL ARNOLD')
City.create(province_id: 20, name: 'CORONEL BOGADO')
City.create(province_id: 20, name: 'CORONEL FRAGA')
City.create(province_id: 20, name: 'CORONEL RODRIGUEZ')
City.create(province_id: 20, name: 'CORONEL ROSETTI')
City.create(province_id: 20, name: 'CORREA')
City.create(province_id: 20, name: 'CRISPI')
City.create(province_id: 20, name: 'CULLEN ,EST.')
City.create(province_id: 20, name: 'CULULU')
City.create(province_id: 20, name: 'CURUPAITY')
City.create(province_id: 20, name: 'DENIS, GREGORIA PEREZ DE ,EST.EL NOCHERO')
City.create(province_id: 20, name: 'DIAZ')
City.create(province_id: 20, name: 'DIEGO DE ALVEAR')
City.create(province_id: 20, name: 'DOCTOR BARROS PAZOS')
City.create(province_id: 20, name: 'DURHAM ,AP.')
City.create(province_id: 20, name: 'ECHEVERRIA, VICENTE A.')
City.create(province_id: 20, name: 'EDISON, TOMAS A.')
City.create(province_id: 20, name: 'EGUSQUIZA')
City.create(province_id: 20, name: 'EL BAYO')
City.create(province_id: 20, name: 'EL CANTOR ,EST.')
City.create(province_id: 20, name: 'EL JARDIN')
City.create(province_id: 20, name: 'EL LAUREL')
City.create(province_id: 20, name: 'EL RABON')
City.create(province_id: 20, name: 'EL SOMBRERITO ,EST.PAUL GROUSSAC')
City.create(province_id: 20, name: 'EL TREBOL')
City.create(province_id: 20, name: 'ELISA')
City.create(province_id: 20, name: 'ELORTONDO')
City.create(province_id: 20, name: 'EMILIA')
City.create(province_id: 20, name: 'EMPALME VILLA CONSTITUCION')
City.create(province_id: 20, name: 'ESCALADA, MARCELINO')
City.create(province_id: 20, name: 'ESCALADA, MIGUEL')
City.create(province_id: 20, name: 'ESMERALDA')
City.create(province_id: 20, name: 'ESPERANZA')
City.create(province_id: 20, name: 'ESPIN')
City.create(province_id: 20, name: 'ESTHER')
City.create(province_id: 20, name: 'ESTRADA, JOSE M.')
City.create(province_id: 20, name: 'EUSEBIA')
City.create(province_id: 20, name: 'FELICIA')
City.create(province_id: 20, name: 'FIGHIERA')
City.create(province_id: 20, name: 'FIRMAT')
City.create(province_id: 20, name: 'FLOR DE ORO')
City.create(province_id: 20, name: 'FLORENCIA')
City.create(province_id: 20, name: 'FLORIDA')
City.create(province_id: 20, name: 'FORTIN ATAHUALPA')
City.create(province_id: 20, name: 'FRANCK')
City.create(province_id: 20, name: 'FRAY LUIS BELTRAN ,EST.TTE.CNL.L.BELTRAN')
City.create(province_id: 20, name: 'FRONTERA')
City.create(province_id: 20, name: 'FUENTES')
City.create(province_id: 20, name: 'FUNES')
City.create(province_id: 20, name: 'GALISTEO')
City.create(province_id: 20, name: 'GALLARDO, ANGEL ,EMB.')
City.create(province_id: 20, name: 'GALVEZ')
City.create(province_id: 20, name: 'GARABATO')
City.create(province_id: 20, name: 'GARIBALDI')
City.create(province_id: 20, name: 'GENERAL GELLY')
City.create(province_id: 20, name: 'GENERAL LAGOS')
City.create(province_id: 20, name: 'GESSLER')
City.create(province_id: 20, name: 'GOBERNADOR CANDIOTI')
City.create(province_id: 20, name: 'GOBERNADOR CRESPO')
City.create(province_id: 20, name: 'GODEKEN')
City.create(province_id: 20, name: 'GODOY')
City.create(province_id: 20, name: 'GOLONDRINA')
City.create(province_id: 20, name: 'GOMEZ CELLO, PEDRO')
City.create(province_id: 20, name: 'GRANADERO BAIGORRIA')
City.create(province_id: 20, name: 'GRANADERO BLAS BARGAS ,AP.')
City.create(province_id: 20, name: 'GRANADEROS ,PDA.')
City.create(province_id: 20, name: 'GRANEROS ,EST.')
City.create(province_id: 20, name: 'GRUTLY')
City.create(province_id: 20, name: 'GRUTLY NORTE')
City.create(province_id: 20, name: 'GUADALUPE ,EST.')
City.create(province_id: 20, name: 'GUADALUPE NORTE')
City.create(province_id: 20, name: 'GUASUNCHO')
City.create(province_id: 20, name: 'GUAYCURU')
City.create(province_id: 20, name: 'HANSEN')
City.create(province_id: 20, name: 'HELVECIA')
City.create(province_id: 20, name: 'HERSILIA')
City.create(province_id: 20, name: 'HUANQUEROS')
City.create(province_id: 20, name: 'HUGENTOBLER')
City.create(province_id: 20, name: 'HUGES')
City.create(province_id: 20, name: 'HUMBOLDT')
City.create(province_id: 20, name: 'HUME ,EST.EL GAUCHO')
City.create(province_id: 20, name: 'IBARLUCEA')
City.create(province_id: 20, name: 'INDEPENDENCIA')
City.create(province_id: 20, name: 'INGENIERO BOASI')
City.create(province_id: 20, name: 'INGENIERO CHANOURDIE')
City.create(province_id: 20, name: 'INTIYACO')
City.create(province_id: 20, name: 'IRIGOYEN')
City.create(province_id: 20, name: 'IRIGOYEN, BERNARDO DE')
City.create(province_id: 20, name: 'IRIONDO')
City.create(province_id: 20, name: 'ITURRASPE')
City.create(province_id: 20, name: 'JOSEFINA')
City.create(province_id: 20, name: 'JUNCAL')
City.create(province_id: 20, name: 'KILOMETR 465 ,EST.')
City.create(province_id: 20, name: 'KILOMETRO 17 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 187 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 213 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 320')
City.create(province_id: 20, name: 'KILOMETRO 392 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 403 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 405 ,EST.')
City.create(province_id: 20, name: 'KILOMETRO 408 ,AP.')
City.create(province_id: 20, name: 'KILOMETRO 41 ,AP.')
City.create(province_id: 20, name: 'KILOMETRO 41 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 443 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 468 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 483 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 501 ,EMB.')
City.create(province_id: 20, name: 'KILOMETRO 85 ,AP.')
City.create(province_id: 20, name: 'KILOMETRO 9 ,AP.')
City.create(province_id: 20, name: 'LA BLANCA CENTRAL')
City.create(province_id: 20, name: 'LA BRAVA')
City.create(province_id: 20, name: 'LA CABRAL')
City.create(province_id: 20, name: 'LA CALIFORNIA')
City.create(province_id: 20, name: 'LA CHISPA')
City.create(province_id: 20, name: 'LA CRIOLLA ,EST.CAÑADITA')
City.create(province_id: 20, name: 'LA GALLARETA')
City.create(province_id: 20, name: 'LA GUARDIA')
City.create(province_id: 20, name: 'LA LUCILA ,EST.LUCILA')
City.create(province_id: 20, name: 'LA PELADA')
City.create(province_id: 20, name: 'LA PENCA Y CARAGUATA')
City.create(province_id: 20, name: 'LA RESERVA')
City.create(province_id: 20, name: 'LA RUBIA')
City.create(province_id: 20, name: 'LA VANGUARDIA')
City.create(province_id: 20, name: 'LA ZULEMA')
City.create(province_id: 20, name: 'LABORDEBOY')
City.create(province_id: 20, name: 'LAGUNA PAIVA')
City.create(province_id: 20, name: 'LANDETA')
City.create(province_id: 20, name: 'LANTERI')
City.create(province_id: 20, name: 'LARGUIA')
City.create(province_id: 20, name: 'LARRECHEA')
City.create(province_id: 20, name: 'LAS AVISPAS')
City.create(province_id: 20, name: 'LAS BANDURRIAS')
City.create(province_id: 20, name: 'LAS CAÑAS')
City.create(province_id: 20, name: 'LAS FLORES ,EMB.')
City.create(province_id: 20, name: 'LAS GAMAS')
City.create(province_id: 20, name: 'LAS GRAZAS')
City.create(province_id: 20, name: 'LAS PALMERAS')
City.create(province_id: 20, name: 'LAS PAREJAS')
City.create(province_id: 20, name: 'LAS PETACAS')
City.create(province_id: 20, name: 'LAS ROSAS')
City.create(province_id: 20, name: 'LAS TOSCAS')
City.create(province_id: 20, name: 'LAS TROJAS ,EST.')
City.create(province_id: 20, name: 'LAS TUNAS')
City.create(province_id: 20, name: 'LAZZARINO')
City.create(province_id: 20, name: 'LEHMANN')
City.create(province_id: 20, name: 'LEIVA, LUCIANO')
City.create(province_id: 20, name: 'LLAMBI CAMPBELL')
City.create(province_id: 20, name: 'LOGROÑO')
City.create(province_id: 20, name: 'LOMA ALTA')
City.create(province_id: 20, name: 'LOPEZ ,EST.SAN MARTIN DE TOURS')
City.create(province_id: 20, name: 'LOPEZ, LUCIO V.')
City.create(province_id: 20, name: 'LOS AMORES')
City.create(province_id: 20, name: 'LOS CARDOS')
City.create(province_id: 20, name: 'LOS CERRILLOS')
City.create(province_id: 20, name: 'LOS CHARABONES ,EMB.')
City.create(province_id: 20, name: 'LOS MOLINOS')
City.create(province_id: 20, name: 'LOS NOGALES')
City.create(province_id: 20, name: 'LOS QUIRQUINCHOS')
City.create(province_id: 20, name: 'LOS SEMBRADOS')
City.create(province_id: 20, name: 'LOS TABANOS ,EMB.')
City.create(province_id: 20, name: 'LUDUEÑA ,EST.')
City.create(province_id: 20, name: 'MACIEL')
City.create(province_id: 20, name: 'MAGGIOLO')
City.create(province_id: 20, name: 'MALABRIGO')
City.create(province_id: 20, name: 'MANUCHO')
City.create(province_id: 20, name: 'MARGARITA')
City.create(province_id: 20, name: 'MARIA EUGENIA')
City.create(province_id: 20, name: 'MARIA JUANA')
City.create(province_id: 20, name: 'MARIA SUSANA')
City.create(province_id: 20, name: 'MARIA TERESA')
City.create(province_id: 20, name: 'MATILDE')
City.create(province_id: 20, name: 'MAUA')
City.create(province_id: 20, name: 'MELINCUE')
City.create(province_id: 20, name: 'MERCEDITAS')
City.create(province_id: 20, name: 'MOCOVI')
City.create(province_id: 20, name: 'MOLINA, JUAN B.')
City.create(province_id: 20, name: 'MOLINAS, NICANOR E.')
City.create(province_id: 20, name: 'MONIGOTES')
City.create(province_id: 20, name: 'MONJE')
City.create(province_id: 20, name: 'MONTE FLORES')
City.create(province_id: 20, name: 'MONTE VERA')
City.create(province_id: 20, name: 'MONTEFIORE')
City.create(province_id: 20, name: 'MONTES DE OCA')
City.create(province_id: 20, name: 'MOUSSY')
City.create(province_id: 20, name: 'ÑANDUCITA')
City.create(province_id: 20, name: 'NARE')
City.create(province_id: 20, name: 'NELSON')
City.create(province_id: 20, name: 'NUEVA ITALIA')
City.create(province_id: 20, name: 'NUEVA LEHMANN')
City.create(province_id: 20, name: 'NUEVO ALBERDI ,EST.')
City.create(province_id: 20, name: 'NUEVO TORINO')
City.create(province_id: 20, name: 'OGILVIE')
City.create(province_id: 20, name: 'OLIVEROS')
City.create(province_id: 20, name: 'OMBU')
City.create(province_id: 20, name: 'OROÑO')
City.create(province_id: 20, name: 'PALACIOS')
City.create(province_id: 20, name: 'PALACIOS, LUIS ,EST.LA SALADA')
City.create(province_id: 20, name: 'PAVON')
City.create(province_id: 20, name: 'PAVON ARRIBA')
City.create(province_id: 20, name: 'PAZ, FRANCISCO')
City.create(province_id: 20, name: 'PAZ, MAXIMO ,EST.PAZ')
City.create(province_id: 20, name: 'PELLEGRINI, CARLOS')
City.create(province_id: 20, name: 'PEREYRA, ZENON')
City.create(province_id: 20, name: 'PEREZ')
City.create(province_id: 20, name: 'PEYRANO')
City.create(province_id: 20, name: 'PIAMONTE')
City.create(province_id: 20, name: 'PILAR')
City.create(province_id: 20, name: 'PINI, ANTONIO')
City.create(province_id: 20, name: 'PINO DE SAN LORENZO ,EST.')
City.create(province_id: 20, name: 'PIQUETE')
City.create(province_id: 20, name: 'POMPEYA ,AP.')
City.create(province_id: 20, name: 'PORTUGALETTE')
City.create(province_id: 20, name: 'POZO BORRADO')
City.create(province_id: 20, name: 'PRESIDENTE ROCA')
City.create(province_id: 20, name: 'PROGRESO')
City.create(province_id: 20, name: 'PROVIDENCIA')
City.create(province_id: 20, name: 'PUEBLO ANDINO')
City.create(province_id: 20, name: 'PUEBLO MARINI')
City.create(province_id: 20, name: 'PUEBLO MUÑOZ ,EST.BERNARD')
City.create(province_id: 20, name: 'PUEBLO NUEVO')
City.create(province_id: 20, name: 'PUERTO GABOTO')
City.create(province_id: 20, name: 'PUERTO GENERAL SAN MARTIN')
City.create(province_id: 20, name: 'PUERTO OCAMPO')
City.create(province_id: 20, name: 'PUERTO PIRACUACITO')
City.create(province_id: 20, name: 'PUERTO RECONQUISTA')
City.create(province_id: 20, name: 'PUERTO SAN LORENZO')
City.create(province_id: 20, name: 'PUJATO')
City.create(province_id: 20, name: 'RAFAELA')
City.create(province_id: 20, name: 'RAMAYON')
City.create(province_id: 20, name: 'RAMONA')
City.create(province_id: 20, name: 'RAMS, ESTEBAN')
City.create(province_id: 20, name: 'RASTREADOR FOURNIER ,EST.')
City.create(province_id: 20, name: 'RECONQUISTA')
City.create(province_id: 20, name: 'RECREO')
City.create(province_id: 20, name: 'RICARDONE')
City.create(province_id: 20, name: 'RINCON DEL POTRERO')
City.create(province_id: 20, name: 'RINCON DEL QUEBRACHO ,EMB.')
City.create(province_id: 20, name: 'ROLDAN')
City.create(province_id: 20, name: 'ROMANG')
City.create(province_id: 20, name: 'ROSARIO')
City.create(province_id: 20, name: 'RUEDA')
City.create(province_id: 20, name: 'RUFINO')
City.create(province_id: 20, name: 'RUNCIMAN')
City.create(province_id: 20, name: 'SA PEREYRA')
City.create(province_id: 20, name: 'SAAVEDRA, MARIANO')
City.create(province_id: 20, name: 'SAGUIER')
City.create(province_id: 20, name: 'SALADERO M.CABAL')
City.create(province_id: 20, name: 'SALTO GRANDE')
City.create(province_id: 20, name: 'SAN ANTONIO')
City.create(province_id: 20, name: 'SAN ANTONIO DE OBLIGADO')
City.create(province_id: 20, name: 'SAN BERNARDO')
City.create(province_id: 20, name: 'SAN BERNARDO')
City.create(province_id: 20, name: 'SAN CARLOS ,EMP.')
City.create(province_id: 20, name: 'SAN CARLOS CENTRO')
City.create(province_id: 20, name: 'SAN CARLOS NORTE')
City.create(province_id: 20, name: 'SAN CARLOS SUR')
City.create(province_id: 20, name: 'SAN CRISTOBAL')
City.create(province_id: 20, name: 'SAN EDUARDO')
City.create(province_id: 20, name: 'SAN ESTANISLAO')
City.create(province_id: 20, name: 'SAN EUGENIO')
City.create(province_id: 20, name: 'SAN FABIAN')
City.create(province_id: 20, name: 'SAN FRANCISCO DE SANTA FE')
City.create(province_id: 20, name: 'SAN GENARO')
City.create(province_id: 20, name: 'SAN GENARO NORTE')
City.create(province_id: 20, name: 'SAN GREGORIO')
City.create(province_id: 20, name: 'SAN GUILLERMO')
City.create(province_id: 20, name: 'SAN JAVIER')
City.create(province_id: 20, name: 'SAN JERONIMO DEL SAUCE')
City.create(province_id: 20, name: 'SAN JERONIMO NORTE')
City.create(province_id: 20, name: 'SAN JERONIMO SUR')
City.create(province_id: 20, name: 'SAN JORGE')
City.create(province_id: 20, name: 'SAN JOSE DE LA ESQUINA')
City.create(province_id: 20, name: 'SAN JOSE DEL RINCON')
City.create(province_id: 20, name: 'SAN JUSTO')
City.create(province_id: 20, name: 'SAN LORENZO')
City.create(province_id: 20, name: 'SAN MARTIN DE LAS ESCOBAS')
City.create(province_id: 20, name: 'SAN MARTIN NORTE')
City.create(province_id: 20, name: 'SAN PEDRO')
City.create(province_id: 20, name: 'SAN RICARDO')
City.create(province_id: 20, name: 'SAN VICENTE')
City.create(province_id: 20, name: 'SANCTI SPIRITU')
City.create(province_id: 20, name: 'SANFORD')
City.create(province_id: 20, name: 'SANTA CLARA DE BUENA VISTA')
City.create(province_id: 20, name: 'SANTA CLARA DE SAGUIER')
City.create(province_id: 20, name: 'SANTA EMILIA')
City.create(province_id: 20, name: 'SANTA FE')
City.create(province_id: 20, name: 'SANTA ISABEL')
City.create(province_id: 20, name: 'SANTA LUCIA')
City.create(province_id: 20, name: 'SANTA MARGARITA')
City.create(province_id: 20, name: 'SANTA ROSA')
City.create(province_id: 20, name: 'SANTA TERESA')
City.create(province_id: 20, name: 'SANTO DOMINGO')
City.create(province_id: 20, name: 'SANTO TOME')
City.create(province_id: 20, name: 'SANTURCE')
City.create(province_id: 20, name: 'SARGENTO CABRAL')
City.create(province_id: 20, name: 'SARMIENTO')
City.create(province_id: 20, name: 'SASTRE')
City.create(province_id: 20, name: 'SAUCE VIEJO')
City.create(province_id: 20, name: 'SCHIFFNER')
City.create(province_id: 20, name: 'SERODINO')
City.create(province_id: 20, name: 'SOLDINI')
City.create(province_id: 20, name: 'SOLEDAD')
City.create(province_id: 20, name: 'SORRENTO ,EST.')
City.create(province_id: 20, name: 'SOUTOMAYOR')
City.create(province_id: 20, name: 'STEPHENSON ,EST.')
City.create(province_id: 20, name: 'SUARDI')
City.create(province_id: 20, name: 'SUNCHALES')
City.create(province_id: 20, name: 'SUSANA')
City.create(province_id: 20, name: 'TACUARENDI ,EMB.KILOMETRO 421')
City.create(province_id: 20, name: 'TACURAL')
City.create(province_id: 20, name: 'TARRAGONA')
City.create(province_id: 20, name: 'TARTAGAL ,EST.EL TAJAMAR')
City.create(province_id: 20, name: 'TEODELINA')
City.create(province_id: 20, name: 'TEODELINA ,EST.')
City.create(province_id: 20, name: 'THEOBALD')
City.create(province_id: 20, name: 'TIMBUES')
City.create(province_id: 20, name: 'TOBA')
City.create(province_id: 20, name: 'TORRES, MIGUEL')
City.create(province_id: 20, name: 'TORTUGAS')
City.create(province_id: 20, name: 'TOSTADO')
City.create(province_id: 20, name: 'TOTORAS')
City.create(province_id: 20, name: 'TRAILL')
City.create(province_id: 20, name: 'UMBERTO')
City.create(province_id: 20, name: 'URANGA')
City.create(province_id: 20, name: 'VENADO TUERTO')
City.create(province_id: 20, name: 'VERA ,EST.GOBERNADOR VERA')
City.create(province_id: 20, name: 'VERA MUJICA')
City.create(province_id: 20, name: 'VERA Y PINTADO ,EST.GUARANIES')
City.create(province_id: 20, name: 'VIDELA')
City.create(province_id: 20, name: 'VILA')
City.create(province_id: 20, name: 'VILLA AMELIA')
City.create(province_id: 20, name: 'VILLA AMERICA')
City.create(province_id: 20, name: 'VILLA ANA')
City.create(province_id: 20, name: 'VILLA CAÑAS')
City.create(province_id: 20, name: 'VILLA CONSTITUCION')
City.create(province_id: 20, name: 'VILLA DIEGO')
City.create(province_id: 20, name: 'VILLA ELOISA')
City.create(province_id: 20, name: 'VILLA ESTELA')
City.create(province_id: 20, name: 'VILLA GOBERNADOR GALVEZ')
City.create(province_id: 20, name: 'VILLA GUILLERMINA')
City.create(province_id: 20, name: 'VILLA MARGARITA')
City.create(province_id: 20, name: 'VILLA MINETTI')
City.create(province_id: 20, name: 'VILLA MUGUETA')
City.create(province_id: 20, name: 'VILLA OCAMPO')
City.create(province_id: 20, name: 'VILLA SARALEGUI')
City.create(province_id: 20, name: 'VILLA TRINIDAD')
City.create(province_id: 20, name: 'VILLADA')
City.create(province_id: 20, name: 'VILLE, MOISES')
City.create(province_id: 20, name: 'VIRGINIA')
City.create(province_id: 20, name: 'VUELTA DEL PARAGUAYO')
City.create(province_id: 20, name: 'WHEELWRIGHT')
City.create(province_id: 20, name: 'WILDERMUTH ,EST.GRANADERO B.BUSTOS')
City.create(province_id: 20, name: 'ZAVALLA')
City.create(province_id: 21, name: 'ABRA GRANDE')
City.create(province_id: 21, name: 'AEROLITO')
City.create(province_id: 21, name: 'AGUSTINA LIBARONA')
City.create(province_id: 21, name: 'AHI VEREMOS')
City.create(province_id: 21, name: 'ALGARROBAL VIEJO')
City.create(province_id: 21, name: 'ALHUAMPA')
City.create(province_id: 21, name: 'AMAMA')
City.create(province_id: 21, name: 'AMBARGASTA')
City.create(province_id: 21, name: 'AMICHA')
City.create(province_id: 21, name: 'AÑATUYA')
City.create(province_id: 21, name: 'ANCAJAN')
City.create(province_id: 21, name: 'ANIMAN')
City.create(province_id: 21, name: 'ANTAJE')
City.create(province_id: 21, name: 'ANTONIO E. TALBOT ,AP.')
City.create(province_id: 21, name: 'ARAGONES')
City.create(province_id: 21, name: 'ARBOL BLANCO')
City.create(province_id: 21, name: 'ARDILES')
City.create(province_id: 21, name: 'ARGENTINA')
City.create(province_id: 21, name: 'ARMONIA')
City.create(province_id: 21, name: 'ARRAGA')
City.create(province_id: 21, name: 'AVERIAS')
City.create(province_id: 21, name: 'BAEZ')
City.create(province_id: 21, name: 'BAJO GRANDE')
City.create(province_id: 21, name: 'BANDERA')
City.create(province_id: 21, name: 'BANDERA BAJADA')
City.create(province_id: 21, name: 'BARRANCAS')
City.create(province_id: 21, name: 'BARRIALITO')
City.create(province_id: 21, name: 'BELGRANO')
City.create(province_id: 21, name: 'BELGRANO')
City.create(province_id: 21, name: 'BELTRAN')
City.create(province_id: 21, name: 'BLANCA POZO')
City.create(province_id: 21, name: 'BOBADAL')
City.create(province_id: 21, name: 'BOQUERON')
City.create(province_id: 21, name: 'BREA POZO')
City.create(province_id: 21, name: 'CAJON')
City.create(province_id: 21, name: 'CAMPO DEL CIELO')
City.create(province_id: 21, name: 'CAMPO GALLO')
City.create(province_id: 21, name: 'CAMPO GRANDE')
City.create(province_id: 21, name: 'CAÑADA ESCOBAR')
City.create(province_id: 21, name: 'CARTAVIO')
City.create(province_id: 21, name: 'CASARES')
City.create(province_id: 21, name: 'CEJOLAO')
City.create(province_id: 21, name: 'CHAUPI POZO')
City.create(province_id: 21, name: 'CHILCA JULIANA')
City.create(province_id: 21, name: 'CHILCA LA LOMA')
City.create(province_id: 21, name: 'CHOYA')
City.create(province_id: 21, name: 'CLODOMIRA')
City.create(province_id: 21, name: 'COLONIA ARBOL BLANCO')
City.create(province_id: 21, name: 'COLONIA DORA')
City.create(province_id: 21, name: 'COLONIA SAN JUAN')
City.create(province_id: 21, name: 'COLONIA TOTORILLAS')
City.create(province_id: 21, name: 'CORONEL MANUEL L.RICO')
City.create(province_id: 21, name: 'CUATRO BOCAS')
City.create(province_id: 21, name: 'CUCHI CORRAL')
City.create(province_id: 21, name: 'DOÑA LUISA')
City.create(province_id: 21, name: 'DONADEU')
City.create(province_id: 21, name: 'EL CABURE')
City.create(province_id: 21, name: 'EL CAMBIADO')
City.create(province_id: 21, name: 'EL CEIBAL')
City.create(province_id: 21, name: 'EL CERRO')
City.create(province_id: 21, name: 'EL CHARCO')
City.create(province_id: 21, name: 'EL COLORADO')
City.create(province_id: 21, name: 'EL HOYO')
City.create(province_id: 21, name: 'EL MALACARA')
City.create(province_id: 21, name: 'EL MOJON')
City.create(province_id: 21, name: 'EL PERTIGO')
City.create(province_id: 21, name: 'EL POLEAR')
City.create(province_id: 21, name: 'EL PORVENIR')
City.create(province_id: 21, name: 'EL PUESTITO')
City.create(province_id: 21, name: 'EL SETENTA')
City.create(province_id: 21, name: 'EL TOBIANO ,EMB.')
City.create(province_id: 21, name: 'EL ZANJON')
City.create(province_id: 21, name: 'FERNANDEZ')
City.create(province_id: 21, name: 'FORRES')
City.create(province_id: 21, name: 'FORTIN INCA')
City.create(province_id: 21, name: 'FRIAS')
City.create(province_id: 21, name: 'GARZA')
City.create(province_id: 21, name: 'GIRARDET')
City.create(province_id: 21, name: 'GRAMILLA')
City.create(province_id: 21, name: 'GRANADERO GATICA')
City.create(province_id: 21, name: 'GUAMPACHO')
City.create(province_id: 21, name: 'GUARDIA ESCOLTA')
City.create(province_id: 21, name: 'HAASE')
City.create(province_id: 21, name: 'HERRERA')
City.create(province_id: 21, name: 'HOYON')
City.create(province_id: 21, name: 'HUACHANA')
City.create(province_id: 21, name: 'HUAICO HONDO')
City.create(province_id: 21, name: 'HURITU HUASI')
City.create(province_id: 21, name: 'HUYAMAMPA')
City.create(province_id: 21, name: 'ICAÑO')
City.create(province_id: 21, name: 'INGENIERO CARLOS CHRISTIERNSON ,EMB.')
City.create(province_id: 21, name: 'ISCA YACU')
City.create(province_id: 21, name: 'KILOMETR0 80 ,DV.')
City.create(province_id: 21, name: 'KILOMETR0699 ,EMP.')
City.create(province_id: 21, name: 'KILOMETRO 101 ,PDA.')
City.create(province_id: 21, name: 'KILOMETRO 1362 ,EMB.')
City.create(province_id: 21, name: 'KILOMETRO 1380 ,EMB.')
City.create(province_id: 21, name: 'KILOMETRO 1391 ,EMB.')
City.create(province_id: 21, name: 'KILOMETRO 153 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 18 ,EMB.')
City.create(province_id: 21, name: 'KILOMETRO 390 ,DV.')
City.create(province_id: 21, name: 'KILOMETRO 433 ,EMB.')
City.create(province_id: 21, name: 'KILOMETRO 436 ,DV.')
City.create(province_id: 21, name: 'KILOMETRO 454 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 473 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 494')
City.create(province_id: 21, name: 'KILOMETRO 499 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 546 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 546 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 55 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 606 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 613 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 645 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 659 ,AP.')
City.create(province_id: 21, name: 'KILOMETRO 969 ,EMB.')
City.create(province_id: 21, name: 'LA ALOJA ,EMB.')
City.create(province_id: 21, name: 'LA AURORA')
City.create(province_id: 21, name: 'LA BANDA')
City.create(province_id: 21, name: 'LA CAÑADA')
City.create(province_id: 21, name: 'LA DONOSA')
City.create(province_id: 21, name: 'LA FIRMEZA')
City.create(province_id: 21, name: 'LA FRAGUA')
City.create(province_id: 21, name: 'LA INVERNADA')
City.create(province_id: 21, name: 'LA ISLA')
City.create(province_id: 21, name: 'LA NENA')
City.create(province_id: 21, name: 'LA PALOMA ,EMB.')
City.create(province_id: 21, name: 'LA PUNTA')
City.create(province_id: 21, name: 'LA TAPA')
City.create(province_id: 21, name: 'LAPRIDA')
City.create(province_id: 21, name: 'LAS ABRAS')
City.create(province_id: 21, name: 'LAS CARPAS')
City.create(province_id: 21, name: 'LAS FLORES')
City.create(province_id: 21, name: 'LAS LOMITAS BLANCAS')
City.create(province_id: 21, name: 'LAS TINAJAS')
City.create(province_id: 21, name: 'LAVALLE')
City.create(province_id: 21, name: 'LEZCANOS')
City.create(province_id: 21, name: 'LIBARONA, AGUSTINA')
City.create(province_id: 21, name: 'LIBERTAD')
City.create(province_id: 21, name: 'LILO VIEJO')
City.create(province_id: 21, name: 'LLAJTA MAUCA')
City.create(province_id: 21, name: 'LOS JURIES')
City.create(province_id: 21, name: 'LOS LINARES')
City.create(province_id: 21, name: 'LOS MILAGROS')
City.create(province_id: 21, name: 'LOS NARANJOS')
City.create(province_id: 21, name: 'LOS NUÑEZ')
City.create(province_id: 21, name: 'LOS PIRPINTOS')
City.create(province_id: 21, name: 'LOS QUIROGA')
City.create(province_id: 21, name: 'LOS TELARES')
City.create(province_id: 21, name: 'LOS TIGRES')
City.create(province_id: 21, name: 'LUGONES')
City.create(province_id: 21, name: 'MACO')
City.create(province_id: 21, name: 'MAILIN')
City.create(province_id: 21, name: 'MAL PASO')
City.create(province_id: 21, name: 'MALBRAN')
City.create(province_id: 21, name: 'MATARA')
City.create(province_id: 21, name: 'MEDELLIN')
City.create(province_id: 21, name: 'MEDIA LUNA')
City.create(province_id: 21, name: 'MELERO')
City.create(province_id: 21, name: 'MIRAVAL, HERNAN M.')
City.create(province_id: 21, name: 'MISTOL PAMPA ,AP.')
City.create(province_id: 21, name: 'MONTE ALTO ,AP.')
City.create(province_id: 21, name: 'MONTE QUEMADO')
City.create(province_id: 21, name: 'MORALES')
City.create(province_id: 21, name: 'NASALO')
City.create(province_id: 21, name: 'NUEVA ESPERANZA')
City.create(province_id: 21, name: 'NUEVA FRANCIA')
City.create(province_id: 21, name: 'NUEVO SIMBOLAR')
City.create(province_id: 21, name: 'OTUMPA')
City.create(province_id: 21, name: 'PALO NEGRO')
City.create(province_id: 21, name: 'PAMPA DE LOS GUANACOS')
City.create(province_id: 21, name: 'PAMPA MAYO')
City.create(province_id: 21, name: 'PAMPA MUYOJ ,EMB.')
City.create(province_id: 21, name: 'PAMPA POZO')
City.create(province_id: 21, name: 'PASO DE LOS OSCARES')
City.create(province_id: 21, name: 'PATAY')
City.create(province_id: 21, name: 'PIEDRAS BLANCAS')
City.create(province_id: 21, name: 'POZO BETBEDER')
City.create(province_id: 21, name: 'POZO DEL CASTAÑO')
City.create(province_id: 21, name: 'POZO DEL TOBA')
City.create(province_id: 21, name: 'POZO DULCE')
City.create(province_id: 21, name: 'POZO HONDO')
City.create(province_id: 21, name: 'POZO HUASCHO')
City.create(province_id: 21, name: 'POZUELOS')
City.create(province_id: 21, name: 'PROVIDENCIA')
City.create(province_id: 21, name: 'PUNA')
City.create(province_id: 21, name: 'PUNI TAJO ,DV.')
City.create(province_id: 21, name: 'QUEBRACHITOS')
City.create(province_id: 21, name: 'QUEBRACHO COTO')
City.create(province_id: 21, name: 'QUILUMPA')
City.create(province_id: 21, name: 'QUIMILI')
City.create(province_id: 21, name: 'RAMIREZ DE VELAZCO')
City.create(province_id: 21, name: 'RAPELLI')
City.create(province_id: 21, name: 'REAL SAYANA')
City.create(province_id: 21, name: 'ROBLES')
City.create(province_id: 21, name: 'ROVERSI')
City.create(province_id: 21, name: 'SABAGASTA')
City.create(province_id: 21, name: 'SACHAYOJ')
City.create(province_id: 21, name: 'SALAVINA')
City.create(province_id: 21, name: 'SAN GREGORIO')
City.create(province_id: 21, name: 'SAN GREGORIO')
City.create(province_id: 21, name: 'SAN PABLO')
City.create(province_id: 21, name: 'SAN PEDRO')
City.create(province_id: 21, name: 'SAN RAMON')
City.create(province_id: 21, name: 'SAN RAMON')
City.create(province_id: 21, name: 'SANTA BARBARA')
City.create(province_id: 21, name: 'SANTA CATALINA')
City.create(province_id: 21, name: 'SANTA CRUZ')
City.create(province_id: 21, name: 'SANTA JUSTINA')
City.create(province_id: 21, name: 'SANTA MARIA')
City.create(province_id: 21, name: 'SANTA MARIA ,EST.INGENIERO EZCURRA')
City.create(province_id: 21, name: 'SANTA MARIA SALOME')
City.create(province_id: 21, name: 'SANTIAGO DEL ESTERO')
City.create(province_id: 21, name: 'SANTO DOMINGO')
City.create(province_id: 21, name: 'SANTO DOMINGO')
City.create(province_id: 21, name: 'SANTOS LUGARES')
City.create(province_id: 21, name: 'SELVA')
City.create(province_id: 21, name: 'SEÑORA PUJIO')
City.create(province_id: 21, name: 'SIETE ARBOLES')
City.create(province_id: 21, name: 'SIMBOL')
City.create(province_id: 21, name: 'SIMBOL BAJO ,EMB.')
City.create(province_id: 21, name: 'SIMBOLAR')
City.create(province_id: 21, name: 'SOL DE JULIO')
City.create(province_id: 21, name: 'SOL DE MAYO')
City.create(province_id: 21, name: 'SUMAMAO')
City.create(province_id: 21, name: 'SUMAMPA')
City.create(province_id: 21, name: 'SUNCHO CORRAL')
City.create(province_id: 21, name: 'SURIHUAYA ,AP.')
City.create(province_id: 21, name: 'TABOADA')
City.create(province_id: 21, name: 'TACANITAS')
City.create(province_id: 21, name: 'TACO POZO')
City.create(province_id: 21, name: 'TERMAS DE RIO HONDO')
City.create(province_id: 21, name: 'TINTINA')
City.create(province_id: 21, name: 'TIUN PUNCO')
City.create(province_id: 21, name: 'TOBAS')
City.create(province_id: 21, name: 'TRES MOJONES')
City.create(province_id: 21, name: 'TRES POZOS')
City.create(province_id: 21, name: 'URUTAU')
City.create(province_id: 21, name: 'VACA HUANUNA')
City.create(province_id: 21, name: 'VILELAS')
City.create(province_id: 21, name: 'VILLA ADELA')
City.create(province_id: 21, name: 'VILLA ATAMISQUI')
City.create(province_id: 21, name: 'VILLA BRAÑA')
City.create(province_id: 21, name: 'VILLA ELVIRA')
City.create(province_id: 21, name: 'VILLA FIGUEROA')
City.create(province_id: 21, name: 'VILLA GENERAL MITRE ,EST.PINTO')
City.create(province_id: 21, name: 'VILLA GUASAYAN')
City.create(province_id: 21, name: 'VILLA JIMENEZ')
City.create(province_id: 21, name: 'VILLA LA PUNTA')
City.create(province_id: 21, name: 'VILLA MATARA')
City.create(province_id: 21, name: 'VILLA MATILDE')
City.create(province_id: 21, name: 'VILLA MATOQUE')
City.create(province_id: 21, name: 'VILLA MERCEDES')
City.create(province_id: 21, name: 'VILLA OJO DE AGUA')
City.create(province_id: 21, name: 'VILLA PALMAR')
City.create(province_id: 21, name: 'VILLA QUEBRACHOS')
City.create(province_id: 21, name: 'VILLA RIO HONDO')
City.create(province_id: 21, name: 'VILLA SAN MARTIN ,EST.LORETO')
City.create(province_id: 21, name: 'VILLA SILIPICA')
City.create(province_id: 21, name: 'VILLA UNION')
City.create(province_id: 21, name: 'VILMER')
City.create(province_id: 21, name: 'VINARA')
City.create(province_id: 21, name: 'YOUNG, TOMAS')
City.create(province_id: 21, name: 'YUCHAN')
City.create(province_id: 21, name: 'ZANJON ,EST.')
City.create(province_id: 22, name: 'ALMIRANTE BROWN')
City.create(province_id: 22, name: 'BAHIA FOX')
City.create(province_id: 22, name: 'BAHIA THETIS')
City.create(province_id: 22, name: 'BARRIO ALMIRANTE BROWN')
City.create(province_id: 22, name: 'BASE A.C.E. ALFEREZ DE NAVIO SOBRAL')
City.create(province_id: 22, name: 'BASE AEREA TTE. BENJAMIN MATIENZO')
City.create(province_id: 22, name: 'BASE DE EJERCITO ESPERANZA')
City.create(province_id: 22, name: 'BASE DE EJERCITO GRL.BELGRANO')
City.create(province_id: 22, name: 'BASE DE EJERCITO GRL.SAN MARTIN')
City.create(province_id: 22, name: 'CARMEN')
City.create(province_id: 22, name: 'CULLEN')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL CORBETA URUGUAY')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL DECEPCION')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL ESPERANZA')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL MELCHIOR')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL ORCADAS')
City.create(province_id: 22, name: 'DESTACAMENTO NAVAL TENIENTE CAMARA')
City.create(province_id: 22, name: 'ESTACION AERONAVAL PETRIEL')
City.create(province_id: 22, name: 'ESTACION CIENTIFICA ALMIRANTE BROWN')
City.create(province_id: 22, name: 'ESTACION CIENTIFICA ELLSWORTH')
City.create(province_id: 22, name: 'ESTACION DE APOYO NÂº 1 FUERZA AEREA ARG.')
City.create(province_id: 22, name: 'GRYTVIKEN')
City.create(province_id: 22, name: 'KAIKEN')
City.create(province_id: 22, name: 'LA MARINA')
City.create(province_id: 22, name: 'LAPATAIA')
City.create(province_id: 22, name: 'MARIA LUISA')
City.create(province_id: 22, name: 'MISION SALESIANA')
City.create(province_id: 22, name: 'PUERTO ARGENTINO')
City.create(province_id: 22, name: 'PUERTO HARBERTON')
City.create(province_id: 22, name: 'PUERTO LEITH')
City.create(province_id: 22, name: 'PUERTO LUIS')
City.create(province_id: 22, name: 'PUERTO RANCHO')
City.create(province_id: 22, name: 'PUERTO REMOLINO')
City.create(province_id: 22, name: 'PUERTO SAN CARLOS')
City.create(province_id: 22, name: 'RANCHO HAMBRE')
City.create(province_id: 22, name: 'RIO GRANDE')
City.create(province_id: 22, name: 'SAN JULIO')
City.create(province_id: 22, name: 'SAN JUSTO')
City.create(province_id: 22, name: 'SAN PABLO')
City.create(province_id: 22, name: 'SAN SEBASTIAN')
City.create(province_id: 22, name: 'SARA')
City.create(province_id: 22, name: 'SARMIENTO')
City.create(province_id: 22, name: 'USHUAIA')
City.create(province_id: 22, name: 'VIAMONTE')
City.create(province_id: 22, name: 'VIEJA CARMEN')
City.create(province_id: 23, name: '7 DE ABRIL')
City.create(province_id: 23, name: 'ACEQUIONES')
City.create(province_id: 23, name: 'ACHERAL')
City.create(province_id: 23, name: 'AGUA DULCE')
City.create(province_id: 23, name: 'AGUA DULCE ,EMP.')
City.create(province_id: 23, name: 'AGUILARES')
City.create(province_id: 23, name: 'ALDERETES')
City.create(province_id: 23, name: 'ALPACHIRI')
City.create(province_id: 23, name: 'ALTA GRACIA')
City.create(province_id: 23, name: 'ALTO DE MEDINA')
City.create(province_id: 23, name: 'ALTO VERDE')
City.create(province_id: 23, name: 'AMAICHA DEL VALLE')
City.create(province_id: 23, name: 'AMBERES')
City.create(province_id: 23, name: 'AMPATA')
City.create(province_id: 23, name: 'ANCAJULI')
City.create(province_id: 23, name: 'ANFAMA')
City.create(province_id: 23, name: 'ARAOZ')
City.create(province_id: 23, name: 'ARBOLES GRANDES')
City.create(province_id: 23, name: 'ARCADIA')
City.create(province_id: 23, name: 'ARROYO')
City.create(province_id: 23, name: 'ATAHONA')
City.create(province_id: 23, name: 'BAJASTINE')
City.create(province_id: 23, name: 'BALDERRAMA')
City.create(province_id: 23, name: 'BANDA DEL RIO SALI')
City.create(province_id: 23, name: 'BELICHA HUAICO')
City.create(province_id: 23, name: 'BELLA VISTA')
City.create(province_id: 23, name: 'BENJAMIN ARAOZ')
City.create(province_id: 23, name: 'BENJAMIN PAZ')
City.create(province_id: 23, name: 'BURRUYACU')
City.create(province_id: 23, name: 'BUSTAMANTE ,AP.')
City.create(province_id: 23, name: 'CACHI HUASI ,AP.')
City.create(province_id: 23, name: 'CACHI YACO ,AP.')
City.create(province_id: 23, name: 'CAMPO BELLO')
City.create(province_id: 23, name: 'CAÑETE')
City.create(province_id: 23, name: 'CEVIL POZO')
City.create(province_id: 23, name: 'CEVIL REDONDO')
City.create(province_id: 23, name: 'CHABELA')
City.create(province_id: 23, name: 'CHAÑARITO')
City.create(province_id: 23, name: 'CHICLIGASTA')
City.create(province_id: 23, name: 'CHILCAS')
City.create(province_id: 23, name: 'CHOROMORO')
City.create(province_id: 23, name: 'CHORRILLOS')
City.create(province_id: 23, name: 'CHUANTA')
City.create(province_id: 23, name: 'CIUDACITA')
City.create(province_id: 23, name: 'CIUDAD HOSPITAL')
City.create(province_id: 23, name: 'CIUDAD UNIVERSITARIA')
City.create(province_id: 23, name: 'COCHUNA')
City.create(province_id: 23, name: 'COLALAO DEL VALLE')
City.create(province_id: 23, name: 'COLOMBRES')
City.create(province_id: 23, name: 'COLONIA NUEVA TRINIDAD')
City.create(province_id: 23, name: 'COLONIA SAN JORGE')
City.create(province_id: 23, name: 'COLONIA SAN JOSE')
City.create(province_id: 23, name: 'CONCEPCION')
City.create(province_id: 23, name: 'CRUZ DEL NORTE')
City.create(province_id: 23, name: 'DIQUE EL CADILLAL')
City.create(province_id: 23, name: 'EL ASERRADERO')
City.create(province_id: 23, name: 'EL BAÑADO')
City.create(province_id: 23, name: 'EL BARCO')
City.create(province_id: 23, name: 'EL BRACHO')
City.create(province_id: 23, name: 'EL CADILLAL')
City.create(province_id: 23, name: 'EL CHAÑAR')
City.create(province_id: 23, name: 'EL COLMENAL')
City.create(province_id: 23, name: 'EL DURAZNITO')
City.create(province_id: 23, name: 'EL GUARDAMONTE')
City.create(province_id: 23, name: 'EL JARDIN')
City.create(province_id: 23, name: 'EL MOLINO')
City.create(province_id: 23, name: 'EL MOLLAR')
City.create(province_id: 23, name: 'EL NARANJO')
City.create(province_id: 23, name: 'EL OJO')
City.create(province_id: 23, name: 'EL PORVENIR')
City.create(province_id: 23, name: 'EL SUNCHAL')
City.create(province_id: 23, name: 'EL ZAPALLAR')
City.create(province_id: 23, name: 'ENCRUCIJADA')
City.create(province_id: 23, name: 'ESCABA ABAJO')
City.create(province_id: 23, name: 'ESCABA ARRIBA')
City.create(province_id: 23, name: 'ESQUINA')
City.create(province_id: 23, name: 'FAMAILLA')
City.create(province_id: 23, name: 'FINCA ELISA')
City.create(province_id: 23, name: 'GALLO, DELFIN')
City.create(province_id: 23, name: 'GARCIA FERNANDEZ, MANUEL')
City.create(province_id: 23, name: 'GASTONA')
City.create(province_id: 23, name: 'GOBERNADOR GARMENDIA')
City.create(province_id: 23, name: 'GOBERNADOR NOUGUES')
City.create(province_id: 23, name: 'GOBERNADOR PIEDRABUENA')
City.create(province_id: 23, name: 'GRANEROS')
City.create(province_id: 23, name: 'GUZMAN')
City.create(province_id: 23, name: 'HUASA PAMPA NORTE ,EST.HUASA PAMPA')
City.create(province_id: 23, name: 'HUASA PAMPA SUR')
City.create(province_id: 23, name: 'ICHIPUCA')
City.create(province_id: 23, name: 'INGENIO AMALIA')
City.create(province_id: 23, name: 'INGENIO CONCEPCION')
City.create(province_id: 23, name: 'INGENIO CRUZ ALTA')
City.create(province_id: 23, name: 'INGENIO LA CORONA')
City.create(province_id: 23, name: 'INGENIO LA ESPERANZA')
City.create(province_id: 23, name: 'INGENIO LA FLORIDA')
City.create(province_id: 23, name: 'INGENIO LA FRONTERITA')
City.create(province_id: 23, name: 'INGENIO LASTENIA')
City.create(province_id: 23, name: 'INGENIO LULES')
City.create(province_id: 23, name: 'INGENIO LULES ,EST.')
City.create(province_id: 23, name: 'INGENIO SAN JOSE')
City.create(province_id: 23, name: 'INGENIO SAN MIGUEL')
City.create(province_id: 23, name: 'INGENIO SAN PABLO')
City.create(province_id: 23, name: 'INGENIO SANTA ANA')
City.create(province_id: 23, name: 'INGENIO SANTA LUCIA')
City.create(province_id: 23, name: 'KILOMETRO 10 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 102 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1185 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1194 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1207 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1213 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1235 ,DV.')
City.create(province_id: 23, name: 'KILOMETRO 1248 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1254 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 1256 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 29 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 36 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 46 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 5 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 55 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 770 ,DV.')
City.create(province_id: 23, name: 'KILOMETRO 781 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 784 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 794 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 808 ,AP.')
City.create(province_id: 23, name: 'KILOMETRO 810 ,DV.')
City.create(province_id: 23, name: 'KILOMETRO 825')
City.create(province_id: 23, name: 'KILOMETRO 847 ,DV.')
City.create(province_id: 23, name: 'KILOMETRO 99,DV.')
City.create(province_id: 23, name: 'LA ANGOSTURA')
City.create(province_id: 23, name: 'LA CAÑADA')
City.create(province_id: 23, name: 'LA COCHA')
City.create(province_id: 23, name: 'LA CRUZ')
City.create(province_id: 23, name: 'LA ENCANTADA')
City.create(province_id: 23, name: 'LA FALDA')
City.create(province_id: 23, name: 'LA HIGUERA')
City.create(province_id: 23, name: 'LA INVERNADA')
City.create(province_id: 23, name: 'LA MADRID')
City.create(province_id: 23, name: 'LA POSTA')
City.create(province_id: 23, name: 'LA RAMADA')
City.create(province_id: 23, name: 'LA REDUCCION')
City.create(province_id: 23, name: 'LA RINCONADA')
City.create(province_id: 23, name: 'LA TIPA')
City.create(province_id: 23, name: 'LA TRINIDAD')
City.create(province_id: 23, name: 'LAGUNA DE ROBLES')
City.create(province_id: 23, name: 'LAS CEJAS')
City.create(province_id: 23, name: 'LAS GUCHAS')
City.create(province_id: 23, name: 'LAS PIEDRITAS')
City.create(province_id: 23, name: 'LEALES')
City.create(province_id: 23, name: 'LILLO, MIGUEL')
City.create(province_id: 23, name: 'LOMA VERDE')
City.create(province_id: 23, name: 'LOPEZ DOMINGUEZ ,AP.')
City.create(province_id: 23, name: 'LOS AGUIRRE')
City.create(province_id: 23, name: 'LOS CHAÑARES')
City.create(province_id: 23, name: 'LOS GOMEZ')
City.create(province_id: 23, name: 'LOS GUTIERREZ')
City.create(province_id: 23, name: 'LOS PEREYRA')
City.create(province_id: 23, name: 'LOS PUESTOS')
City.create(province_id: 23, name: 'LOS RALOS')
City.create(province_id: 23, name: 'LOS SARMIENTOS')
City.create(province_id: 23, name: 'LOS SOSA')
City.create(province_id: 23, name: 'LUISIANA')
City.create(province_id: 23, name: 'LULES')
City.create(province_id: 23, name: 'LUNAREJOS')
City.create(province_id: 23, name: 'MACIO')
City.create(province_id: 23, name: 'MACOMITA')
City.create(province_id: 23, name: 'MALVINAS')
City.create(province_id: 23, name: 'MANANTIAL')
City.create(province_id: 23, name: 'MARIÑO')
City.create(province_id: 23, name: 'MATE DE LUNA')
City.create(province_id: 23, name: 'MEDINAS')
City.create(province_id: 23, name: 'MENDEZ, PEDRO G.')
City.create(province_id: 23, name: 'MILLAN, DOMINGO')
City.create(province_id: 23, name: 'MIRAFLORES')
City.create(province_id: 23, name: 'MIXTA')
City.create(province_id: 23, name: 'MONTE GRANDE')
City.create(province_id: 23, name: 'MONTEAGUDO')
City.create(province_id: 23, name: 'MONTEROS')
City.create(province_id: 23, name: 'MUNDO NUEVO')
City.create(province_id: 23, name: 'MUÑECAS')
City.create(province_id: 23, name: 'NARANJITO')
City.create(province_id: 23, name: 'NUEVA ESPAÑA')
City.create(province_id: 23, name: 'NUEVA TRINIDAD')
City.create(province_id: 23, name: 'ORAN')
City.create(province_id: 23, name: 'PACARA')
City.create(province_id: 23, name: 'PADILLA')
City.create(province_id: 23, name: 'PALA PALA')
City.create(province_id: 23, name: 'PAZ, BENJAMIN')
City.create(province_id: 23, name: 'PAZ, LEOCADIO')
City.create(province_id: 23, name: 'PAZ, MARCOS')
City.create(province_id: 23, name: 'PEDRAZA, MANUELA ,AP.')
City.create(province_id: 23, name: 'POLITO ,DV.')
City.create(province_id: 23, name: 'POTRERO DE LAS TABLAS')
City.create(province_id: 23, name: 'POZO DEL ALTO')
City.create(province_id: 23, name: 'PUEBLO VIEJO')
City.create(province_id: 23, name: 'PUERTA DE SAN JAVIER')
City.create(province_id: 23, name: 'RACO')
City.create(province_id: 23, name: 'RANCHILLOS')
City.create(province_id: 23, name: 'REQUELME')
City.create(province_id: 23, name: 'RIO CHICO')
City.create(province_id: 23, name: 'RIO COLORADO')
City.create(province_id: 23, name: 'RIO DEL NIO')
City.create(province_id: 23, name: 'RIO SECO')
City.create(province_id: 23, name: 'ROMERO POZO')
City.create(province_id: 23, name: 'ROUGES, LEON')
City.create(province_id: 23, name: 'RUMI PUNCO')
City.create(province_id: 23, name: 'SAN AGUSTIN')
City.create(province_id: 23, name: 'SAN ANDRES')
City.create(province_id: 23, name: 'SAN FELIPE')
City.create(province_id: 23, name: 'SAN IGNACIO')
City.create(province_id: 23, name: 'SAN JAVIER')
City.create(province_id: 23, name: 'SAN JOSE')
City.create(province_id: 23, name: 'SAN MIGUEL')
City.create(province_id: 23, name: 'SAN MIGUEL DE TUCUMAN ,EST.TUCUMAN')
City.create(province_id: 23, name: 'SAN PABLO')
City.create(province_id: 23, name: 'SAN PATRICIO')
City.create(province_id: 23, name: 'SAN PEDRO DE COLALAO')
City.create(province_id: 23, name: 'SAN RAFAEL')
City.create(province_id: 23, name: 'SAN VICENTE')
City.create(province_id: 23, name: 'SANTA BARBARA')
City.create(province_id: 23, name: 'SANTA CRUZ')
City.create(province_id: 23, name: 'SANTA ROSA DE LEALES')
City.create(province_id: 23, name: 'SIAMBON')
City.create(province_id: 23, name: 'SIMOCA')
City.create(province_id: 23, name: 'SINQUIEAL')
City.create(province_id: 23, name: 'SOL DE MAYO')
City.create(province_id: 23, name: 'SUELDOS')
City.create(province_id: 23, name: 'TACANAS ,EST.SUPERINTENDENTE LEDESMA')
City.create(province_id: 23, name: 'TACO PALTA')
City.create(province_id: 23, name: 'TACO RALO')
City.create(province_id: 23, name: 'TAFI DEL VALLE')
City.create(province_id: 23, name: 'TAFI VIEJO')
City.create(province_id: 23, name: 'TAFICILLO')
City.create(province_id: 23, name: 'TALA POZO')
City.create(province_id: 23, name: 'TAPIA')
City.create(province_id: 23, name: 'TARUCA PAMPA')
City.create(province_id: 23, name: 'TICUCHO')
City.create(province_id: 23, name: 'TIMBO NUEVO')
City.create(province_id: 23, name: 'TIMBO VIEJO')
City.create(province_id: 23, name: 'TINAJEROS')
City.create(province_id: 23, name: 'TRANCAS')
City.create(province_id: 23, name: 'TREJOS')
City.create(province_id: 23, name: 'TRES POZOS')
City.create(province_id: 23, name: 'TUNA SOLA')
City.create(province_id: 23, name: 'TUSQUITAS')
City.create(province_id: 23, name: 'URIZAR')
City.create(province_id: 23, name: 'UTURUNCO')
City.create(province_id: 23, name: 'VILLA CARMELA')
City.create(province_id: 23, name: 'VILLA LUJAN')
City.create(province_id: 23, name: 'VILLA NUEVA')
City.create(province_id: 23, name: 'VILLA PADRE MONTI')
City.create(province_id: 23, name: 'VILLA QUINTEROS')
City.create(province_id: 23, name: 'VILLA RESCATE')
City.create(province_id: 23, name: 'VIPOS')
City.create(province_id: 23, name: 'YACUCHINA')
City.create(province_id: 23, name: 'YANIMAS')
City.create(province_id: 23, name: 'YERBA BUENA')

City.create(province_id: 24, name: 'São Luís')
City.create(province_id: 25, name: 'Cuiabá')
