City.create(province_id: 5, name: 'SACANTA')
City.create(province_id: 5, name: 'SAGUION')
City.create(province_id: 5, name: 'SAIRA')
City.create(province_id: 5, name: 'SALADILLO')
City.create(province_id: 5, name: 'SALAS, MIGUEL')
City.create(province_id: 5, name: 'SALDAN')
City.create(province_id: 5, name: 'SALGUERO')
City.create(province_id: 5, name: 'SALSACATE')
City.create(province_id: 5, name: 'SALSIPUEDES')
City.create(province_id: 5, name: 'SAMPACHO')
City.create(province_id: 5, name: 'SAN AGUSTIN')
City.create(province_id: 5, name: 'SAN AGUSTIN')
City.create(province_id: 5, name: 'SAN AMBROSIO')
City.create(province_id: 5, name: 'SAN ANTINIO')
City.create(province_id: 5, name: 'SAN ANTONIO')
City.create(province_id: 5, name: 'SAN ANTONIO')
City.create(province_id: 5, name: 'SAN ANTONIO DE ARREDONDO')
City.create(province_id: 5, name: 'SAN ANTONIO DE LITIN')
City.create(province_id: 5, name: 'SAN BARTOLOME')
City.create(province_id: 5, name: 'SAN BASILIO')
City.create(province_id: 5, name: 'SAN BUENAVENTURA')
City.create(province_id: 5, name: 'SAN BUENAVENTURA ,AP.')
City.create(province_id: 5, name: 'SAN CARLOS')
City.create(province_id: 5, name: 'SAN CARLOS')
City.create(province_id: 5, name: 'SAN CLEMENTE')
City.create(province_id: 5, name: 'SAN ESTEBAN')
City.create(province_id: 5, name: 'SAN FERNANDO')
City.create(province_id: 5, name: 'SAN FRANCISCO')
City.create(province_id: 5, name: 'SAN FRANCISCO DEL CHAÑAR')
City.create(province_id: 5, name: 'SAN GERONIMO')
City.create(province_id: 5, name: 'SAN IGNACIO')
City.create(province_id: 5, name: 'SAN IGNACIO')
City.create(province_id: 5, name: 'SAN JAVIER')
City.create(province_id: 5, name: 'SAN JOAQUIN')
City.create(province_id: 5, name: 'SAN JOSE')
City.create(province_id: 5, name: 'SAN JOSE')
City.create(province_id: 5, name: 'SAN JOSE DE LA DORMIDA')
City.create(province_id: 5, name: 'SAN JOSE DE LAS SALINAS ,EST.SAN JOSE')
City.create(province_id: 5, name: 'SAN JOSE DEL SALTEÑO')
City.create(province_id: 5, name: 'SAN LORENZO')
City.create(province_id: 5, name: 'SAN LUIS')
City.create(province_id: 5, name: 'SAN MARCOS')
City.create(province_id: 5, name: 'SAN MARCOS SIERRA')
City.create(province_id: 5, name: 'SAN MIGUEL')
City.create(province_id: 5, name: 'SAN PEDRO')
City.create(province_id: 5, name: 'SAN PEDRO')
City.create(province_id: 5, name: 'SAN PEDRO')
City.create(province_id: 5, name: 'SAN PEDRO DE TOYOS')
City.create(province_id: 5, name: 'SAN PEDRO NORTE')
City.create(province_id: 5, name: 'SAN RAFAEL')
City.create(province_id: 5, name: 'SAN ROQUE')
City.create(province_id: 5, name: 'SAN SEVERO')
City.create(province_id: 5, name: 'SAN VICENTE')
City.create(province_id: 5, name: 'SANABRIA')
City.create(province_id: 5, name: 'SANTA ANA')
City.create(province_id: 5, name: 'SANTA CATALINA')
City.create(province_id: 5, name: 'SANTA CATALINA ,EST.HOLMBERG')
City.create(province_id: 5, name: 'SANTA CRUZ')
City.create(province_id: 5, name: 'SANTA EUFEMIA')
City.create(province_id: 5, name: 'SANTA ISABEL')
City.create(province_id: 5, name: 'SANTA MAGDALENA ,EST.JOVITA')
City.create(province_id: 5, name: 'SANTA MARIA')
City.create(province_id: 5, name: 'SANTA MARIA DE PUNILLA ,EST.SANTA MARIA')
City.create(province_id: 5, name: 'SANTA ROSA')
City.create(province_id: 5, name: 'SANTA ROSA DE CALAMUCHITA')
City.create(province_id: 5, name: 'SANTA ROSA DE RIO PRIMERO ,EST.V.S.ROSA')
City.create(province_id: 5, name: 'SANTA SABINA')
City.create(province_id: 5, name: 'SANTA TERESA')
City.create(province_id: 5, name: 'SANTA VICTORIA')
City.create(province_id: 5, name: 'SARMIENTO')
City.create(province_id: 5, name: 'SAUCE DE LOS QUEVEDOS')
City.create(province_id: 5, name: 'SEEBER')
City.create(province_id: 5, name: 'SERRANO')
City.create(province_id: 5, name: 'SERREZUELA')
City.create(province_id: 5, name: 'SIMBOLAR')
City.create(province_id: 5, name: 'SINSACATE')
City.create(province_id: 5, name: 'SOCONCHO')
City.create(province_id: 5, name: 'SOTO')
City.create(province_id: 5, name: 'SUCO')
City.create(province_id: 5, name: 'SUQUIA ,AP.')
City.create(province_id: 5, name: 'SVILLA NUEVA')
City.create(province_id: 5, name: 'TABAQUILLO')
City.create(province_id: 5, name: 'TALA CAÑADA')
City.create(province_id: 5, name: 'TALA CRUZ')
City.create(province_id: 5, name: 'TALA NORTE ,EST.EL ALCALDE')
City.create(province_id: 5, name: 'TALAINI')
City.create(province_id: 5, name: 'TANCACHA')
City.create(province_id: 5, name: 'TANTI')
City.create(province_id: 5, name: 'TANTI NUEVO')
City.create(province_id: 5, name: 'TASMA')
City.create(province_id: 5, name: 'TEGUA')
City.create(province_id: 5, name: 'TEMPLE, SANTIAGO')
City.create(province_id: 5, name: 'THEA')
City.create(province_id: 5, name: 'TICINO')
City.create(province_id: 5, name: 'TILQUICHO')
City.create(province_id: 5, name: 'TINOCO')
City.create(province_id: 5, name: 'TIO PUJIO')
City.create(province_id: 5, name: 'TOLEDO')
City.create(province_id: 5, name: 'TOSNO')
City.create(province_id: 5, name: 'TOSQUITA')
City.create(province_id: 5, name: 'TOTORALEJOS')
City.create(province_id: 5, name: 'TRANSITO')
City.create(province_id: 5, name: 'TRAVESIA')
City.create(province_id: 5, name: 'TRES ARBOLES')
City.create(province_id: 5, name: 'TRINCHERA')
City.create(province_id: 5, name: 'TUCLAME')
City.create(province_id: 5, name: 'UCACHA')
City.create(province_id: 5, name: 'UNQUILLO')
City.create(province_id: 5, name: 'VALLE HERMOSO')
City.create(province_id: 5, name: 'VELEZ SARSFIELD, DALMACIO')
City.create(province_id: 5, name: 'VELEZ SARSFIELD, DALMACIO ,AP.')
City.create(province_id: 5, name: 'VIAMONTE')
City.create(province_id: 5, name: 'VICUÑA MACKENNA')
City.create(province_id: 5, name: 'VILLA AIZACATE')
City.create(province_id: 5, name: 'VILLA ALICIA')
City.create(province_id: 5, name: 'VILLA ALLENDE')
City.create(province_id: 5, name: 'VILLA ASCASUBI')
City.create(province_id: 5, name: 'VILLA BUSTOS')
City.create(province_id: 5, name: 'VILLA CANDELARIA')
City.create(province_id: 5, name: 'VILLA CARLOS PAZ')
City.create(province_id: 5, name: 'VILLA CERRO AZUL')
City.create(province_id: 5, name: 'VILLA COLANCHANGA')
City.create(province_id: 5, name: 'VILLA COLONIA ITALIANA')
City.create(province_id: 5, name: 'VILLA CONCEPCION DEL TIO')
City.create(province_id: 5, name: 'VILLA CORAZON DE MARIA')
City.create(province_id: 5, name: 'VILLA CURA BROCHERO')
City.create(province_id: 5, name: 'VILLA DE LAS ROSAS')
City.create(province_id: 5, name: 'VILLA DE MARIA')
City.create(province_id: 5, name: 'VILLA DE SOTO')
City.create(province_id: 5, name: 'VILLA DEL DIQUE')
City.create(province_id: 5, name: 'VILLA DEL LAGO')
City.create(province_id: 5, name: 'VILLA DEL ROSARIO')
City.create(province_id: 5, name: 'VILLA DEL TOTORAL')
City.create(province_id: 5, name: 'VILLA DEL TRANSITO')
City.create(province_id: 5, name: 'VILLA DOLORES')
City.create(province_id: 5, name: 'VILLA ELISA')
City.create(province_id: 5, name: 'VILLA ESQUIU')
City.create(province_id: 5, name: 'VILLA FONTANA')
City.create(province_id: 5, name: 'VILLA GARCIA')
City.create(province_id: 5, name: 'VILLA GENERAL BELGRANO')
City.create(province_id: 5, name: 'VILLA GIARDINO')
City.create(province_id: 5, name: 'VILLA GUTIERREZ ,EMB. KM. 807')
City.create(province_id: 5, name: 'VILLA HUIDOBRO ,EST.CAÑADA VERDE')
City.create(province_id: 5, name: 'VILLA ICHO CRUZ')
City.create(province_id: 5, name: 'VILLA INDEPENDENCIA')
City.create(province_id: 5, name: 'VILLA LOS MOLINOS')
City.create(province_id: 5, name: 'VILLA MARIA')
City.create(province_id: 5, name: 'VILLA MODERNA')
City.create(province_id: 5, name: 'VILLA ÑU PORA')
City.create(province_id: 5, name: 'VILLA QUILINO')
City.create(province_id: 5, name: 'VILLA RAFAEL BENEGAS')
City.create(province_id: 5, name: 'VILLA REDUCCION')
City.create(province_id: 5, name: 'VILLA ROSARIO DEL SALADILLO')
City.create(province_id: 5, name: 'VILLA ROSSI')
City.create(province_id: 5, name: 'VILLA RUMIPAL')
City.create(province_id: 5, name: 'VILLA SAN ANTONIO')
City.create(province_id: 5, name: 'VILLA SAN ESTEBAN')
City.create(province_id: 5, name: 'VILLA SARMIENTO')
City.create(province_id: 5, name: 'VILLA TULUMBA')
City.create(province_id: 5, name: 'VILLA VALERIA')
City.create(province_id: 5, name: 'VILLA VAUDAGNA')
City.create(province_id: 5, name: 'VILLA VISO')
City.create(province_id: 5, name: 'VIVAS, PEDRO E. ,EMB.KILOMETRO 658')
City.create(province_id: 5, name: 'VIVERO')
City.create(province_id: 5, name: 'WASHINGTON')
City.create(province_id: 5, name: 'WATT ,EST.MELIDEO')
City.create(province_id: 5, name: 'YACANTO')
City.create(province_id: 5, name: 'YACANTO DE CALAMUCHITA')
City.create(province_id: 5, name: 'YOCSINA')
City.create(province_id: 5, name: 'ZUMARAN, ANA')
City.create(province_id: 6, name: '9 DE JULIO ,EST.PUEBLO DE JULIO')
City.create(province_id: 6, name: 'ACUÑA')
City.create(province_id: 6, name: 'AGUAPEY')
City.create(province_id: 6, name: 'AGUAY')
City.create(province_id: 6, name: 'ALEM CUE')
City.create(province_id: 6, name: 'ALFONSO LOMA')
City.create(province_id: 6, name: 'ALVEAR')
City.create(province_id: 6, name: 'ANGUA')
City.create(province_id: 6, name: 'APIPE')
City.create(province_id: 6, name: 'ARERUNGUA')
City.create(province_id: 6, name: 'ARROYITO')
City.create(province_id: 6, name: 'ARROYO AMBROSIO ,AP.')
City.create(province_id: 6, name: 'ARROYO GONZALEZ')
City.create(province_id: 6, name: 'ARROYO PONTON')
City.create(province_id: 6, name: 'BAIBIENE')
City.create(province_id: 6, name: 'BAÑADO SUR')
City.create(province_id: 6, name: 'BATEL')
City.create(province_id: 6, name: 'BELLA VISTA')
City.create(province_id: 6, name: 'BERON DE ASTRADA')
City.create(province_id: 6, name: 'BONPLAND')
City.create(province_id: 6, name: 'BOQUERON')
City.create(province_id: 6, name: 'BUENA VISTA')
City.create(province_id: 6, name: 'CAA GUAZU ,AP.')
City.create(province_id: 6, name: 'CABRED')
City.create(province_id: 6, name: 'CAMPO GRANDE')
City.create(province_id: 6, name: 'CAMPO GRANDE')
City.create(province_id: 6, name: 'CAÑADITAS')
City.create(province_id: 6, name: 'CAPILLITAS')
City.create(province_id: 6, name: 'CAPITAN JOAQUIN MADARIAGA')
City.create(province_id: 6, name: 'CAZA PAVA')
City.create(province_id: 6, name: 'CAZADORES CORRENTINOS')
City.create(province_id: 6, name: 'CERRITO')
City.create(province_id: 6, name: 'CERRUDO CUE')
City.create(province_id: 6, name: 'CHAVARRIA')
City.create(province_id: 6, name: 'COLONIA 3 DE ABRIL')
City.create(province_id: 6, name: 'COLONIA BARRIENTOS')
City.create(province_id: 6, name: 'COLONIA BUEN RETIRO')
City.create(province_id: 6, name: 'COLONIA CARLOS PELLEGRINI')
City.create(province_id: 6, name: 'COLONIA CAROLINA')
City.create(province_id: 6, name: 'COLONIA CAROLINA ,AP.')
City.create(province_id: 6, name: 'COLONIA GARABI')
City.create(province_id: 6, name: 'COLONIA ISABEL VICTORIA')
City.create(province_id: 6, name: 'COLONIA MADARIAGA')
City.create(province_id: 6, name: 'COLONIA PANDO')
City.create(province_id: 6, name: 'COLONIA PORVENIR')
City.create(province_id: 6, name: 'COLONIA PROGRESO')
City.create(province_id: 6, name: 'COLONIA PUCHETA')
City.create(province_id: 6, name: 'COLONIA ROMERO')
City.create(province_id: 6, name: 'COLONIA SAN MARTIN')
City.create(province_id: 6, name: 'COLONIA SARGENTO JUAN B. CABRAL')
City.create(province_id: 6, name: 'COLONIA TATACUA')
City.create(province_id: 6, name: 'COLONIA YATAYTI CALLE')
City.create(province_id: 6, name: 'CONCEPCION')
City.create(province_id: 6, name: 'CONI, EMILIO R.')
City.create(province_id: 6, name: 'CORONEL ABRAHAM SCHWEIZER')
City.create(province_id: 6, name: 'CORONEL DESIDERIO SOSA')
City.create(province_id: 6, name: 'CORRIENTES')
City.create(province_id: 6, name: 'COSTA GRANDE')
City.create(province_id: 6, name: 'CRUCESITA')
City.create(province_id: 6, name: 'CRUZ DE LOS MILAGROS')
City.create(province_id: 6, name: 'CUAY GRANDE')
City.create(province_id: 6, name: 'CURUZU CUATIA')
City.create(province_id: 6, name: 'DERQUI, MANUEL')
City.create(province_id: 6, name: 'DESMOCHADO')
City.create(province_id: 6, name: 'DIAZ COLODRERO,PEDRO')
City.create(province_id: 6, name: 'DOCTOR FELIX MARIA GOMEZ ,AP.')
City.create(province_id: 6, name: 'EJERCITO ARGENTINO ,DV.')
City.create(province_id: 6, name: 'EL SOMBRERO ,EMB.')
City.create(province_id: 6, name: 'EMPEDRADO LIMPIO')
City.create(province_id: 6, name: 'ENSENADA GRANDE')
City.create(province_id: 6, name: 'ESQUINA')
City.create(province_id: 6, name: 'FANEGAS')
City.create(province_id: 6, name: 'FERNANDEZ, PEDRO R.,EST.M.F.MANSILLA')
City.create(province_id: 6, name: 'GALARZA')
City.create(province_id: 6, name: 'GARRUCHOS')
City.create(province_id: 6, name: 'GDOR.IGR.VALENTIN VIRASORO.GDOR.VIRASORO')
City.create(province_id: 6, name: 'GOBERNADOR JUAN E.MARTINEZ')
City.create(province_id: 6, name: 'GOYA')
City.create(province_id: 6, name: 'GUAVIRAVI ,EST.25 DE FEBRERO')
City.create(province_id: 6, name: 'GUAYQUIRARO')
City.create(province_id: 6, name: 'HERLITKZA')
City.create(province_id: 6, name: 'HORMIGUERO')
City.create(province_id: 6, name: 'IBAHAY')
City.create(province_id: 6, name: 'IFRAN')
City.create(province_id: 6, name: 'INGENIO PRIMER CORRENTINO')
City.create(province_id: 6, name: 'ISOQUI')
City.create(province_id: 6, name: 'ITA IBATE')
City.create(province_id: 6, name: 'ITATI')
City.create(province_id: 6, name: 'ITUZAINGO')
City.create(province_id: 6, name: 'KILOMETR 402 ,AP.')
City.create(province_id: 6, name: 'KILOMETR0 167 ,AP.')
City.create(province_id: 6, name: 'KILOMETR0 301 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 104 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 120 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 161 ,PDA.')
City.create(province_id: 6, name: 'KILOMETRO 173 ,EMB')
City.create(province_id: 6, name: 'KILOMETRO 182 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 204 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 374 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 382 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 387 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 394 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 396 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 405 .AP.')
City.create(province_id: 6, name: 'KILOMETRO 406 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 410 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 416 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 431 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 442 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 451 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 459 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 470 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 476 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 479 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 485 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 489 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 492 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 501 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 504 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 506 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 512 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 516 ,AP.')
City.create(province_id: 6, name: 'KILOMETRO 517 ,AP.')
City.create(province_id: 6, name: 'LA CASUALIDAD')
City.create(province_id: 6, name: 'LA CRUZ')
City.create(province_id: 6, name: 'LABOUGLE')
City.create(province_id: 6, name: 'LAGUNA BRAVA')
City.create(province_id: 6, name: 'LAS LOMAS')
City.create(province_id: 6, name: 'LAS PALMITAS')
City.create(province_id: 6, name: 'LAVALLE')
City.create(province_id: 6, name: 'LIBERTAD')
City.create(province_id: 6, name: 'LIBERTAD ,EST.')
City.create(province_id: 6, name: 'LOMAS DE GALARZA')
City.create(province_id: 6, name: 'LOMAS DE VALLEJOS')
City.create(province_id: 6, name: 'LORETO')
City.create(province_id: 6, name: 'LOZA, MARIANO I. ,EST.JUSTINO SOLARI')
City.create(province_id: 6, name: 'MALOYAS')
City.create(province_id: 6, name: 'MALVINAS')
City.create(province_id: 6, name: 'MANANTIALES')
City.create(province_id: 6, name: 'MBURUCUYA')
City.create(province_id: 6, name: 'MERCEDES')
City.create(province_id: 6, name: 'MINUANES ,AP.')
City.create(province_id: 6, name: 'MONTE CASEROS')
City.create(province_id: 6, name: 'MONTE GRANDE')
City.create(province_id: 6, name: 'MORA')
City.create(province_id: 6, name: 'MUCHAS ISLAS')
City.create(province_id: 6, name: 'NARANJITO')
City.create(province_id: 6, name: 'NUESTRA SEÑORA DEL ROSARIO DE CAA CATI')
City.create(province_id: 6, name: 'OMBUCITO')
City.create(province_id: 6, name: 'PAGO LARGO')
City.create(province_id: 6, name: 'PAGO REDONDO')
City.create(province_id: 6, name: 'PALMAR GRANDE')
City.create(province_id: 6, name: 'PANCHO CUE')
City.create(province_id: 6, name: 'PARAJE SAN ISIDRO')
City.create(province_id: 6, name: 'PASO DE LA PATRIA')
City.create(province_id: 6, name: 'PASO DE LOS LIBRES')
City.create(province_id: 6, name: 'PASO FLORENTIN')
City.create(province_id: 6, name: 'PASO ITU')
City.create(province_id: 6, name: 'PASO PESOA')
City.create(province_id: 6, name: 'PERUGORRIA')
City.create(province_id: 6, name: 'PLAYADITO')
City.create(province_id: 6, name: 'PUCHETA ,PDA.')
City.create(province_id: 6, name: 'PUEBLO LIBERTADOR')
City.create(province_id: 6, name: 'PUENTE BATEL')
City.create(province_id: 6, name: 'PUERTO EMPEDRADO')
City.create(province_id: 6, name: 'PUERTO GOYA')
City.create(province_id: 6, name: 'PUERTO LAVALLE')
City.create(province_id: 6, name: 'PUISOYE')
City.create(province_id: 6, name: 'PUJOL, JUAN')
City.create(province_id: 6, name: 'PUNTA GRANDE')
City.create(province_id: 6, name: 'RAMADA PASO')
City.create(province_id: 6, name: 'RAMONES')
City.create(province_id: 6, name: 'RIACHUELO')
City.create(province_id: 6, name: 'SAENZ VALIENTE')
City.create(province_id: 6, name: 'SALADAS')
City.create(province_id: 6, name: 'SALDAÑA')
City.create(province_id: 6, name: 'SAN ANTONIO')
City.create(province_id: 6, name: 'SAN CARLOS')
City.create(province_id: 6, name: 'SAN COSME')
City.create(province_id: 6, name: 'SAN GABRIEL')
City.create(province_id: 6, name: 'SAN LORENZO')
City.create(province_id: 6, name: 'SAN LUIS DEL PALMAR')
City.create(province_id: 6, name: 'SAN MIGUEL')
City.create(province_id: 6, name: 'SAN ROQUE')
City.create(province_id: 6, name: 'SAN SALVADOR')
City.create(province_id: 6, name: 'SANTA ANA')
City.create(province_id: 6, name: 'SANTA LUCIA')
City.create(province_id: 6, name: 'SANTA ROSA')
City.create(province_id: 6, name: 'SANTILLAN')
City.create(province_id: 6, name: 'SANTO TOME')
City.create(province_id: 6, name: 'SAUCE')
City.create(province_id: 6, name: 'TABAY')
City.create(province_id: 6, name: 'TACUARAL')
City.create(province_id: 6, name: 'TACUARITAS')
City.create(province_id: 6, name: 'TAPEBICUA')
City.create(province_id: 6, name: 'TIMBOCITO')
City.create(province_id: 6, name: 'TORRENT')
City.create(province_id: 6, name: 'UGUAY')
City.create(province_id: 6, name: 'VACA CUA')
City.create(province_id: 6, name: 'VILLA CORDOBA')
City.create(province_id: 6, name: 'YAHAPE')
City.create(province_id: 6, name: 'YAPEYU')
City.create(province_id: 6, name: 'YAPEYU ,AP.')
City.create(province_id: 6, name: 'YOFRE, FELIPE')
City.create(province_id: 6, name: 'YUQUERI')
City.create(province_id: 7, name: '1° DE MAYO')
City.create(province_id: 7, name: '20 DE SEPTIEMBRE')
City.create(province_id: 7, name: 'ACHAGUE')
City.create(province_id: 7, name: 'ALBERTO GERCHUNOF ,PDA.')
City.create(province_id: 7, name: 'ALDEA ASUNCION')
City.create(province_id: 7, name: 'ALDEA BRASILERA')
City.create(province_id: 7, name: 'ALDEA CUESTA')
City.create(province_id: 7, name: 'ALDEA MARIA LUISA')
City.create(province_id: 7, name: 'ALDEA PROTESTANTE')
City.create(province_id: 7, name: 'ALDEA SAN ANTONIO')
City.create(province_id: 7, name: 'ALDEA SAN GREGORIO')
City.create(province_id: 7, name: 'ALDEA SAN JUAN')
City.create(province_id: 7, name: 'ALDEA SANTA MARIA')
City.create(province_id: 7, name: 'ALDEA SPATZENKUTTER')
City.create(province_id: 7, name: 'ALDEA VALLE MARIA')
City.create(province_id: 7, name: 'ALGARROBITOS')
City.create(province_id: 7, name: 'ALTAMIRANO NORTE')
City.create(province_id: 7, name: 'ALTAMIRANO SUR')
City.create(province_id: 7, name: 'ANTELO')
City.create(province_id: 7, name: 'ARANGUREN')
City.create(province_id: 7, name: 'ARROYO BARU')
City.create(province_id: 7, name: 'ARROYO CLE')
City.create(province_id: 7, name: 'ARROYO DEL MEDIO')
City.create(province_id: 7, name: 'ARROYO PALMAR ,EST.')
City.create(province_id: 7, name: 'ARROYO URQUIZA')
City.create(province_id: 7, name: 'ATENCIO')
City.create(province_id: 7, name: 'BAJADA GRANDE')
City.create(province_id: 7, name: 'BASAVILBASO')
City.create(province_id: 7, name: 'BELGRANO')
City.create(province_id: 7, name: 'BENITO LEGEREN ,AP.')
City.create(province_id: 7, name: 'BERDUC ,EST.MARTINIANO LEGUIZAMON')
City.create(province_id: 7, name: 'BERISSO ,EMB.')
City.create(province_id: 7, name: 'BETBEDER')
City.create(province_id: 7, name: 'BOCA DEL TIGRE ,AP.')
City.create(province_id: 7, name: 'BOVRIL')
City.create(province_id: 7, name: 'CALABACILLAS')
City.create(province_id: 7, name: 'CAMPS')
City.create(province_id: 7, name: 'CARBO, ENRIQUE')
City.create(province_id: 7, name: 'CEIBAS')
City.create(province_id: 7, name: 'CERRITO ,EST.COLONIA CERRITO')
City.create(province_id: 7, name: 'CHAJARI')
City.create(province_id: 7, name: 'CHAÑAR')
City.create(province_id: 7, name: 'CLARA')
City.create(province_id: 7, name: 'COLON')
City.create(province_id: 7, name: 'COLONIA ARGENTINA')
City.create(province_id: 7, name: 'COLONIA ARGENTINA')
City.create(province_id: 7, name: 'COLONIA ARRUABARRENA')
City.create(province_id: 7, name: 'COLONIA AVIGDOR')
City.create(province_id: 7, name: 'COLONIA BELEZ')
City.create(province_id: 7, name: 'COLONIA BUENA VISTA')
City.create(province_id: 7, name: 'COLONIA CASEROS ,EST.CASEROS')
City.create(province_id: 7, name: 'COLONIA CENTENARIO ,AP.')
City.create(province_id: 7, name: 'COLONIA DELTA')
City.create(province_id: 7, name: 'COLONIA EL CARMEN')
City.create(province_id: 7, name: 'COLONIA EL SAUCE')
City.create(province_id: 7, name: 'COLONIA ELIA')
City.create(province_id: 7, name: 'COLONIA ENSANCHE SAUCE')
City.create(province_id: 7, name: 'COLONIA HAMBIS')
City.create(province_id: 7, name: 'COLONIA HOCKER')
City.create(province_id: 7, name: 'COLONIA HUGHES')
City.create(province_id: 7, name: 'COLONIA NUEVA ALEMANIA')
City.create(province_id: 7, name: 'COLONIA SAN ERNESTO')
City.create(province_id: 7, name: 'COLONIA SAN MIGUEL')
City.create(province_id: 7, name: 'COLONIA SAN VICENTE')
City.create(province_id: 7, name: 'CONCEPCION DEL URUGUAY')
City.create(province_id: 7, name: 'CONCORDIA')
City.create(province_id: 7, name: 'CONSCRIPTO BERNARDI')
City.create(province_id: 7, name: 'COSTA GRANDE')
City.create(province_id: 7, name: 'CRESPO')
City.create(province_id: 7, name: 'CUCHILLA REDONDA')
City.create(province_id: 7, name: 'CURTIEMBRE')
City.create(province_id: 7, name: 'DIAMANTE')
City.create(province_id: 7, name: 'DON CRISTOBAL')
City.create(province_id: 7, name: 'DON GONZALO ,AP.')
City.create(province_id: 7, name: 'DURAZNO')
City.create(province_id: 7, name: 'EL BRILLANTE')
City.create(province_id: 7, name: 'EL CIMARRON')
City.create(province_id: 7, name: 'EL GUALEGUAY ,AP.')
City.create(province_id: 7, name: 'EL MOCHO ,AP.')
City.create(province_id: 7, name: 'EL PAGO ,AP.')
City.create(province_id: 7, name: 'EL PALENQUE ,AP.')
City.create(province_id: 7, name: 'EL PINGO')
City.create(province_id: 7, name: 'EL REDOMON')
City.create(province_id: 7, name: 'ESCRIÑA')
City.create(province_id: 7, name: 'ESTACAS')
City.create(province_id: 7, name: 'FABRICA COLON')
City.create(province_id: 7, name: 'FEBRE')
City.create(province_id: 7, name: 'FEDERACION')
City.create(province_id: 7, name: 'FEDERAL')
City.create(province_id: 7, name: 'FERNANDEZ ,EMB.')
City.create(province_id: 7, name: 'FORTUNA')
City.create(province_id: 7, name: 'GARAT, JUAN ,EST.GARAT')
City.create(province_id: 7, name: 'GENERAL ALMADA')
City.create(province_id: 7, name: 'GENERAL ALVEAR')
City.create(province_id: 7, name: 'GENERAL CAMPOS')
City.create(province_id: 7, name: 'GENERAL GALARZA')
City.create(province_id: 7, name: 'GENERAL GUEMES')
City.create(province_id: 7, name: 'GENERAL RACEDO')
City.create(province_id: 7, name: 'GENERAL RAMIREZ ,EST.RAMIREZ')
City.create(province_id: 7, name: 'GILBERT')
City.create(province_id: 7, name: 'GOBERNADOR MANSILLA')
City.create(province_id: 7, name: 'GONZALEZ CALDERON')
City.create(province_id: 7, name: 'GONZALEZ, LUCAS')
City.create(province_id: 7, name: 'GUALEGUAY')
City.create(province_id: 7, name: 'GUALEGUAYCHU')
City.create(province_id: 7, name: 'GUARDAMONTE')
City.create(province_id: 7, name: 'HASENKAMP')
City.create(province_id: 7, name: 'HERNANDEZ')
City.create(province_id: 7, name: 'HERRERA')
City.create(province_id: 7, name: 'HOLT ,EST')
City.create(province_id: 7, name: 'IBICUY')
City.create(province_id: 7, name: 'IRAZUSTA')
City.create(province_id: 7, name: 'JUAN JORGE')
City.create(province_id: 7, name: 'JUBILEO')
City.create(province_id: 7, name: 'KILOMETRO 160 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 180 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 183,AP.')
City.create(province_id: 7, name: 'KILOMETRO 200 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 208 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 213 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 306 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 325 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 33 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 340 ,PDA.')
City.create(province_id: 7, name: 'KILOMETRO 361 ,EMB.')
City.create(province_id: 7, name: 'KILOMETRO 389 ,AP.')
City.create(province_id: 7, name: 'KILOMETRO 45 ,AP.')
City.create(province_id: 7, name: 'LA ARGENTINA')
City.create(province_id: 7, name: 'LA CALANDRIA')
City.create(province_id: 7, name: 'LA CLARITA')
City.create(province_id: 7, name: 'LA CRIOLLA')
City.create(province_id: 7, name: 'LA ESMERALDA')
City.create(province_id: 7, name: 'LA GRANJA')
City.create(province_id: 7, name: 'LA HIERRA')
City.create(province_id: 7, name: 'LA LLAVE')
City.create(province_id: 7, name: 'LA PAZ')
City.create(province_id: 7, name: 'LA PICADA')
City.create(province_id: 7, name: 'LA QUERENCIA')
City.create(province_id: 7, name: 'LA VIRGEN ,AP.')
City.create(province_id: 7, name: 'LAGUNA LARGA')
City.create(province_id: 7, name: 'LARROQUE')
City.create(province_id: 7, name: 'LAS CUEVAS')
City.create(province_id: 7, name: 'LAS DELICIAS')
City.create(province_id: 7, name: 'LAS GARZAS')
City.create(province_id: 7, name: 'LAS MERCEDES')
City.create(province_id: 7, name: 'LAS MOSCAS')
City.create(province_id: 7, name: 'LAS MULITAS')
City.create(province_id: 7, name: 'LAZO')
City.create(province_id: 7, name: 'LEDESMA, CLODOMIRO')
City.create(province_id: 7, name: 'LEGUIZAMON')
City.create(province_id: 7, name: 'LIBAROS')
City.create(province_id: 7, name: 'LIEBIG')
City.create(province_id: 7, name: 'LOS CHARRUAS')
City.create(province_id: 7, name: 'LOS CONQUISTADORES')
City.create(province_id: 7, name: 'MACIA')
City.create(province_id: 7, name: 'MAGNASCO, OSVALDO')
City.create(province_id: 7, name: 'MANDISOVI')
City.create(province_id: 7, name: 'MAZARUCA')
City.create(province_id: 7, name: 'MEDANOS')
City.create(province_id: 7, name: 'MIÑONES')
City.create(province_id: 7, name: 'MOJONES NORTE')
City.create(province_id: 7, name: 'MOJONES SUR')
City.create(province_id: 7, name: 'MOLINO DOLL')
City.create(province_id: 7, name: 'MONTIEL')
City.create(province_id: 7, name: 'MONTOYA')
City.create(province_id: 7, name: 'MOREIRA')
City.create(province_id: 7, name: 'NOGOYA')
City.create(province_id: 7, name: 'NUEVA ESCOCIA')
City.create(province_id: 7, name: 'NUEVA VIZCAYA')
City.create(province_id: 7, name: 'ORO VERDE')
City.create(province_id: 7, name: 'PALAVECINO')
City.create(province_id: 7, name: 'PALMAR')
City.create(province_id: 7, name: 'PALO A PIQUE')
City.create(province_id: 7, name: 'PARANA')
City.create(province_id: 7, name: 'PARANACITO ,EST.LIB.GRL.SAN MARTIN')
City.create(province_id: 7, name: 'PARERA, FAUSTINO M.')
City.create(province_id: 7, name: 'PARERA, RAMONA A. ,EMB.')
City.create(province_id: 7, name: 'PASO DE LA LAGUNA')
City.create(province_id: 7, name: 'PASTOR BRITOS')
City.create(province_id: 7, name: 'PEDERNAL')
City.create(province_id: 7, name: 'PERDICES')
City.create(province_id: 7, name: 'PIEDRAS BLANCAS')
City.create(province_id: 7, name: 'PILOTO AVILA')
City.create(province_id: 7, name: 'PRIMER CONGRESO ,AP.')
City.create(province_id: 7, name: 'PRONUNCIAMIENTO')
City.create(province_id: 7, name: 'PUEBLO ARRUA ,EST.ALCARAZ')
City.create(province_id: 7, name: 'PUEBLO BRUGO')
City.create(province_id: 7, name: 'PUEBLO FERRE')
City.create(province_id: 7, name: 'PUEBLO GENERAL PAZ')
City.create(province_id: 7, name: 'PUEBLO MORENO')
City.create(province_id: 7, name: 'PUERTO CUPALEN')
City.create(province_id: 7, name: 'PUERTO IBICUY')
City.create(province_id: 7, name: 'PUERTO UNZUE')
City.create(province_id: 7, name: 'PUIGGARI')
City.create(province_id: 7, name: 'RAICES')
City.create(province_id: 7, name: 'RINCON DE NOGOYA')
City.create(province_id: 7, name: 'ROCAMORA')
City.create(province_id: 7, name: 'ROSARIO DE TALA ,EST.TALA')
City.create(province_id: 7, name: 'SAN BENITO')
City.create(province_id: 7, name: 'SAN GUSTAVO')
City.create(province_id: 7, name: 'SAN JAIME')
City.create(province_id: 7, name: 'SAN JORGE')
City.create(province_id: 7, name: 'SAN JOSE DE FELICIANO')
City.create(province_id: 7, name: 'SAN JUSTO')
City.create(province_id: 7, name: 'SAN RAMON')
City.create(province_id: 7, name: 'SAN SALVADOR')
City.create(province_id: 7, name: 'SAN VICTOR')
City.create(province_id: 7, name: 'SANTA ANA')
City.create(province_id: 7, name: 'SANTA ANITA')
City.create(province_id: 7, name: 'SANTA ELENA')
City.create(province_id: 7, name: 'SAUCE DE LUNA')
City.create(province_id: 7, name: 'SAUCE PINTO')
City.create(province_id: 7, name: 'SEGUI')
City.create(province_id: 7, name: 'SOLA')
City.create(province_id: 7, name: 'SOSA')
City.create(province_id: 7, name: 'STROBEL')
City.create(province_id: 7, name: 'TABOSSI')
City.create(province_id: 7, name: 'TALITA')
City.create(province_id: 7, name: 'TALITAS ,AP.')
City.create(province_id: 7, name: 'TENIENTE 1Â° BRIGIDO CAINZO ,AP.')
City.create(province_id: 7, name: 'TEZANOS PINTO')
City.create(province_id: 7, name: 'TRES BOCAS')
City.create(province_id: 7, name: 'UBAJAY')
City.create(province_id: 7, name: 'URDINARRAIN')
City.create(province_id: 7, name: 'VIALE')
City.create(province_id: 7, name: 'VICTORIA')
City.create(province_id: 7, name: 'VILLA DEL ROSARIO')
City.create(province_id: 7, name: 'VILLA DOMINGUEZ ,EST.DOMINGUEZ')
City.create(province_id: 7, name: 'VILLA ELISA')
City.create(province_id: 7, name: 'VILLA HERNANDARIAS')
City.create(province_id: 7, name: 'VILLA MANTERO')
City.create(province_id: 7, name: 'VILLA MARIA GRANDE')
City.create(province_id: 7, name: 'VILLA NUEVA MONTEVIDEO')
City.create(province_id: 7, name: 'VILLA PARANACITO')
City.create(province_id: 7, name: 'VILLA SAN JOSE')
City.create(province_id: 8, name: 'VILLA SAN JOSE')
City.create(province_id: 7, name: 'VILLA SAN MARCIAL ,EST.GDR.URQUIZA')
City.create(province_id: 7, name: 'VILLA URQUIZA')
City.create(province_id: 7, name: 'VILLA ZORRAQUIN')
City.create(province_id: 7, name: 'VILLAGUAY')
City.create(province_id: 7, name: 'YAROS')
City.create(province_id: 7, name: 'YERUA')
City.create(province_id: 7, name: 'YESO')
City.create(province_id: 7, name: 'YUQUERI')
City.create(province_id: 8, name: 'APAYEREY')
City.create(province_id: 8, name: 'BARTOLOME DE LAS CASAS')
City.create(province_id: 8, name: 'BOUVIER')
City.create(province_id: 8, name: 'BRUCHARD')
City.create(province_id: 8, name: 'BUENA VISTA')
City.create(province_id: 8, name: 'CABO 1RO. LUGONES')
City.create(province_id: 8, name: 'CAMPO ALEGRE')
City.create(province_id: 8, name: 'CLORINDA')
City.create(province_id: 8, name: 'COLONIA ALTO ALEGRE')
City.create(province_id: 8, name: 'COLONIA BUENA VISTA')
City.create(province_id: 8, name: 'COLONIA CAMPO VILLAFAÑE')
City.create(province_id: 8, name: 'COLONIA PASTORIL')
City.create(province_id: 8, name: 'COLONIA PERIN')
City.create(province_id: 8, name: 'COMANDANTE FONTANA')
City.create(province_id: 8, name: 'CORONEL ARGENTINO LARRABURE')
City.create(province_id: 8, name: 'DE LAS CASAS, BARTOLOME')
City.create(province_id: 8, name: 'DEL CAMPO, ESTANISLAO')
City.create(province_id: 8, name: 'DOCTOR CARLOS MONTAG')
City.create(province_id: 8, name: 'DOCTOR E.RAMOS MEJIAS ,EST.CHIRIGUANOS')
City.create(province_id: 8, name: 'DOCTOR GUMERSINDO SAYAGO')
City.create(province_id: 8, name: 'DOCTOR JOSE DE GASPRI')
City.create(province_id: 8, name: 'DOCTOR LUIS AGOTE')
City.create(province_id: 8, name: 'EL CHAÑARAL')
City.create(province_id: 8, name: 'EL COATI')
City.create(province_id: 8, name: 'EL COLORADO')
City.create(province_id: 8, name: 'EL PERDIDO')
City.create(province_id: 8, name: 'EL TOTORAL')
City.create(province_id: 8, name: 'ESPINILLO')
City.create(province_id: 8, name: 'ESTERO PATIÑO ,AP.')
City.create(province_id: 8, name: 'FORMOSA')
City.create(province_id: 8, name: 'FORTIN PILCOMAYO')
City.create(province_id: 8, name: 'FORTIN SARGENTO 1Âº LEYES')
City.create(province_id: 8, name: 'FORTIN SOLEDAD')
City.create(province_id: 8, name: 'GENERAL ENRIQUE MOSCONI')
City.create(province_id: 8, name: 'GENERAL FRANCISCO BASILIANO BOSCH')
City.create(province_id: 8, name: 'GRAN GUARDIA')
City.create(province_id: 8, name: 'GUADALCAZAR')
City.create(province_id: 8, name: 'HERRADURA')
City.create(province_id: 8, name: 'IBARRETA')
City.create(province_id: 8, name: 'INGENIERO ENRIQUE H.FAURE')
City.create(province_id: 8, name: 'INGENIERO GUILLERMO N.JUAREZ')
City.create(province_id: 8, name: 'KILOMETRO 1769')
City.create(province_id: 8, name: 'KILOMETRO 1895 ,AP.')
City.create(province_id: 8, name: 'KILOMETRO 213')
City.create(province_id: 8, name: 'LA ESPERANZA')
City.create(province_id: 8, name: 'LA FLORENCIA')
City.create(province_id: 8, name: 'LA FRONTERA')
City.create(province_id: 8, name: 'LA ISLETA')
City.create(province_id: 8, name: 'LA PRIMAVERA')
City.create(province_id: 8, name: 'LA SIRENA')
City.create(province_id: 8, name: 'LAGUNA BLANCA')
City.create(province_id: 8, name: 'LAGUNA NAICK-NECK')
City.create(province_id: 8, name: 'LAGUNA YEMA')
City.create(province_id: 8, name: 'LAPRIDA, FRANCISCO NARCISO DE')
City.create(province_id: 8, name: 'LAS LOMITAS')
City.create(province_id: 8, name: 'LOA MATACOS')
City.create(province_id: 8, name: 'LOS PILAGAS ,EMB.')
City.create(province_id: 8, name: 'MEDIA LUNA')
City.create(province_id: 8, name: 'MISION TACAAGLE')
City.create(province_id: 8, name: 'MISION YACARE')
City.create(province_id: 8, name: 'MONTE LINDO CHICO')
City.create(province_id: 8, name: 'PALMA SOLA')
City.create(province_id: 8, name: 'PALMA SOLA')
City.create(province_id: 8, name: 'PALMARCITO')
City.create(province_id: 8, name: 'PALO SANTO')
City.create(province_id: 8, name: 'PASO, JUAN JOSE')
City.create(province_id: 8, name: 'PIRANE')
City.create(province_id: 8, name: 'PORTEÑO VIEJO')
City.create(province_id: 8, name: 'POSTA CAMBIO A ZALAZAR')
City.create(province_id: 8, name: 'POSTA KILOMETRO 45')
City.create(province_id: 8, name: 'POZO DEL TIGRE')
City.create(province_id: 8, name: 'PRESIDENTE YRIGOYEN')
City.create(province_id: 8, name: 'PUERTO CABO IRIGOYEN')
City.create(province_id: 8, name: 'PUERTO DALMACIA')
City.create(province_id: 8, name: 'PUERTO PILCOMAYO')
City.create(province_id: 8, name: 'PUERTO VELAZ')
City.create(province_id: 8, name: 'SAN CAMILO')
City.create(province_id: 8, name: 'SAN FRANCISCO DE LAISHI')
City.create(province_id: 8, name: 'SAN HILARIO')
City.create(province_id: 8, name: 'SAN MARTIN 1')
City.create(province_id: 8, name: 'SAN MARTIN 2')
City.create(province_id: 8, name: 'SAN RAMON')
City.create(province_id: 8, name: 'SARGENTO AYUDANTE VICTOR SANABRIA')
City.create(province_id: 8, name: 'SELVA MARIA')
City.create(province_id: 8, name: 'SIETE PALMAS')
City.create(province_id: 8, name: 'TENIENTE BROWN')
City.create(province_id: 8, name: 'TENIENTE GENERAL JUAN CARLOS SANCHEZ')
City.create(province_id: 8, name: 'TENIENTE GENERAL ROSENDO M FRAGA')
City.create(province_id: 8, name: 'TRES LAGUNAS')
City.create(province_id: 8, name: 'VILLA ESCOLAR')
City.create(province_id: 9, name: '23 DE AGOSTO')
City.create(province_id: 9, name: 'ABDON CASTRO TOLAY')
City.create(province_id: 9, name: 'ABRA LAITE')
City.create(province_id: 9, name: 'ABRA PAMPA')
City.create(province_id: 9, name: 'AGUA CALIENTE')
City.create(province_id: 9, name: 'AGUA CALIENTE')
City.create(province_id: 9, name: 'AGUA CHICA')
City.create(province_id: 9, name: 'AGUADITA')
City.create(province_id: 9, name: 'AGUAS CALIENTES')
City.create(province_id: 9, name: 'ALTO LA TORRE')
City.create(province_id: 9, name: 'ALTO LA VIÑA')
City.create(province_id: 9, name: 'BORDO LA ISLA')
City.create(province_id: 9, name: 'CAIMANCITO')
City.create(province_id: 9, name: 'CALILEGUA')
City.create(province_id: 9, name: 'CANGREJILLOS')
City.create(province_id: 9, name: 'CAPLA')
City.create(province_id: 9, name: 'CARACARA')
City.create(province_id: 9, name: 'CARAHUASI')
City.create(province_id: 9, name: 'CASABINDO')
City.create(province_id: 9, name: 'CASPALA')
City.create(province_id: 9, name: 'CASTRO TOLAY, ABDON')
City.create(province_id: 9, name: 'CATUA')
City.create(province_id: 9, name: 'CERRILLOS')
City.create(province_id: 9, name: 'CHALICAN')
City.create(province_id: 9, name: 'CHAÑI ,AP.')
City.create(province_id: 9, name: 'CHAUPI RODERO')
City.create(province_id: 9, name: 'CHURQUI')
City.create(province_id: 9, name: 'CIENAGUILLAS')
City.create(province_id: 9, name: 'COCHINOCA')
City.create(province_id: 9, name: 'CONDOR')
City.create(province_id: 9, name: 'CORANZULI')
City.create(province_id: 9, name: 'CORAYA')
City.create(province_id: 9, name: 'CORRAL BLANCO')
City.create(province_id: 9, name: 'EL AGUILAR')
City.create(province_id: 9, name: 'EL BRETE')
City.create(province_id: 9, name: 'EL CARMEN')
City.create(province_id: 9, name: 'EL CARRIL')
City.create(province_id: 9, name: 'EL CEIBAL')
City.create(province_id: 9, name: 'EL MORENO')
City.create(province_id: 9, name: 'EL PARQUE')
City.create(province_id: 9, name: 'EL PIQUETE')
City.create(province_id: 9, name: 'EL PORVENIR')
City.create(province_id: 9, name: 'EL QUEMADO')
City.create(province_id: 9, name: 'EL REMATE')
City.create(province_id: 9, name: 'EL SUNCHAL')
City.create(province_id: 9, name: 'ESCAYA')
City.create(province_id: 9, name: 'FRAILE PINTADO')
City.create(province_id: 9, name: 'GALAN, JUAN')
City.create(province_id: 9, name: 'GUERRERO')
City.create(province_id: 9, name: 'HORNILLOS')
City.create(province_id: 9, name: 'HUACALERA')
City.create(province_id: 9, name: 'HUMAHUACA')
City.create(province_id: 9, name: 'INGENIO LA ESPERANZA')
City.create(province_id: 9, name: 'INTI CANCHA')
City.create(province_id: 9, name: 'ITURBE')
City.create(province_id: 9, name: 'KILOMETRO 1129 ,DV.')
City.create(province_id: 9, name: 'KILOMETRO 1137 ,EST.')
City.create(province_id: 9, name: 'KILOMETRO 1149 ,AP.')
City.create(province_id: 9, name: 'KILOMETRO 1183 ,AP.')
City.create(province_id: 9, name: 'KILOMETRO 1210 ,DV.')
City.create(province_id: 9, name: 'KILOMETRO 1243 ,AP.')
City.create(province_id: 9, name: 'KILOMETRO 1247')
City.create(province_id: 9, name: 'KILOMETRO 1278')
City.create(province_id: 9, name: 'KILOMETRO 1289 ,AP.')
City.create(province_id: 9, name: 'KILOMETRO 1321 ,DV.')
City.create(province_id: 9, name: 'KILOMETRO 1373 ,AP.')
City.create(province_id: 9, name: 'LA ALMONA')
City.create(province_id: 9, name: 'LA CAPILLA')
City.create(province_id: 9, name: 'LA CUEVA')
City.create(province_id: 9, name: 'LA MENDIETA')
City.create(province_id: 9, name: 'LA QUIACA')
City.create(province_id: 9, name: 'LA TOMA')
City.create(province_id: 9, name: 'LAGUNA')
City.create(province_id: 9, name: 'LAS CUEVAS')
City.create(province_id: 9, name: 'LEON')
City.create(province_id: 9, name: 'LIBERTADOR GRL.SAN MARTIN, EST.LEDESMA')
City.create(province_id: 9, name: 'LOS ALISOS')
City.create(province_id: 9, name: 'LOS BLANCOS')
City.create(province_id: 9, name: 'LOS CHANCHILLOS')
City.create(province_id: 9, name: 'LOS LAPACHOS ,EST.MAQUINISTA VERON')
City.create(province_id: 9, name: 'LOS PERALES')
City.create(province_id: 9, name: 'MADREJON')
City.create(province_id: 9, name: 'MAIMARA')
City.create(province_id: 9, name: 'MEDANITOS')
City.create(province_id: 9, name: 'MINA AJEDREZ')
City.create(province_id: 9, name: 'MINA PIRQUITAS')
City.create(province_id: 9, name: 'MONTE RICO')
City.create(province_id: 9, name: 'MONTE RICO ,AP.')
City.create(province_id: 9, name: 'OLACAPATO ,EST.')
City.create(province_id: 9, name: 'OLAROZ CHICO')
City.create(province_id: 9, name: 'OLAROZ GRANDE')
City.create(province_id: 9, name: 'ORATORIO')
City.create(province_id: 9, name: 'OROSMAYO')
City.create(province_id: 9, name: 'PAIRIQUE CHICO')
City.create(province_id: 9, name: 'PAIRIQUE GRANDE')
City.create(province_id: 9, name: 'PALCA DE APARZO')
City.create(province_id: 9, name: 'PALMA SOLA')
City.create(province_id: 9, name: 'PALPALA ,EST.GRL.MANUEL N.SAVIO')
City.create(province_id: 9, name: 'PAMPA BLANCA')
City.create(province_id: 9, name: 'PAMPICHUELA')
City.create(province_id: 9, name: 'PERICO')
City.create(province_id: 9, name: 'PUEBLO LEDESMA')
City.create(province_id: 9, name: 'PUEBLO VIEJO')
City.create(province_id: 9, name: 'PUESTO DEL MARQUES')
City.create(province_id: 9, name: 'PUESTO GRANDE')
City.create(province_id: 9, name: 'PUMAHUASI')
City.create(province_id: 9, name: 'PURMAMARCA')
City.create(province_id: 9, name: 'QUICHAGUA')
City.create(province_id: 9, name: 'REYES')
City.create(province_id: 9, name: 'RINCONADA')
City.create(province_id: 9, name: 'RINCONADILLAS')
City.create(province_id: 9, name: 'RIO BLANCO ,AP.')
City.create(province_id: 9, name: 'RIO GRANDE')
City.create(province_id: 9, name: 'RODERO')
City.create(province_id: 9, name: 'ROSARIO')
City.create(province_id: 9, name: 'ROSARIO')
City.create(province_id: 9, name: 'SAN ANTONIO')
City.create(province_id: 9, name: 'SAN BERNARDO')
City.create(province_id: 9, name: 'SAN JAVIER')
City.create(province_id: 9, name: 'SAN JUAN DE DIOS')
City.create(province_id: 9, name: 'SAN JUAN DE ORO')
City.create(province_id: 9, name: 'SAN JUAN DE PALCA')
City.create(province_id: 9, name: 'SAN JUANCITO')
City.create(province_id: 9, name: 'SAN JUANCITO')
City.create(province_id: 9, name: 'SAN PEDRITO')
City.create(province_id: 9, name: 'SAN PEDRO ,EST.SAN PEDRO DE JUJUY')
City.create(province_id: 9, name: 'SAN SALVADOR DE JUJUY ,EST.JUJUY')
City.create(province_id: 9, name: 'SANTA ANA')
City.create(province_id: 9, name: 'SANTA BARBARA')
City.create(province_id: 9, name: 'SANTA CATALINA')
City.create(province_id: 9, name: 'SANTA CLARA')
City.create(province_id: 9, name: 'SANTO DOMINGO')
City.create(province_id: 9, name: 'SAYATE')
City.create(province_id: 9, name: 'SENADOR PEREZ')
City.create(province_id: 9, name: 'SEY')
City.create(province_id: 9, name: 'SIBERIA')
City.create(province_id: 9, name: 'SOL DE MAYO')
City.create(province_id: 9, name: 'SURIPUGIO')
City.create(province_id: 9, name: 'SUSQUES')
City.create(province_id: 9, name: 'TABLADITAS')
City.create(province_id: 9, name: 'TAFNA')
City.create(province_id: 9, name: 'TERMAS DE REYES')
City.create(province_id: 9, name: 'TILCARA')
City.create(province_id: 9, name: 'TIMON CRUZ')
City.create(province_id: 9, name: 'TIOMAYO')
City.create(province_id: 9, name: 'TIONSO')
City.create(province_id: 9, name: 'TRES CRUCES')
City.create(province_id: 9, name: 'TRES MORROS')
City.create(province_id: 9, name: 'TUMBAYA')
City.create(province_id: 9, name: 'TURU TARI')
City.create(province_id: 9, name: 'TUSAQUILLA')
City.create(province_id: 9, name: 'UQUIA')
City.create(province_id: 9, name: 'VALLE COLORADO')
City.create(province_id: 9, name: 'VALLE GRANDE')
City.create(province_id: 9, name: 'VILLA ACHAVAL')
City.create(province_id: 9, name: 'VOLCAN')
City.create(province_id: 9, name: 'YALA')
City.create(province_id: 9, name: 'YAVI')
City.create(province_id: 9, name: 'YOSCABA')
City.create(province_id: 9, name: 'YUTO')
City.create(province_id: 9, name: 'ZAPLA')
City.create(province_id: 10, name: 'ABRAMO')
City.create(province_id: 10, name: 'ADOLFO VAN PRAET')
City.create(province_id: 10, name: 'AGUSTONI')
City.create(province_id: 10, name: 'ALFREDO PEÑA')
City.create(province_id: 10, name: 'ALGARROBO DEL AGUILA')
City.create(province_id: 10, name: 'ALPACHIRI')
City.create(province_id: 10, name: 'ALTA ITALIA')
City.create(province_id: 10, name: 'ANGUIL')
City.create(province_id: 10, name: 'ANZOATEGUI')
City.create(province_id: 10, name: 'APUYACO')
City.create(province_id: 10, name: 'ARATA')
City.create(province_id: 10, name: 'ATALIVA ROCA')
City.create(province_id: 10, name: 'ATREUCO')
City.create(province_id: 10, name: 'BAJO DE LAS PALOMAS')
City.create(province_id: 10, name: 'BERNARDO LARROUDE')
City.create(province_id: 10, name: 'BERNASCONI')
City.create(province_id: 10, name: 'BOEUF')
City.create(province_id: 10, name: 'BUTA RANQUIL')
City.create(province_id: 10, name: 'CACHIRULO')
City.create(province_id: 10, name: 'CALEUFU')
City.create(province_id: 10, name: 'CANE, MIGUEL')
City.create(province_id: 10, name: 'CARRO QUEMADO')
City.create(province_id: 10, name: 'CASTEX, EDUARDO')
City.create(province_id: 10, name: 'CATRILO')
City.create(province_id: 10, name: 'CEBALLOS')
City.create(province_id: 10, name: 'CEREALES')
City.create(province_id: 10, name: 'CHACHARRAMENDI')
City.create(province_id: 10, name: 'CHAMAICO')
City.create(province_id: 10, name: 'CHICAL CO')
City.create(province_id: 10, name: 'COLONIA 25 DE MAYO')
City.create(province_id: 10, name: 'COLONIA BARON')
City.create(province_id: 10, name: 'COLONIA EMILIO MITRE')
City.create(province_id: 10, name: 'COLONIA INES Y CARLOTA')
City.create(province_id: 10, name: 'COLONIA LA PASTORIL')
City.create(province_id: 10, name: 'COLONIA SAN JOSE')
City.create(province_id: 10, name: 'COLONIA SANTA TERESA')
City.create(province_id: 10, name: 'CONHELO')
City.create(province_id: 10, name: 'CORONEL HILARIO LAGOS')
City.create(province_id: 10, name: 'COTITA')
City.create(province_id: 10, name: 'CUCHILLO-CO')
City.create(province_id: 10, name: 'DOBLAS')
City.create(province_id: 10, name: 'DORILA')
City.create(province_id: 10, name: 'EL DURAZNO')
City.create(province_id: 10, name: 'EMBAJADOR MARTINI')
City.create(province_id: 10, name: 'EPU-PEL')
City.create(province_id: 10, name: 'FALUCHO')
City.create(province_id: 10, name: 'GAMAY')
City.create(province_id: 10, name: 'GAVIOTAS')
City.create(province_id: 10, name: 'GENERAL ACHA')
City.create(province_id: 10, name: 'GENERAL MANUEL CAMPOS')
City.create(province_id: 10, name: 'GENERAL PICO')
City.create(province_id: 10, name: 'GENERAL SAN MARTIN')
City.create(province_id: 10, name: 'GOBERNADOR AYALA')
City.create(province_id: 10, name: 'GOBERNADOR DUVAL')
City.create(province_id: 10, name: 'GUATRACHE')
City.create(province_id: 10, name: 'HIDALGO')
City.create(province_id: 10, name: 'HUCAL')
City.create(province_id: 10, name: 'HUELEN')
City.create(province_id: 10, name: 'INGENIERO FOSTER')
City.create(province_id: 10, name: 'INGENIERO LUIGGI')
City.create(province_id: 10, name: 'INTENDENTE ALVEAR')
City.create(province_id: 10, name: 'IVANOWSKY')
City.create(province_id: 10, name: 'KILOMETRO 755 ,DV.')
City.create(province_id: 10, name: 'LA ADELA')
City.create(province_id: 10, name: 'LA ASTURIANA')
City.create(province_id: 10, name: 'LA COPELINA')
City.create(province_id: 10, name: 'LA ESTRELLA')
City.create(province_id: 10, name: 'LA GLORIA')
City.create(province_id: 10, name: 'LA MARUJA')
City.create(province_id: 10, name: 'LA PRIMAVERA')
City.create(province_id: 10, name: 'LA REFORMA')
City.create(province_id: 10, name: 'LARROUDE, BERNARDO')
City.create(province_id: 10, name: 'LAVALLE, RICARDO')
City.create(province_id: 10, name: 'LIHUEL CALEL')
City.create(province_id: 10, name: 'LIMAY MAHUIDA')
City.create(province_id: 10, name: 'LONQUIMAY')
City.create(province_id: 10, name: 'LOVENTUE')
City.create(province_id: 10, name: 'LUAN TORO')
City.create(province_id: 10, name: 'MACACHIN')
City.create(province_id: 10, name: 'MAISONAVE, DAMIAN ,EST.SIMSON')
City.create(province_id: 10, name: 'MAYER, MAURICIO')
City.create(province_id: 10, name: 'METILEO')
City.create(province_id: 10, name: 'MONTE NIEVAS')
City.create(province_id: 10, name: 'NAICO')
City.create(province_id: 10, name: 'OJEDA')
City.create(province_id: 10, name: 'OLONIA SANTA MARIA')
City.create(province_id: 10, name: 'PARERA')
City.create(province_id: 10, name: 'PASO DE LOS ALGARROBOS')
City.create(province_id: 10, name: 'PEÑA, ALFREDO')
City.create(province_id: 10, name: 'PERU')
City.create(province_id: 10, name: 'PICHI HUINCA')
City.create(province_id: 10, name: 'PUELCHES')
City.create(province_id: 10, name: 'PUELEN')
City.create(province_id: 10, name: 'QUEHUE')
City.create(province_id: 10, name: 'QUEMU QUEMU')
City.create(province_id: 10, name: 'QUETREQUEN')
City.create(province_id: 10, name: 'RANCUL')
City.create(province_id: 10, name: 'REALICO')
City.create(province_id: 10, name: 'RELMO')
City.create(province_id: 10, name: 'REMECO')
City.create(province_id: 10, name: 'RIGLOS, MIGUEL')
City.create(province_id: 10, name: 'ROCA, ATALIVA')
City.create(province_id: 10, name: 'ROLON')
City.create(province_id: 10, name: 'RUCANELO')
City.create(province_id: 10, name: 'SANTA ISABEL')
City.create(province_id: 10, name: 'SANTA ROSA')
City.create(province_id: 10, name: 'SARAH')
City.create(province_id: 10, name: 'SPELUZZI')
City.create(province_id: 10, name: 'TELEN')
City.create(province_id: 10, name: 'TENIENTE GENERAL EMILIO MITRE')
City.create(province_id: 10, name: 'TOAY')
City.create(province_id: 10, name: 'TREBOLARES')
City.create(province_id: 10, name: 'TRENEL')
City.create(province_id: 10, name: 'TRILI')
City.create(province_id: 10, name: 'UNANJE')
City.create(province_id: 10, name: 'URIBURU')
City.create(province_id: 10, name: 'UTRACAN')
City.create(province_id: 10, name: 'VAN PRAET, ADOLFO')
City.create(province_id: 10, name: 'VERTIZ')
City.create(province_id: 10, name: 'VICTORICA')
City.create(province_id: 10, name: 'VILLA MIRASOL')
City.create(province_id: 10, name: 'WINIFREDA')
City.create(province_id: 11, name: 'AGUA BLANCA')
City.create(province_id: 11, name: 'AGUAYO')
City.create(province_id: 11, name: 'AICUÑA')
City.create(province_id: 11, name: 'AIMOGASTA')
City.create(province_id: 11, name: 'ALCAZAR')
City.create(province_id: 11, name: 'ALPASINCHE')
City.create(province_id: 11, name: 'AMANA')
City.create(province_id: 11, name: 'AMBIL')
City.create(province_id: 11, name: 'AMINGA')
