Province.create(name: 'BUENOS AIRES', country_id: 1)
Province.create(name: 'CATAMARCA', country_id: 1)
Province.create(name: 'CHACO', country_id: 1)
Province.create(name: 'CHUBUT', country_id: 1)
Province.create(name: 'CORDOBA', country_id: 1)
Province.create(name: 'CORRIENTES', country_id: 1)
Province.create(name: 'ENTRE RIOS', country_id: 1)
Province.create(name: 'FORMOSA', country_id: 1)
Province.create(name: 'JUJUY', country_id: 1)
Province.create(name: 'LA PAMPA', country_id: 1)
Province.create(name: 'LA RIOJA', country_id: 1)
Province.create(name: 'MENDOZA', country_id: 1)
Province.create(name: 'MISIONES', country_id: 1)
Province.create(name: 'NEUQUEN', country_id: 1)
Province.create(name: 'RIO NEGRO', country_id: 1)
Province.create(name: 'SALTA', country_id: 1)
Province.create(name: 'SAN JUAN', country_id: 1)
Province.create(name: 'SAN LUIS', country_id: 1)
Province.create(name: 'SANTA CRUZ', country_id: 1)
Province.create(name: 'SANTA FE', country_id: 1)
Province.create(name: 'SANTIAGO DEL ESTERO', country_id: 1)
Province.create(name: 'TIERRA DEL FUEGO', country_id: 1)
Province.create(name: 'TUCUMAN', country_id: 1)

Province.create(name: 'MARANHAO', country_id: 2)
Province.create(name: 'MATO GROSSO', country_id: 2)